'use strict';

// Secure bridge: exposes a minimal, typed API to the renderer. The renderer
// never gets Node or ipcRenderer directly (contextIsolation stays on).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('aria', {
  config: () => ipcRenderer.invoke('aria:config'),
  ask: (text, history) => ipcRenderer.invoke('aria:ask', { text, history }),
  stt: {
    available: () => ipcRenderer.invoke('stt:available'),
    info: () => ipcRenderer.invoke('stt:info'),
    // payload is either { base64, sampleRate } for local PCM, or { base64, mime }
    // for the cloud audio-file path.
    transcribe: (payload) => ipcRenderer.invoke('stt:transcribe', payload),
  },
  stocks: {
    quote: (symbol) => ipcRenderer.invoke('stocks:quote', symbol),
    quotes: (symbols) => ipcRenderer.invoke('stocks:quotes', symbols),
    search: (query) => ipcRenderer.invoke('stocks:search', query),
    news: (query) => ipcRenderer.invoke('stocks:news', query),
    history: (symbol, range) => ipcRenderer.invoke('stocks:history', { symbol, range }),
    watchlist: () => ipcRenderer.invoke('stocks:watchlist'),
    watchlistQuotes: () => ipcRenderer.invoke('stocks:watchlist:quotes'),
    addToWatchlist: (symbol) => ipcRenderer.invoke('stocks:watchlist:add', symbol),
    removeFromWatchlist: (symbol) => ipcRenderer.invoke('stocks:watchlist:remove', symbol),
  },
  trading: {
    portfolio: () => ipcRenderer.invoke('trading:portfolio'),
    pending: () => ipcRenderer.invoke('trading:pending'),
    propose: (order) => ipcRenderer.invoke('trading:propose', order),
    approve: (id) => ipcRenderer.invoke('trading:approve', id),
    reject: (id) => ipcRenderer.invoke('trading:reject', id),
    orders: () => ipcRenderer.invoke('trading:orders'),
    reset: () => ipcRenderer.invoke('trading:reset'),
  },
  productivity: {
    tasks: (filter) => ipcRenderer.invoke('prod:tasks', filter),
    addTask: (t) => ipcRenderer.invoke('prod:task:add', t),
    completeTask: (id) => ipcRenderer.invoke('prod:task:complete', id),
    deleteTask: (id) => ipcRenderer.invoke('prod:task:delete', id),
    briefing: () => ipcRenderer.invoke('prod:briefing'),
  },
  alerts: {
    list: () => ipcRenderer.invoke('alerts:list'),
    add: (a) => ipcRenderer.invoke('alerts:add', a),
    remove: (id) => ipcRenderer.invoke('alerts:remove', id),
    // main -> renderer push when an alert fires
    onTriggered: (cb) => ipcRenderer.on('alert:triggered', (_e, data) => cb(data)),
  },
  google: {
    status: () => ipcRenderer.invoke('google:status'),
    connect: () => ipcRenderer.invoke('google:connect'),
    disconnect: () => ipcRenderer.invoke('google:disconnect'),
    agenda: () => ipcRenderer.invoke('google:agenda'),
    inbox: () => ipcRenderer.invoke('google:inbox'),
  },
  broker: {
    status: () => ipcRenderer.invoke('broker:status'),
    connect: (creds) => ipcRenderer.invoke('broker:connect', creds),
    disconnect: () => ipcRenderer.invoke('broker:disconnect'),
    encryptionAvailable: () => ipcRenderer.invoke('broker:encryptionAvailable'),
  },
  accounting: {
    summary: (range) => ipcRenderer.invoke('acct:summary', range),
    txns: (filter) => ipcRenderer.invoke('acct:txns', filter),
    addTxn: (t) => ipcRenderer.invoke('acct:txn:add', t),
    deleteTxn: (id) => ipcRenderer.invoke('acct:txn:delete', id),
    categories: () => ipcRenderer.invoke('acct:categories'),
    invoices: (filter) => ipcRenderer.invoke('acct:invoices', filter),
    addInvoice: (inv) => ipcRenderer.invoke('acct:invoice:add', inv),
    markPaid: (id) => ipcRenderer.invoke('acct:invoice:paid', id),
    deleteInvoice: (id) => ipcRenderer.invoke('acct:invoice:delete', id),
  },
  study: {
    stats: () => ipcRenderer.invoke('study:stats'),
    due: (filter) => ipcRenderer.invoke('study:due', filter),
    review: (id, grade) => ipcRenderer.invoke('study:review', { id, grade }),
    addCard: (c) => ipcRenderer.invoke('study:card:add', c),
    addVocab: (v) => ipcRenderer.invoke('study:vocab:add', v),
    deleteCard: (id) => ipcRenderer.invoke('study:card:delete', id),
    notes: (filter) => ipcRenderer.invoke('study:notes', filter),
    addNote: (n) => ipcRenderer.invoke('study:note:add', n),
    deleteNote: (id) => ipcRenderer.invoke('study:note:delete', id),
    log: (s) => ipcRenderer.invoke('study:log', s),
    cpa: () => ipcRenderer.invoke('study:cpa'),
    setCpa: (p) => ipcRenderer.invoke('study:cpa:set', p),
  },
  strategy: {
    idea: (symbol) => ipcRenderer.invoke('strategy:idea', symbol),
    scan: () => ipcRenderer.invoke('strategy:scan'),
  },
  language: {
    languages: () => ipcRenderer.invoke('lang:languages'),
    curriculum: () => ipcRenderer.invoke('lang:curriculum'),
    profile: () => ipcRenderer.invoke('lang:profile'),
    setLanguage: (p) => ipcRenderer.invoke('lang:setLanguage', p),
    progress: (lang) => ipcRenderer.invoke('lang:progress', lang),
    missions: (lang) => ipcRenderer.invoke('lang:missions', lang),
    completeMission: (p) => ipcRenderer.invoke('lang:mission:complete', p),
    addVocab: (v) => ipcRenderer.invoke('lang:vocab:add', v),
    due: (lang) => ipcRenderer.invoke('lang:due', lang),
  },
  agents: {
    roster: () => ipcRenderer.invoke('agents:roster'),
    route: (text) => ipcRenderer.invoke('agents:route', text),
    activity: () => ipcRenderer.invoke('agents:activity'),
  },
  memory: {
    list: (query) => ipcRenderer.invoke('memory:list', query),
    remember: (m) => ipcRenderer.invoke('memory:remember', m),
    forget: (p) => ipcRenderer.invoke('memory:forget', p),
  },
  sidecar: {
    status: () => ipcRenderer.invoke('sidecar:status'),
    // Generic REST passthrough for Phase 13 operational platform.
    request: (method, route, body) => ipcRenderer.invoke('sidecar:request', { method, route, body }),
    analyze: (p) => ipcRenderer.invoke('sidecar:analyze', p),
    factors: (p) => ipcRenderer.invoke('sidecar:factors', p),
    risk: (p) => ipcRenderer.invoke('sidecar:risk', p),
    portfolio: (p) => ipcRenderer.invoke('sidecar:portfolio', p),
    ascTopics: () => ipcRenderer.invoke('sidecar:ascTopics'),
    explainAsc: (topic) => ipcRenderer.invoke('sidecar:explainAsc', topic),
    memo: (p) => ipcRenderer.invoke('sidecar:memo', p),
    acctBriefing: (refresh) => ipcRenderer.invoke('sidecar:acctBriefing', refresh),
    acctIntel: (source) => ipcRenderer.invoke('sidecar:acctIntel', source),
    acctIntelRefresh: () => ipcRenderer.invoke('sidecar:acctIntelRefresh'),
    acctGraph: (asc) => ipcRenderer.invoke('sidecar:acctGraph', asc),
    checklist: (topic) => ipcRenderer.invoke('sidecar:checklist', topic),
    memoFull: (p) => ipcRenderer.invoke('sidecar:memoFull', p),
    fundamentals: (p) => ipcRenderer.invoke('sidecar:fundamentals', p),
    signal: (p) => ipcRenderer.invoke('sidecar:signal', p),
    marketBriefing: (p) => ipcRenderer.invoke('sidecar:marketBriefing', p),
    n8nStatus: () => ipcRenderer.invoke('sidecar:n8nStatus'),
    n8nWorkflows: () => ipcRenderer.invoke('sidecar:n8nWorkflows'),
    n8nGenerate: (p) => ipcRenderer.invoke('sidecar:n8nGenerate', p),
    createTask: (p) => ipcRenderer.invoke('sidecar:createTask', p),
    listTasks: (status) => ipcRenderer.invoke('sidecar:listTasks', status),
    completeTask: (tid) => ipcRenderer.invoke('sidecar:completeTask', tid),
    deleteTask: (tid) => ipcRenderer.invoke('sidecar:deleteTask', tid),
    recommendTasks: () => ipcRenderer.invoke('sidecar:recommendTasks'),
    createGoal: (p) => ipcRenderer.invoke('sidecar:createGoal', p),
    goalsDashboard: () => ipcRenderer.invoke('sidecar:goalsDashboard'),
    goalProgress: (p) => ipcRenderer.invoke('sidecar:goalProgress', p),
    deleteGoal: (gid) => ipcRenderer.invoke('sidecar:deleteGoal', gid),
    schedulerJobs: () => ipcRenderer.invoke('sidecar:schedulerJobs'),
    schedulerSeed: () => ipcRenderer.invoke('sidecar:schedulerSeed'),
    schedulerTick: () => ipcRenderer.invoke('sidecar:schedulerTick'),
    cosBriefingAuto: () => ipcRenderer.invoke('sidecar:cosBriefingAuto'),
    cosPlanAuto: () => ipcRenderer.invoke('sidecar:cosPlanAuto'),
    cosDailyBriefing: (ctx) => ipcRenderer.invoke('sidecar:cosDailyBriefing', ctx),
    cosEveningReview: (ctx) => ipcRenderer.invoke('sidecar:cosEveningReview', ctx),
    emailBriefing: (emails) => ipcRenderer.invoke('sidecar:emailBriefing', emails),
    calendarPlan: (p) => ipcRenderer.invoke('sidecar:calendarPlan', p),
    acctSeed: (t) => ipcRenderer.invoke('sidecar:acctSeed', t),
    acctChart: () => ipcRenderer.invoke('sidecar:acctChart'),
    acctJournal: (p) => ipcRenderer.invoke('sidecar:acctJournal', p),
    acctEntries: (q) => ipcRenderer.invoke('sidecar:acctEntries', q),
    acctTrialBalance: (asOf) => ipcRenderer.invoke('sidecar:acctTrialBalance', asOf),
    acctBalanceSheet: (asOf) => ipcRenderer.invoke('sidecar:acctBalanceSheet', asOf),
    acctIncome: (start, end) => ipcRenderer.invoke('sidecar:acctIncome', { start, end }),
    acctCashFlow: (start, end) => ipcRenderer.invoke('sidecar:acctCashFlow', { start, end }),
    acctApAging: () => ipcRenderer.invoke('sidecar:acctApAging'),
    acctArAging: () => ipcRenderer.invoke('sidecar:acctArAging'),
    acctAddVendor: (p) => ipcRenderer.invoke('sidecar:acctAddVendor', p),
    acctAddBill: (p) => ipcRenderer.invoke('sidecar:acctAddBill', p),
    acctAddCustomer: (p) => ipcRenderer.invoke('sidecar:acctAddCustomer', p),
    acctAddInvoice: (p) => ipcRenderer.invoke('sidecar:acctAddInvoice', p),
    acctAssets: () => ipcRenderer.invoke('sidecar:acctAssets'),
    acctAddAsset: (p) => ipcRenderer.invoke('sidecar:acctAddAsset', p),
    acctAssetSchedule: (id) => ipcRenderer.invoke('sidecar:acctAssetSchedule', id),
    acctClients: () => ipcRenderer.invoke('sidecar:acctClients'),
    acctImportJournal: (csv) => ipcRenderer.invoke('sidecar:acctImportJournal', csv),
    acctAudit: () => ipcRenderer.invoke('sidecar:acctAudit'),
    acctDashboard: (asOf) => ipcRenderer.invoke('sidecar:acctDashboard', asOf),
    ocrStatus: () => ipcRenderer.invoke('sidecar:ocrStatus'),
    docProcess: (p) => ipcRenderer.invoke('sidecar:docProcess', p),
    docSearch: (q) => ipcRenderer.invoke('sidecar:docSearch', q),
    taxTopics: () => ipcRenderer.invoke('sidecar:taxTopics'),
    taxResearch: (query) => ipcRenderer.invoke('sidecar:taxResearch', query),
    taxMemo: (p) => ipcRenderer.invoke('sidecar:taxMemo', p),
    orgClient: (p) => ipcRenderer.invoke('sidecar:orgClient', p),
    orgDashboard: () => ipcRenderer.invoke('sidecar:orgDashboard'),
    wpTrialBalance: (asOf) => ipcRenderer.invoke('sidecar:wpTrialBalance', asOf),
    wpLead: (type, asOf) => ipcRenderer.invoke('sidecar:wpLead', { type, asOf }),
    advisoryAnalysis: (asOf) => ipcRenderer.invoke('sidecar:advisoryAnalysis', asOf),
    advisoryDD: (year) => ipcRenderer.invoke('sidecar:advisoryDD', year),
    globalSearch: (q) => ipcRenderer.invoke('sidecar:globalSearch', q),
    execQueue: () => ipcRenderer.invoke('sidecar:execQueue'),
    execActions: (status) => ipcRenderer.invoke('sidecar:execActions', status),
    execApprove: (p) => ipcRenderer.invoke('sidecar:execApprove', p),
    execReject: (p) => ipcRenderer.invoke('sidecar:execReject', p),
    execExecute: (id) => ipcRenderer.invoke('sidecar:execExecute', id),
    execRollback: (id) => ipcRenderer.invoke('sidecar:execRollback', id),
    execAutomateDoc: (p) => ipcRenderer.invoke('sidecar:execAutomateDoc', p),
    closeStart: (period) => ipcRenderer.invoke('sidecar:closeStart', period),
    closeUpdate: (p) => ipcRenderer.invoke('sidecar:closeUpdate', p),
    closeDashboard: () => ipcRenderer.invoke('sidecar:closeDashboard'),
    outcomesMetrics: () => ipcRenderer.invoke('sidecar:outcomesMetrics'),
    opsFirm: () => ipcRenderer.invoke('sidecar:opsFirm'),
    opsPortfolio: () => ipcRenderer.invoke('sidecar:opsPortfolio'),
    workflowBuild: (p) => ipcRenderer.invoke('sidecar:workflowBuild', p),
  },
  imessage: {
    status: () => ipcRenderer.invoke('imessage:status'),
  },
  telegram: {
    status: () => ipcRenderer.invoke('telegram:status'),
  },
});
