'use strict';

// Russian language corpus for ARIA's built-in curriculum.
// All Cyrillic is correct; transliteration follows a readable Latin convention
// with acute accent (´) on the stressed vowel where practical.
// POS: noun|verb|adj|adv|num|phrase|pron|prep|conj|particle|interj

// ─────────────────────────────────────────────
//  VOCABULARY  (300+ entries, by theme)
// ─────────────────────────────────────────────
const VOCAB = [
  // ── Greetings & Politeness ────────────────────────────────────────────────
  { ru: 'Привет', translit: 'Privét', en: 'Hi / Hello (informal)', theme: 'greetings', pos: 'interj' },
  { ru: 'Здравствуйте', translit: 'Zdrástvuyte', en: 'Hello (formal)', theme: 'greetings', pos: 'interj' },
  { ru: 'Пока', translit: 'Poká', en: 'Bye (informal)', theme: 'greetings', pos: 'interj' },
  { ru: 'До свидания', translit: 'Do svidániya', en: 'Goodbye (formal)', theme: 'greetings', pos: 'phrase' },
  { ru: 'Спасибо', translit: 'Spasíbo', en: 'Thank you', theme: 'greetings', pos: 'interj' },
  { ru: 'Пожалуйста', translit: 'Pozháluysta', en: 'Please / You\'re welcome', theme: 'greetings', pos: 'interj' },
  { ru: 'Извините', translit: 'Izviníte', en: 'Excuse me / Sorry (formal)', theme: 'greetings', pos: 'interj' },
  { ru: 'Простите', translit: 'Prostíte', en: 'Forgive me / Pardon', theme: 'greetings', pos: 'interj' },
  { ru: 'Доброе утро', translit: 'Dóbroye útro', en: 'Good morning', theme: 'greetings', pos: 'phrase' },
  { ru: 'Добрый день', translit: 'Dóbryy den\'', en: 'Good afternoon', theme: 'greetings', pos: 'phrase' },
  { ru: 'Добрый вечер', translit: 'Dóbryy vécher', en: 'Good evening', theme: 'greetings', pos: 'phrase' },
  { ru: 'Спокойной ночи', translit: 'Spokóynoy nóchi', en: 'Good night', theme: 'greetings', pos: 'phrase' },
  { ru: 'Как дела?', translit: 'Kak delá?', en: 'How are you?', theme: 'greetings', pos: 'phrase' },
  { ru: 'Хорошо', translit: 'Khorosho', en: 'Good / Fine / Well', theme: 'greetings', pos: 'adv' },
  { ru: 'Нормально', translit: 'Normál\'no', en: 'OK / Normal / Alright', theme: 'greetings', pos: 'adv' },
  { ru: 'Плохо', translit: 'Plókho', en: 'Bad / Badly', theme: 'greetings', pos: 'adv' },
  { ru: 'Очень хорошо', translit: 'Óchen\' khorosho', en: 'Very good', theme: 'greetings', pos: 'phrase' },
  { ru: 'Рад познакомиться', translit: 'Rad poznakomit\'sya', en: 'Nice to meet you', theme: 'greetings', pos: 'phrase' },
  { ru: 'Меня зовут…', translit: 'Menyá zovút…', en: 'My name is…', theme: 'greetings', pos: 'phrase' },
  { ru: 'Да', translit: 'Da', en: 'Yes', theme: 'greetings', pos: 'particle' },
  { ru: 'Нет', translit: 'Net', en: 'No', theme: 'greetings', pos: 'particle' },

  // ── Numbers 0–20 + multiples + ordinals ───────────────────────────────────
  { ru: 'ноль', translit: 'nol\'', en: 'zero', theme: 'numbers', pos: 'num' },
  { ru: 'один', translit: 'odín', en: 'one', theme: 'numbers', pos: 'num' },
  { ru: 'два', translit: 'dva', en: 'two', theme: 'numbers', pos: 'num' },
  { ru: 'три', translit: 'tri', en: 'three', theme: 'numbers', pos: 'num' },
  { ru: 'четыре', translit: 'chetýre', en: 'four', theme: 'numbers', pos: 'num' },
  { ru: 'пять', translit: 'pyat\'', en: 'five', theme: 'numbers', pos: 'num' },
  { ru: 'шесть', translit: 'shest\'', en: 'six', theme: 'numbers', pos: 'num' },
  { ru: 'семь', translit: 'sem\'', en: 'seven', theme: 'numbers', pos: 'num' },
  { ru: 'восемь', translit: 'vósem\'', en: 'eight', theme: 'numbers', pos: 'num' },
  { ru: 'девять', translit: 'dévyat\'', en: 'nine', theme: 'numbers', pos: 'num' },
  { ru: 'десять', translit: 'désyat\'', en: 'ten', theme: 'numbers', pos: 'num' },
  { ru: 'одиннадцать', translit: 'odinnadtsat\'', en: 'eleven', theme: 'numbers', pos: 'num' },
  { ru: 'двенадцать', translit: 'dvenadtsat\'', en: 'twelve', theme: 'numbers', pos: 'num' },
  { ru: 'тринадцать', translit: 'trinadtsat\'', en: 'thirteen', theme: 'numbers', pos: 'num' },
  { ru: 'четырнадцать', translit: 'chetyrnadtsat\'', en: 'fourteen', theme: 'numbers', pos: 'num' },
  { ru: 'пятнадцать', translit: 'pyatnadtsat\'', en: 'fifteen', theme: 'numbers', pos: 'num' },
  { ru: 'шестнадцать', translit: 'shestnadtsat\'', en: 'sixteen', theme: 'numbers', pos: 'num' },
  { ru: 'семнадцать', translit: 'semnadtsat\'', en: 'seventeen', theme: 'numbers', pos: 'num' },
  { ru: 'восемнадцать', translit: 'vosemnadtsat\'', en: 'eighteen', theme: 'numbers', pos: 'num' },
  { ru: 'девятнадцать', translit: 'devyatnadtsat\'', en: 'nineteen', theme: 'numbers', pos: 'num' },
  { ru: 'двадцать', translit: 'dvadtsat\'', en: 'twenty', theme: 'numbers', pos: 'num' },
  { ru: 'тридцать', translit: 'tridtsat\'', en: 'thirty', theme: 'numbers', pos: 'num' },
  { ru: 'сорок', translit: 'sórok', en: 'forty', theme: 'numbers', pos: 'num' },
  { ru: 'пятьдесят', translit: 'pyat\'desyát', en: 'fifty', theme: 'numbers', pos: 'num' },
  { ru: 'шестьдесят', translit: 'shest\'desyát', en: 'sixty', theme: 'numbers', pos: 'num' },
  { ru: 'семьдесят', translit: 'sém\'desyat', en: 'seventy', theme: 'numbers', pos: 'num' },
  { ru: 'восемьдесят', translit: 'vósem\'desyat', en: 'eighty', theme: 'numbers', pos: 'num' },
  { ru: 'девяносто', translit: 'devyanósto', en: 'ninety', theme: 'numbers', pos: 'num' },
  { ru: 'сто', translit: 'sto', en: 'one hundred', theme: 'numbers', pos: 'num' },
  { ru: 'первый', translit: 'pérvyy', en: 'first (ordinal)', theme: 'numbers', pos: 'num' },
  { ru: 'второй', translit: 'vtoróy', en: 'second (ordinal)', theme: 'numbers', pos: 'num' },
  { ru: 'третий', translit: 'trétiy', en: 'third (ordinal)', theme: 'numbers', pos: 'num' },
  { ru: 'четвёртый', translit: 'chetvórtyy', en: 'fourth (ordinal)', theme: 'numbers', pos: 'num' },
  { ru: 'пятый', translit: 'pyátyy', en: 'fifth (ordinal)', theme: 'numbers', pos: 'num' },

  // ── Days / Months / Time ──────────────────────────────────────────────────
  { ru: 'понедельник', translit: 'ponedél\'nik', en: 'Monday', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'вторник', translit: 'vtórnik', en: 'Tuesday', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'среда', translit: 'sredá', en: 'Wednesday', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'четверг', translit: 'chetvérg', en: 'Thursday', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'пятница', translit: 'pyátnitsa', en: 'Friday', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'суббота', translit: 'subbóta', en: 'Saturday', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'воскресенье', translit: 'voskresénje', en: 'Sunday', theme: 'time', pos: 'noun', gender: 'n' },
  { ru: 'январь', translit: 'yanvár\'', en: 'January', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'февраль', translit: 'fevrál\'', en: 'February', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'март', translit: 'mart', en: 'March', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'апрель', translit: 'aprél\'', en: 'April', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'май', translit: 'may', en: 'May', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'июнь', translit: 'iyún\'', en: 'June', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'июль', translit: 'iyúl\'', en: 'July', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'август', translit: 'ávgust', en: 'August', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'сентябрь', translit: 'sentyábr\'', en: 'September', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'октябрь', translit: 'oktyábr\'', en: 'October', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'ноябрь', translit: 'noyábr\'', en: 'November', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'декабрь', translit: 'dekábr\'', en: 'December', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'год', translit: 'god', en: 'year', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'месяц', translit: 'mésyats', en: 'month', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'неделя', translit: 'nedélya', en: 'week', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'день', translit: 'den\'', en: 'day', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'час', translit: 'chas', en: 'hour', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'минута', translit: 'minúta', en: 'minute', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'утро', translit: 'útro', en: 'morning', theme: 'time', pos: 'noun', gender: 'n' },
  { ru: 'день', translit: 'den\'', en: 'afternoon / daytime', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'вечер', translit: 'vécher', en: 'evening', theme: 'time', pos: 'noun', gender: 'm' },
  { ru: 'ночь', translit: 'noch\'', en: 'night', theme: 'time', pos: 'noun', gender: 'f' },
  { ru: 'сегодня', translit: 'sevódnya', en: 'today', theme: 'time', pos: 'adv' },
  { ru: 'завтра', translit: 'závtra', en: 'tomorrow', theme: 'time', pos: 'adv' },
  { ru: 'вчера', translit: 'vchéra', en: 'yesterday', theme: 'time', pos: 'adv' },
  { ru: 'сейчас', translit: 'seychás', en: 'now', theme: 'time', pos: 'adv' },
  { ru: 'потом', translit: 'potóm', en: 'later / then', theme: 'time', pos: 'adv' },
  { ru: 'скоро', translit: 'skóro', en: 'soon', theme: 'time', pos: 'adv' },

  // ── Family ─────────────────────────────────────────────────────────────────
  { ru: 'мама', translit: 'máma', en: 'mum / mom', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'папа', translit: 'pápa', en: 'dad', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'мать', translit: 'mat\'', en: 'mother', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'отец', translit: 'otéts', en: 'father', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'сын', translit: 'syn', en: 'son', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'дочь', translit: 'doch\'', en: 'daughter', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'брат', translit: 'brat', en: 'brother', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'сестра', translit: 'sestrá', en: 'sister', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'муж', translit: 'muzh', en: 'husband', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'жена', translit: 'zhená', en: 'wife', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'дедушка', translit: 'dédushka', en: 'grandfather', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'бабушка', translit: 'bábushka', en: 'grandmother', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'ребёнок', translit: 'rebénok', en: 'child', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'дети', translit: 'déti', en: 'children (pl.)', theme: 'family', pos: 'noun', gender: 'pl' },
  { ru: 'семья', translit: 'sem\'yá', en: 'family', theme: 'family', pos: 'noun', gender: 'f' },
  { ru: 'дядя', translit: 'dyádya', en: 'uncle', theme: 'family', pos: 'noun', gender: 'm' },
  { ru: 'тётя', translit: 'tyótya', en: 'aunt', theme: 'family', pos: 'noun', gender: 'f' },

  // ── Pronouns & People ─────────────────────────────────────────────────────
  { ru: 'я', translit: 'ya', en: 'I', theme: 'pronouns', pos: 'pron' },
  { ru: 'ты', translit: 'ty', en: 'you (singular informal)', theme: 'pronouns', pos: 'pron' },
  { ru: 'он', translit: 'on', en: 'he / it (m.)', theme: 'pronouns', pos: 'pron' },
  { ru: 'она', translit: 'oná', en: 'she / it (f.)', theme: 'pronouns', pos: 'pron' },
  { ru: 'оно', translit: 'onó', en: 'it (n.)', theme: 'pronouns', pos: 'pron' },
  { ru: 'мы', translit: 'my', en: 'we', theme: 'pronouns', pos: 'pron' },
  { ru: 'вы', translit: 'vy', en: 'you (plural / formal)', theme: 'pronouns', pos: 'pron' },
  { ru: 'они', translit: 'oní', en: 'they', theme: 'pronouns', pos: 'pron' },
  { ru: 'человек', translit: 'chelovék', en: 'person / human', theme: 'pronouns', pos: 'noun', gender: 'm' },
  { ru: 'мужчина', translit: 'muzhchína', en: 'man', theme: 'pronouns', pos: 'noun', gender: 'm' },
  { ru: 'женщина', translit: 'zhénshchina', en: 'woman', theme: 'pronouns', pos: 'noun', gender: 'f' },
  { ru: 'мальчик', translit: 'mál\'chik', en: 'boy', theme: 'pronouns', pos: 'noun', gender: 'm' },
  { ru: 'девочка', translit: 'dévochka', en: 'girl', theme: 'pronouns', pos: 'noun', gender: 'f' },
  { ru: 'друг', translit: 'drug', en: 'friend (m.)', theme: 'pronouns', pos: 'noun', gender: 'm' },
  { ru: 'подруга', translit: 'podrúga', en: 'friend (f.)', theme: 'pronouns', pos: 'noun', gender: 'f' },

  // ── Food & Drink ──────────────────────────────────────────────────────────
  { ru: 'еда', translit: 'yedá', en: 'food', theme: 'food', pos: 'noun', gender: 'f' },
  { ru: 'вода', translit: 'vodá', en: 'water', theme: 'food', pos: 'noun', gender: 'f' },
  { ru: 'чай', translit: 'chay', en: 'tea', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'кофе', translit: 'kófe', en: 'coffee', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'молоко', translit: 'molokó', en: 'milk', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'сок', translit: 'sok', en: 'juice', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'хлеб', translit: 'khleb', en: 'bread', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'мясо', translit: 'myáso', en: 'meat', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'рыба', translit: 'ryba', en: 'fish', theme: 'food', pos: 'noun', gender: 'f' },
  { ru: 'суп', translit: 'sup', en: 'soup', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'салат', translit: 'salát', en: 'salad', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'рис', translit: 'ris', en: 'rice', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'яйцо', translit: 'yaytso', en: 'egg', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'сыр', translit: 'syr', en: 'cheese', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'масло', translit: 'máslo', en: 'butter / oil', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'сахар', translit: 'sákhar', en: 'sugar', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'соль', translit: 'sol\'', en: 'salt', theme: 'food', pos: 'noun', gender: 'f' },
  { ru: 'яблоко', translit: 'yábloko', en: 'apple', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'апельсин', translit: 'apel\'sín', en: 'orange', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'банан', translit: 'banán', en: 'banana', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'картошка', translit: 'kartóshka', en: 'potato (colloquial)', theme: 'food', pos: 'noun', gender: 'f' },
  { ru: 'торт', translit: 'tort', en: 'cake', theme: 'food', pos: 'noun', gender: 'm' },
  { ru: 'пиво', translit: 'pívo', en: 'beer', theme: 'food', pos: 'noun', gender: 'n' },
  { ru: 'вино', translit: 'vinó', en: 'wine', theme: 'food', pos: 'noun', gender: 'n' },

  // ── Colors ────────────────────────────────────────────────────────────────
  { ru: 'красный', translit: 'krásnyy', en: 'red', theme: 'colors', pos: 'adj' },
  { ru: 'синий', translit: 'síney', en: 'blue (dark / rich)', theme: 'colors', pos: 'adj' },
  { ru: 'голубой', translit: 'golubóy', en: 'light blue', theme: 'colors', pos: 'adj' },
  { ru: 'зелёный', translit: 'zelyónyy', en: 'green', theme: 'colors', pos: 'adj' },
  { ru: 'жёлтый', translit: 'zhóltyy', en: 'yellow', theme: 'colors', pos: 'adj' },
  { ru: 'белый', translit: 'bélyy', en: 'white', theme: 'colors', pos: 'adj' },
  { ru: 'чёрный', translit: 'chórnyy', en: 'black', theme: 'colors', pos: 'adj' },
  { ru: 'серый', translit: 'seryy', en: 'grey', theme: 'colors', pos: 'adj' },
  { ru: 'коричневый', translit: 'koríchnevyy', en: 'brown', theme: 'colors', pos: 'adj' },
  { ru: 'оранжевый', translit: 'oránzhevyy', en: 'orange', theme: 'colors', pos: 'adj' },
  { ru: 'фиолетовый', translit: 'fioletovyy', en: 'purple / violet', theme: 'colors', pos: 'adj' },
  { ru: 'розовый', translit: 'rózovyy', en: 'pink', theme: 'colors', pos: 'adj' },

  // ── Home & Objects ────────────────────────────────────────────────────────
  { ru: 'дом', translit: 'dom', en: 'house / home', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'квартира', translit: 'kvartíra', en: 'apartment / flat', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'комната', translit: 'kómnata', en: 'room', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'кухня', translit: 'kúkhnya', en: 'kitchen', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'ванная', translit: 'vánnaya', en: 'bathroom', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'окно', translit: 'oknó', en: 'window', theme: 'home', pos: 'noun', gender: 'n' },
  { ru: 'дверь', translit: 'dver\'', en: 'door', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'стол', translit: 'stol', en: 'table / desk', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'стул', translit: 'stul', en: 'chair', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'кровать', translit: 'krovát\'', en: 'bed', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'диван', translit: 'diván', en: 'sofa / couch', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'книга', translit: 'kníga', en: 'book', theme: 'home', pos: 'noun', gender: 'f' },
  { ru: 'телефон', translit: 'telefón', en: 'phone', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'компьютер', translit: 'komp\'yúter', en: 'computer', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'телевизор', translit: 'televizór', en: 'television', theme: 'home', pos: 'noun', gender: 'm' },
  { ru: 'ключ', translit: 'klyuch', en: 'key', theme: 'home', pos: 'noun', gender: 'm' },

  // ── City & Nature ─────────────────────────────────────────────────────────
  { ru: 'город', translit: 'górod', en: 'city / town', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'улица', translit: 'úlitsa', en: 'street', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'площадь', translit: 'plóshchad\'', en: 'square / plaza', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'парк', translit: 'park', en: 'park', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'магазин', translit: 'magazín', en: 'store / shop', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'рынок', translit: 'rynok', en: 'market', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'банк', translit: 'bank', en: 'bank', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'больница', translit: 'bol\'níca', en: 'hospital', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'школа', translit: 'shkóla', en: 'school', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'университет', translit: 'universitét', en: 'university', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'ресторан', translit: 'restarán', en: 'restaurant', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'кафе', translit: 'kafé', en: 'cafe', theme: 'city', pos: 'noun', gender: 'n' },
  { ru: 'аптека', translit: 'aptéka', en: 'pharmacy', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'река', translit: 'reká', en: 'river', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'море', translit: 'móre', en: 'sea', theme: 'city', pos: 'noun', gender: 'n' },
  { ru: 'лес', translit: 'les', en: 'forest', theme: 'city', pos: 'noun', gender: 'm' },
  { ru: 'гора', translit: 'gorá', en: 'mountain', theme: 'city', pos: 'noun', gender: 'f' },
  { ru: 'поле', translit: 'póle', en: 'field', theme: 'city', pos: 'noun', gender: 'n' },
  { ru: 'небо', translit: 'nébo', en: 'sky', theme: 'city', pos: 'noun', gender: 'n' },
  { ru: 'земля', translit: 'zemlyá', en: 'earth / ground / land', theme: 'city', pos: 'noun', gender: 'f' },

  // ── Common Verbs (50+) ────────────────────────────────────────────────────
  { ru: 'быть', translit: 'byt\'', en: 'to be', theme: 'verbs', pos: 'verb' },
  { ru: 'иметь', translit: 'imét\'', en: 'to have', theme: 'verbs', pos: 'verb' },
  { ru: 'хотеть', translit: 'khotét\'', en: 'to want', theme: 'verbs', pos: 'verb' },
  { ru: 'мочь', translit: 'moch\'', en: 'to be able to / can', theme: 'verbs', pos: 'verb' },
  { ru: 'знать', translit: 'znat\'', en: 'to know', theme: 'verbs', pos: 'verb' },
  { ru: 'понимать', translit: 'ponimat\'', en: 'to understand', theme: 'verbs', pos: 'verb' },
  { ru: 'говорить', translit: 'govorít\'', en: 'to speak / say', theme: 'verbs', pos: 'verb' },
  { ru: 'сказать', translit: 'skazát\'', en: 'to say (pfv.)', theme: 'verbs', pos: 'verb' },
  { ru: 'читать', translit: 'chitát\'', en: 'to read', theme: 'verbs', pos: 'verb' },
  { ru: 'писать', translit: 'pisát\'', en: 'to write', theme: 'verbs', pos: 'verb' },
  { ru: 'видеть', translit: 'vídet\'', en: 'to see', theme: 'verbs', pos: 'verb' },
  { ru: 'слышать', translit: 'slyshat\'', en: 'to hear', theme: 'verbs', pos: 'verb' },
  { ru: 'слушать', translit: 'slúshat\'', en: 'to listen', theme: 'verbs', pos: 'verb' },
  { ru: 'смотреть', translit: 'smotrét\'', en: 'to watch / look', theme: 'verbs', pos: 'verb' },
  { ru: 'думать', translit: 'dúmat\'', en: 'to think', theme: 'verbs', pos: 'verb' },
  { ru: 'работать', translit: 'rabótat\'', en: 'to work', theme: 'verbs', pos: 'verb' },
  { ru: 'учиться', translit: 'uchít\'sya', en: 'to study / learn (intrans.)', theme: 'verbs', pos: 'verb' },
  { ru: 'учить', translit: 'uchít\'', en: 'to teach / memorize', theme: 'verbs', pos: 'verb' },
  { ru: 'жить', translit: 'zhit\'', en: 'to live', theme: 'verbs', pos: 'verb' },
  { ru: 'идти', translit: 'idtí', en: 'to go (on foot, one direction)', theme: 'verbs', pos: 'verb' },
  { ru: 'ходить', translit: 'khodít\'', en: 'to go (on foot, habitual)', theme: 'verbs', pos: 'verb' },
  { ru: 'ехать', translit: 'yékhat\'', en: 'to go (by vehicle, one direction)', theme: 'verbs', pos: 'verb' },
  { ru: 'ездить', translit: 'yézdit\'', en: 'to go (by vehicle, habitual)', theme: 'verbs', pos: 'verb' },
  { ru: 'приходить', translit: 'prikhodít\'', en: 'to arrive / come', theme: 'verbs', pos: 'verb' },
  { ru: 'приехать', translit: 'priyékhat\'', en: 'to arrive (by vehicle, pfv.)', theme: 'verbs', pos: 'verb' },
  { ru: 'уходить', translit: 'ukhodít\'', en: 'to leave (on foot)', theme: 'verbs', pos: 'verb' },
  { ru: 'есть', translit: 'yest\'', en: 'to eat', theme: 'verbs', pos: 'verb' },
  { ru: 'пить', translit: 'pit\'', en: 'to drink', theme: 'verbs', pos: 'verb' },
  { ru: 'спать', translit: 'spat\'', en: 'to sleep', theme: 'verbs', pos: 'verb' },
  { ru: 'вставать', translit: 'vstavát\'', en: 'to get up', theme: 'verbs', pos: 'verb' },
  { ru: 'открывать', translit: 'otkryvát\'', en: 'to open', theme: 'verbs', pos: 'verb' },
  { ru: 'закрывать', translit: 'zakryvát\'', en: 'to close', theme: 'verbs', pos: 'verb' },
  { ru: 'покупать', translit: 'pokupát\'', en: 'to buy', theme: 'verbs', pos: 'verb' },
  { ru: 'продавать', translit: 'prodavát\'', en: 'to sell', theme: 'verbs', pos: 'verb' },
  { ru: 'давать', translit: 'davát\'', en: 'to give', theme: 'verbs', pos: 'verb' },
  { ru: 'брать', translit: 'brat\'', en: 'to take', theme: 'verbs', pos: 'verb' },
  { ru: 'делать', translit: 'délat\'', en: 'to do / make', theme: 'verbs', pos: 'verb' },
  { ru: 'помогать', translit: 'pomogát\'', en: 'to help', theme: 'verbs', pos: 'verb' },
  { ru: 'любить', translit: 'lyubít\'', en: 'to love / like', theme: 'verbs', pos: 'verb' },
  { ru: 'нравиться', translit: 'nrávit\'sya', en: 'to be pleasing to / like (impers.)', theme: 'verbs', pos: 'verb' },
  { ru: 'начинать', translit: 'nachinat\'', en: 'to begin / start', theme: 'verbs', pos: 'verb' },
  { ru: 'заканчивать', translit: 'zakanchivar\'', en: 'to finish / end', theme: 'verbs', pos: 'verb' },
  { ru: 'отвечать', translit: 'otvechat\'', en: 'to answer', theme: 'verbs', pos: 'verb' },
  { ru: 'спрашивать', translit: 'spráshivat\'', en: 'to ask', theme: 'verbs', pos: 'verb' },
  { ru: 'ждать', translit: 'zhdat\'', en: 'to wait', theme: 'verbs', pos: 'verb' },
  { ru: 'искать', translit: 'iskát\'', en: 'to look for / search', theme: 'verbs', pos: 'verb' },
  { ru: 'найти', translit: 'naytí', en: 'to find (pfv.)', theme: 'verbs', pos: 'verb' },
  { ru: 'звонить', translit: 'zvonít\'', en: 'to call (phone)', theme: 'verbs', pos: 'verb' },
  { ru: 'играть', translit: 'igrát\'', en: 'to play', theme: 'verbs', pos: 'verb' },
  { ru: 'стоить', translit: 'stóit\'', en: 'to cost', theme: 'verbs', pos: 'verb' },
  { ru: 'платить', translit: 'platít\'', en: 'to pay', theme: 'verbs', pos: 'verb' },
  { ru: 'знакомиться', translit: 'znakomít\'sya', en: 'to get acquainted', theme: 'verbs', pos: 'verb' },
  { ru: 'вернуться', translit: 'vernút\'sya', en: 'to return (pfv.)', theme: 'verbs', pos: 'verb' },
  { ru: 'показывать', translit: 'pokazyvat\'', en: 'to show', theme: 'verbs', pos: 'verb' },

  // ── Common Adjectives ─────────────────────────────────────────────────────
  { ru: 'большой', translit: 'bol\'shóy', en: 'big / large', theme: 'adjectives', pos: 'adj' },
  { ru: 'маленький', translit: 'málen\'kiy', en: 'small / little', theme: 'adjectives', pos: 'adj' },
  { ru: 'новый', translit: 'nóvyy', en: 'new', theme: 'adjectives', pos: 'adj' },
  { ru: 'старый', translit: 'stáryy', en: 'old', theme: 'adjectives', pos: 'adj' },
  { ru: 'молодой', translit: 'molodóy', en: 'young', theme: 'adjectives', pos: 'adj' },
  { ru: 'красивый', translit: 'krasívyy', en: 'beautiful / pretty', theme: 'adjectives', pos: 'adj' },
  { ru: 'интересный', translit: 'interésnyy', en: 'interesting', theme: 'adjectives', pos: 'adj' },
  { ru: 'скучный', translit: 'skúchnyy', en: 'boring', theme: 'adjectives', pos: 'adj' },
  { ru: 'трудный', translit: 'trúdnyy', en: 'difficult / hard', theme: 'adjectives', pos: 'adj' },
  { ru: 'лёгкий', translit: 'lyókhkiy', en: 'easy / light', theme: 'adjectives', pos: 'adj' },
  { ru: 'важный', translit: 'vázhnye', en: 'important', theme: 'adjectives', pos: 'adj' },
  { ru: 'дорогой', translit: 'dorogóy', en: 'expensive / dear', theme: 'adjectives', pos: 'adj' },
  { ru: 'дешёвый', translit: 'deshóvyy', en: 'cheap / inexpensive', theme: 'adjectives', pos: 'adj' },
  { ru: 'быстрый', translit: 'bystryy', en: 'fast / quick', theme: 'adjectives', pos: 'adj' },
  { ru: 'медленный', translit: 'médlennyy', en: 'slow', theme: 'adjectives', pos: 'adj' },
  { ru: 'тихий', translit: 'tíkhiy', en: 'quiet', theme: 'adjectives', pos: 'adj' },
  { ru: 'громкий', translit: 'gróm\'kiy', en: 'loud', theme: 'adjectives', pos: 'adj' },
  { ru: 'горячий', translit: 'goryáchiy', en: 'hot', theme: 'adjectives', pos: 'adj' },
  { ru: 'холодный', translit: 'kholódnyy', en: 'cold', theme: 'adjectives', pos: 'adj' },
  { ru: 'тёплый', translit: 'tyópyy', en: 'warm', theme: 'adjectives', pos: 'adj' },
  { ru: 'прохладный', translit: 'prokhlódnyy', en: 'cool', theme: 'adjectives', pos: 'adj' },
  { ru: 'вкусный', translit: 'vkúsnyy', en: 'tasty / delicious', theme: 'adjectives', pos: 'adj' },
  { ru: 'правый', translit: 'právyy', en: 'right (side) / correct', theme: 'adjectives', pos: 'adj' },
  { ru: 'левый', translit: 'lévyy', en: 'left (side)', theme: 'adjectives', pos: 'adj' },

  // ── Travel & Directions ───────────────────────────────────────────────────
  { ru: 'дорога', translit: 'doróga', en: 'road / way', theme: 'travel', pos: 'noun', gender: 'f' },
  { ru: 'путь', translit: 'put\'', en: 'path / journey / way', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'карта', translit: 'kárta', en: 'map / card', theme: 'travel', pos: 'noun', gender: 'f' },
  { ru: 'аэропорт', translit: 'aeropórt', en: 'airport', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'вокзал', translit: 'vokzál', en: 'train station', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'автобус', translit: 'avtóbus', en: 'bus', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'метро', translit: 'metró', en: 'metro / subway', theme: 'travel', pos: 'noun', gender: 'n' },
  { ru: 'поезд', translit: 'póyezd', en: 'train', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'самолёт', translit: 'samolyót', en: 'airplane', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'такси', translit: 'taksí', en: 'taxi', theme: 'travel', pos: 'noun', gender: 'n' },
  { ru: 'машина', translit: 'mashína', en: 'car / machine', theme: 'travel', pos: 'noun', gender: 'f' },
  { ru: 'билет', translit: 'bilét', en: 'ticket', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'паспорт', translit: 'pásport', en: 'passport', theme: 'travel', pos: 'noun', gender: 'm' },
  { ru: 'гостиница', translit: 'gostinitsa', en: 'hotel', theme: 'travel', pos: 'noun', gender: 'f' },
  { ru: 'налево', translit: 'nalévo', en: 'to the left', theme: 'travel', pos: 'adv' },
  { ru: 'направо', translit: 'naprávo', en: 'to the right', theme: 'travel', pos: 'adv' },
  { ru: 'прямо', translit: 'pryámo', en: 'straight ahead', theme: 'travel', pos: 'adv' },
  { ru: 'далеко', translit: 'daleká', en: 'far', theme: 'travel', pos: 'adv' },
  { ru: 'близко', translit: 'blízko', en: 'near / close', theme: 'travel', pos: 'adv' },
  { ru: 'здесь', translit: 'zdes\'', en: 'here', theme: 'travel', pos: 'adv' },
  { ru: 'там', translit: 'tam', en: 'there', theme: 'travel', pos: 'adv' },
  { ru: 'куда', translit: 'kudá', en: 'where to (direction)', theme: 'travel', pos: 'adv' },
  { ru: 'откуда', translit: 'otkúda', en: 'from where', theme: 'travel', pos: 'adv' },

  // ── Weather ───────────────────────────────────────────────────────────────
  { ru: 'погода', translit: 'pogóda', en: 'weather', theme: 'weather', pos: 'noun', gender: 'f' },
  { ru: 'солнце', translit: 'sóntse', en: 'sun', theme: 'weather', pos: 'noun', gender: 'n' },
  { ru: 'дождь', translit: 'dozhd\'', en: 'rain', theme: 'weather', pos: 'noun', gender: 'm' },
  { ru: 'снег', translit: 'sneg', en: 'snow', theme: 'weather', pos: 'noun', gender: 'm' },
  { ru: 'ветер', translit: 'véter', en: 'wind', theme: 'weather', pos: 'noun', gender: 'm' },
  { ru: 'туман', translit: 'tumán', en: 'fog', theme: 'weather', pos: 'noun', gender: 'm' },
  { ru: 'облако', translit: 'óblako', en: 'cloud', theme: 'weather', pos: 'noun', gender: 'n' },
  { ru: 'гроза', translit: 'grozá', en: 'thunderstorm', theme: 'weather', pos: 'noun', gender: 'f' },
  { ru: 'тепло', translit: 'tepló', en: 'it is warm (pred.)', theme: 'weather', pos: 'adv' },
  { ru: 'холодно', translit: 'khólodno', en: 'it is cold (pred.)', theme: 'weather', pos: 'adv' },
  { ru: 'жарко', translit: 'zhárko', en: 'it is hot (pred.)', theme: 'weather', pos: 'adv' },
  { ru: 'идёт дождь', translit: 'idyót dozhd\'', en: 'it is raining', theme: 'weather', pos: 'phrase' },
  { ru: 'идёт снег', translit: 'idyót sneg', en: 'it is snowing', theme: 'weather', pos: 'phrase' },

  // ── Body & Health ─────────────────────────────────────────────────────────
  { ru: 'тело', translit: 'télo', en: 'body', theme: 'health', pos: 'noun', gender: 'n' },
  { ru: 'голова', translit: 'golová', en: 'head', theme: 'health', pos: 'noun', gender: 'f' },
  { ru: 'глаз', translit: 'glaz', en: 'eye', theme: 'health', pos: 'noun', gender: 'm' },
  { ru: 'ухо', translit: 'úkho', en: 'ear', theme: 'health', pos: 'noun', gender: 'n' },
  { ru: 'нос', translit: 'nos', en: 'nose', theme: 'health', pos: 'noun', gender: 'm' },
  { ru: 'рот', translit: 'rot', en: 'mouth', theme: 'health', pos: 'noun', gender: 'm' },
  { ru: 'рука', translit: 'ruká', en: 'hand / arm', theme: 'health', pos: 'noun', gender: 'f' },
  { ru: 'нога', translit: 'nogá', en: 'leg / foot', theme: 'health', pos: 'noun', gender: 'f' },
  { ru: 'спина', translit: 'spiná', en: 'back', theme: 'health', pos: 'noun', gender: 'f' },
  { ru: 'сердце', translit: 'sérdtse', en: 'heart', theme: 'health', pos: 'noun', gender: 'n' },
  { ru: 'боль', translit: 'bol\'', en: 'pain', theme: 'health', pos: 'noun', gender: 'f' },
  { ru: 'болеть', translit: 'bolét\'', en: 'to be sick / to hurt', theme: 'health', pos: 'verb' },
  { ru: 'врач', translit: 'vrach', en: 'doctor', theme: 'health', pos: 'noun', gender: 'm' },
  { ru: 'лекарство', translit: 'lekárstvo', en: 'medicine / medication', theme: 'health', pos: 'noun', gender: 'n' },
  { ru: 'у меня болит…', translit: 'u menyá bolít…', en: 'my … hurts', theme: 'health', pos: 'phrase' },

  // ── Work & Study ──────────────────────────────────────────────────────────
  { ru: 'работа', translit: 'rabóta', en: 'work / job', theme: 'work', pos: 'noun', gender: 'f' },
  { ru: 'офис', translit: 'ófis', en: 'office', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'коллега', translit: 'kolléga', en: 'colleague', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'начальник', translit: 'nachál\'nik', en: 'boss / manager', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'встреча', translit: 'vstrecha', en: 'meeting', theme: 'work', pos: 'noun', gender: 'f' },
  { ru: 'проект', translit: 'proyékt', en: 'project', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'задание', translit: 'zadániye', en: 'task / assignment', theme: 'work', pos: 'noun', gender: 'n' },
  { ru: 'язык', translit: 'yazyk', en: 'language / tongue', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'слово', translit: 'slóvo', en: 'word', theme: 'work', pos: 'noun', gender: 'n' },
  { ru: 'предложение', translit: 'predlozhéniye', en: 'sentence', theme: 'work', pos: 'noun', gender: 'n' },
  { ru: 'урок', translit: 'urók', en: 'lesson', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'упражнение', translit: 'uprazhnéniye', en: 'exercise', theme: 'work', pos: 'noun', gender: 'n' },
  { ru: 'экзамен', translit: 'ekzámen', en: 'exam', theme: 'work', pos: 'noun', gender: 'm' },
  { ru: 'оценка', translit: 'otsénka', en: 'grade / evaluation', theme: 'work', pos: 'noun', gender: 'f' },

  // ── Shopping & Money ──────────────────────────────────────────────────────
  { ru: 'деньги', translit: 'dén\'gi', en: 'money', theme: 'shopping', pos: 'noun', gender: 'pl' },
  { ru: 'рубль', translit: 'rúbl\'', en: 'ruble', theme: 'shopping', pos: 'noun', gender: 'm' },
  { ru: 'цена', translit: 'tsená', en: 'price', theme: 'shopping', pos: 'noun', gender: 'f' },
  { ru: 'скидка', translit: 'skídka', en: 'discount', theme: 'shopping', pos: 'noun', gender: 'f' },
  { ru: 'касса', translit: 'kássa', en: 'cash register / checkout', theme: 'shopping', pos: 'noun', gender: 'f' },
  { ru: 'чек', translit: 'chek', en: 'receipt', theme: 'shopping', pos: 'noun', gender: 'm' },
  { ru: 'сдача', translit: 'sdácha', en: 'change (money)', theme: 'shopping', pos: 'noun', gender: 'f' },
  { ru: 'Сколько стоит?', translit: 'Skól\'ko stóit?', en: 'How much does it cost?', theme: 'shopping', pos: 'phrase' },
  { ru: 'дорого', translit: 'dórogo', en: 'expensive (pred.)', theme: 'shopping', pos: 'adv' },
  { ru: 'дёшево', translit: 'dyóshevo', en: 'cheap (pred.)', theme: 'shopping', pos: 'adv' },

  // ── Question Words ────────────────────────────────────────────────────────
  { ru: 'что', translit: 'chto', en: 'what', theme: 'questions', pos: 'pron' },
  { ru: 'кто', translit: 'kto', en: 'who', theme: 'questions', pos: 'pron' },
  { ru: 'где', translit: 'gde', en: 'where (location)', theme: 'questions', pos: 'adv' },
  { ru: 'когда', translit: 'kogdá', en: 'when', theme: 'questions', pos: 'adv' },
  { ru: 'почему', translit: 'pochemu', en: 'why', theme: 'questions', pos: 'adv' },
  { ru: 'зачем', translit: 'zachém', en: 'what for / why (purpose)', theme: 'questions', pos: 'adv' },
  { ru: 'как', translit: 'kak', en: 'how', theme: 'questions', pos: 'adv' },
  { ru: 'сколько', translit: 'skól\'ko', en: 'how many / how much', theme: 'questions', pos: 'adv' },
  { ru: 'какой', translit: 'kakóy', en: 'which / what kind of', theme: 'questions', pos: 'pron' },
  { ru: 'чей', translit: 'chey', en: 'whose', theme: 'questions', pos: 'pron' },

  // ── Prepositions ──────────────────────────────────────────────────────────
  { ru: 'в', translit: 'v', en: 'in / into (+ prep/acc)', theme: 'prepositions', pos: 'prep' },
  { ru: 'на', translit: 'na', en: 'on / onto / at (+ prep/acc)', theme: 'prepositions', pos: 'prep' },
  { ru: 'с', translit: 's', en: 'with / from (+ instr/gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'из', translit: 'iz', en: 'from / out of (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'от', translit: 'ot', en: 'from / away from (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'до', translit: 'do', en: 'until / up to / before (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'после', translit: 'pósle', en: 'after (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'без', translit: 'bez', en: 'without (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'о / об', translit: 'o / ob', en: 'about / concerning (+ prep)', theme: 'prepositions', pos: 'prep' },
  { ru: 'для', translit: 'dlya', en: 'for (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'за', translit: 'za', en: 'behind / for / in exchange (+ instr/acc)', theme: 'prepositions', pos: 'prep' },
  { ru: 'под', translit: 'pod', en: 'under (+ instr/acc)', theme: 'prepositions', pos: 'prep' },
  { ru: 'над', translit: 'nad', en: 'above / over (+ instr)', theme: 'prepositions', pos: 'prep' },
  { ru: 'перед', translit: 'péred', en: 'in front of / before (+ instr)', theme: 'prepositions', pos: 'prep' },
  { ru: 'между', translit: 'mézhdu', en: 'between (+ instr)', theme: 'prepositions', pos: 'prep' },
  { ru: 'через', translit: 'chérez', en: 'through / across / in (time) (+ acc)', theme: 'prepositions', pos: 'prep' },
  { ru: 'по', translit: 'po', en: 'along / by / according to (+ dat)', theme: 'prepositions', pos: 'prep' },
  { ru: 'при', translit: 'pri', en: 'at / in the presence of (+ prep)', theme: 'prepositions', pos: 'prep' },
  { ru: 'у', translit: 'u', en: 'at / near / by / belonging to (+ gen)', theme: 'prepositions', pos: 'prep' },
  { ru: 'к', translit: 'k', en: 'towards / to (+ dat)', theme: 'prepositions', pos: 'prep' },

  // ── Conjunctions ──────────────────────────────────────────────────────────
  { ru: 'и', translit: 'i', en: 'and', theme: 'conjunctions', pos: 'conj' },
  { ru: 'а', translit: 'a', en: 'but (contrast) / and (while)', theme: 'conjunctions', pos: 'conj' },
  { ru: 'но', translit: 'no', en: 'but (contradiction)', theme: 'conjunctions', pos: 'conj' },
  { ru: 'или', translit: 'íli', en: 'or', theme: 'conjunctions', pos: 'conj' },
  { ru: 'что', translit: 'chto', en: 'that (conjunction)', theme: 'conjunctions', pos: 'conj' },
  { ru: 'если', translit: 'ésli', en: 'if', theme: 'conjunctions', pos: 'conj' },
  { ru: 'когда', translit: 'kogdá', en: 'when (conjunction)', theme: 'conjunctions', pos: 'conj' },
  { ru: 'потому что', translit: 'potomu chto', en: 'because', theme: 'conjunctions', pos: 'conj' },
  { ru: 'хотя', translit: 'khotya', en: 'although / though', theme: 'conjunctions', pos: 'conj' },
  { ru: 'чтобы', translit: 'chtoby', en: 'in order to / so that', theme: 'conjunctions', pos: 'conj' },
  { ru: 'пока', translit: 'poká', en: 'while / as long as', theme: 'conjunctions', pos: 'conj' },
  { ru: 'тоже', translit: 'tózhe', en: 'also / too', theme: 'conjunctions', pos: 'conj' },
  { ru: 'ни…ни', translit: 'ni…ni', en: 'neither…nor', theme: 'conjunctions', pos: 'conj' },

  // ── Survival Phrases ──────────────────────────────────────────────────────
  { ru: 'Я не понимаю', translit: 'Ya ne ponimáyu', en: 'I don\'t understand', theme: 'phrases', pos: 'phrase' },
  { ru: 'Повторите, пожалуйста', translit: 'Povtoríte, pozháluysta', en: 'Please repeat that', theme: 'phrases', pos: 'phrase' },
  { ru: 'Говорите медленнее', translit: 'Govoríte médlenneye', en: 'Speak more slowly', theme: 'phrases', pos: 'phrase' },
  { ru: 'Я не говорю по-русски', translit: 'Ya ne govoryu po-rússki', en: 'I don\'t speak Russian', theme: 'phrases', pos: 'phrase' },
  { ru: 'Вы говорите по-английски?', translit: 'Vy govoríte po-anglíyski?', en: 'Do you speak English?', theme: 'phrases', pos: 'phrase' },
  { ru: 'Где находится…?', translit: 'Gde nakhoditsya…?', en: 'Where is … located?', theme: 'phrases', pos: 'phrase' },
  { ru: 'Как пройти к…?', translit: 'Kak proytí k…?', en: 'How do I get to …?', theme: 'phrases', pos: 'phrase' },
  { ru: 'Мне нужна помощь', translit: 'Mne nuzhnúa pomoshch\'', en: 'I need help', theme: 'phrases', pos: 'phrase' },
  { ru: 'Вызовите скорую!', translit: 'Výzovite skóruyu!', en: 'Call an ambulance!', theme: 'phrases', pos: 'phrase' },
  { ru: 'Позвоните в полицию!', translit: 'Pozvonite v polítsiyu!', en: 'Call the police!', theme: 'phrases', pos: 'phrase' },
  { ru: 'Я хочу…', translit: 'Ya khochú…', en: 'I want…', theme: 'phrases', pos: 'phrase' },
  { ru: 'У меня нет…', translit: 'U menyá net…', en: 'I don\'t have…', theme: 'phrases', pos: 'phrase' },
  { ru: 'Можно…?', translit: 'Mózhno…?', en: 'May I…? / Is it possible to…?', theme: 'phrases', pos: 'phrase' },
  { ru: 'Нельзя', translit: 'Nel\'zyá', en: 'It is not allowed / one must not', theme: 'phrases', pos: 'phrase' },
  { ru: 'Конечно', translit: 'konéchno', en: 'Of course / certainly', theme: 'phrases', pos: 'phrase' },
  { ru: 'Может быть', translit: 'Mózhet byt\'', en: 'Maybe / perhaps', theme: 'phrases', pos: 'phrase' },
  { ru: 'Не знаю', translit: 'Ne znáyu', en: 'I don\'t know', theme: 'phrases', pos: 'phrase' },
  { ru: 'Всё понятно', translit: 'Vsyo ponyátno', en: 'Everything is clear / I understand', theme: 'phrases', pos: 'phrase' },
  { ru: 'Отлично', translit: 'Otlichno', en: 'Excellent / Great', theme: 'phrases', pos: 'phrase' },
  { ru: 'Поздравляю!', translit: 'Pozdravlyáyu!', en: 'Congratulations!', theme: 'phrases', pos: 'phrase' },
  { ru: 'Счастливого пути!', translit: 'Schastlívogo putí!', en: 'Have a good journey! / Bon voyage!', theme: 'phrases', pos: 'phrase' },
  { ru: 'Приятного аппетита!', translit: 'Priyátnogo appetíta!', en: 'Enjoy your meal! / Bon appétit!', theme: 'phrases', pos: 'phrase' },
];

// ─────────────────────────────────────────────
//  THEMES  (derived from VOCAB; for reference)
// ─────────────────────────────────────────────
const THEMES = [
  'greetings', 'numbers', 'time', 'family', 'pronouns', 'food', 'colors',
  'home', 'city', 'verbs', 'adjectives', 'travel', 'weather', 'health',
  'work', 'shopping', 'questions', 'prepositions', 'conjunctions', 'phrases',
];

// ─────────────────────────────────────────────
//  LEVELS
// ─────────────────────────────────────────────
const LEVELS = ['beginner', 'intermediate'];

// ─────────────────────────────────────────────
//  GRAMMAR LESSONS  (12 core + extras)
// ─────────────────────────────────────────────
const GRAMMAR = [
  {
    id: 'alphabet',
    title: 'The Cyrillic Alphabet & Pronunciation',
    level: 'beginner',
    body: 'Russian uses the Cyrillic alphabet (33 letters). Many letters resemble Latin ones but sound different — А, Е, О, С, Т, М, К map roughly to their Latin equivalents, but В = "v", Н = "n", Р = "r", Х = "kh".\n\nVowels: А (ah), Е (ye), Ё (yo), И (ee), О (oh), У (oo), Э (eh), Ю (yu), Я (ya).\nSoft vs hard: И and Й ("short i") soften preceding consonants; Ы is a back-central vowel with no English equivalent — keep the tongue flat.\nStress is not written but changes vowel quality: unstressed О sounds like "a", unstressed Е sounds like "i".\nThe hard sign Ъ separates a prefix from a root; the soft sign Ь softens the preceding consonant.',
    examples: [
      { ru: 'Молоко', translit: 'malakó', en: 'milk — "о" before stress reduces to "a"' },
      { ru: 'Нос', translit: 'nos', en: 'nose — final consonant slightly devoiced' },
      { ru: 'Объяснить', translit: 'ob\'yasnít\'', en: 'to explain — Ъ keeps "б" hard before "я"' },
    ],
  },
  {
    id: 'gender',
    title: 'Noun Gender',
    level: 'beginner',
    body: 'Every Russian noun has a grammatical gender: masculine (m), feminine (f), or neuter (n). Gender affects adjective endings, pronouns, and verb agreement in the past tense.\n\nRules of thumb:\n• Masculine: ends in a consonant (стол, брат) or -й (музей, трамвай).\n• Feminine: ends in -а/-я (мама, неделя) or -ь with feminine pattern (ночь, дверь).\n• Neuter: ends in -о/-е (окно, море) or -мя (время, имя).\n• Soft-sign nouns (ь) must be memorized: врач (m), ночь (f), путь (m), мать (f).\nGender is a property of the word, not the referent — even inanimate objects have gender.',
    examples: [
      { ru: 'стол (m) — красивый стол', translit: 'stol (m) — krasívyy stol', en: 'table (m) — a beautiful table' },
      { ru: 'книга (f) — красивая книга', translit: 'kníga (f) — krasívaya kníga', en: 'book (f) — a beautiful book' },
      { ru: 'окно (n) — красивое окно', translit: 'oknó (n) — krasívoe oknó', en: 'window (n) — a beautiful window' },
    ],
  },
  {
    id: 'nominative',
    title: 'Case 1: Nominative (Именительный падеж)',
    level: 'beginner',
    body: 'The nominative case is the base form of a noun — the dictionary form. It is used for:\n1. The subject of a sentence (the doer of the action).\n2. A predicate noun after "есть" (is) or a dash.\n\nNouns in the nominative appear as listed in the dictionary. Adjectives agree in gender/number:\n• Masculine: -ый/-ий/-ой (новый, синий, молодой)\n• Feminine: -ая/-яя (новая, синяя)\n• Neuter: -ое/-ее (новое, синее)\n• Plural: -ые/-ие (новые, синие)',
    examples: [
      { ru: 'Студент читает книгу.', translit: 'Studént chitáet knígu.', en: 'The student is reading a book. (студент = subject, nominative)' },
      { ru: 'Москва — большой город.', translit: 'Moskvá — bol\'shóy górod.', en: 'Moscow is a big city.' },
      { ru: 'Новая машина стоит дорого.', translit: 'Nóvaya mashína stóit dórogo.', en: 'The new car costs a lot.' },
    ],
  },
  {
    id: 'genitive',
    title: 'Case 2: Genitive (Родительный падеж)',
    level: 'beginner',
    body: 'The genitive case indicates possession, absence, quantity, and follows many prepositions.\n\nMain uses:\n1. Possession: "мamа Ивана" (Ivan\'s mother).\n2. Negation with нет: "нет книги" (there is no book).\n3. After numbers 2–4: "два рубля"; after 5+: "пять рублей".\n4. After prepositions: из, от, до, без, для, у, с (from), около, после.\n\nEndings (singular): masculine consonant → -а/-я; feminine -а → -ы/-и; neuter -о/-е → -а/-я.\nPlural genitive is irregular and must be learned word by word (e.g., книга → книг, стол → столов).',
    examples: [
      { ru: 'У меня нет денег.', translit: 'U menyá net déneg.', en: 'I have no money. (нет + genitive)' },
      { ru: 'Я из России.', translit: 'Ya iz Rossíi.', en: 'I am from Russia. (из + genitive)' },
      { ru: 'Три чашки кофе.', translit: 'Tri cháshki kófe.', en: 'Three cups of coffee. (quantity + genitive)' },
    ],
  },
  {
    id: 'dative',
    title: 'Case 3: Dative (Дательный падеж)',
    level: 'beginner',
    body: 'The dative case marks the indirect object — the recipient of an action — and is used in several important constructions.\n\nMain uses:\n1. Indirect object: "Я дал другу книгу" (I gave my friend the book).\n2. With нравиться/нравится: "Мне нравится музыка" (I like music — lit. "music pleases me").\n3. Age expressions: "Мне двадцать лет" (I am twenty).\n4. Impersonal expressions: "Мне холодно" (I am cold — lit. "to me it is cold").\n5. After prepositions: к (towards), по (along/according to).\n\nEndings (singular): m/n → -у/-ю; f -а → -е/-и.',
    examples: [
      { ru: 'Мне нравится этот фильм.', translit: 'Mne nrávitsya etot fil\'m.', en: 'I like this film. (мне = dative)' },
      { ru: 'Сколько тебе лет?', translit: 'Skól\'ko tebé let?', en: 'How old are you? (тебе = dative)' },
      { ru: 'Иди к врачу.', translit: 'Idí k vrachú.', en: 'Go to the doctor. (к + dative)' },
    ],
  },
  {
    id: 'accusative',
    title: 'Case 4: Accusative (Винительный падеж)',
    level: 'beginner',
    body: 'The accusative is the direct object case — the thing that receives the action directly. It also appears after certain prepositions indicating direction.\n\nMain uses:\n1. Direct object: "Я вижу дом" (I see the house).\n2. Direction with в/на: "Я иду в магазин" (I am going to the store).\n3. Duration/time: "каждый день" (every day), "всю неделю" (all week).\n\nEndings: Inanimate masculine nouns do NOT change (= nominative). Animate masculine: -а/-я (as genitive). Feminine -а → -у/-ю. Neuter = nominative. Plural inanimate = nominative plural; animate plural = genitive plural.\n\nThis animate/inanimate distinction is one of the trickier features of Russian.',
    examples: [
      { ru: 'Я читаю книгу.', translit: 'Ya chitáyu knígu.', en: 'I am reading a book. (книгу = acc. fem.)' },
      { ru: 'Я вижу студента.', translit: 'Ya vizhu studénta.', en: 'I see the student. (студента = acc. animate masc.)' },
      { ru: 'Мы едем в Москву.', translit: 'My yédem v Moskvú.', en: 'We are going to Moscow. (в + acc. for direction)' },
    ],
  },
  {
    id: 'instrumental',
    title: 'Case 5: Instrumental (Творительный падеж)',
    level: 'intermediate',
    body: 'The instrumental expresses the means or instrument by which something is done, accompaniment, and certain predicative constructions.\n\nMain uses:\n1. Instrument/means: "Я пишу ручкой" (I write with a pen).\n2. Accompaniment with с: "Я иду с другом" (I\'m going with a friend).\n3. Predicate after быть in non-present tense: "Он был учителем" (He was a teacher).\n4. After prepositions: с (with), за, перед, над, под, между.\n5. Occupations/identity: "Она работает врачом" (She works as a doctor).\n\nEndings: m/n → -ом/-ем; f -а → -ой/-ей; plural → -ами/-ями.',
    examples: [
      { ru: 'Я пишу карандашом.', translit: 'Ya pishú karandashóm.', en: 'I write with a pencil.' },
      { ru: 'Между нами нет секретов.', translit: 'Mézhdu námi net sekrétov.', en: 'There are no secrets between us.' },
      { ru: 'Он стал инженером.', translit: 'On stal inzhenérom.', en: 'He became an engineer.' },
    ],
  },
  {
    id: 'prepositional',
    title: 'Case 6: Prepositional (Предложный падеж)',
    level: 'beginner',
    body: 'The prepositional case is always used with a preposition — it never appears alone. It indicates location and the topic of speech.\n\nMain uses:\n1. Location with в/на: "Я в магазине" (I am in the store), "книга на столе" (the book is on the table).\n2. Topic/about with о/об: "Мы говорим о погоде" (We\'re talking about the weather).\n3. After при: "при Петре Первом" (under Peter the First).\n\nEndings: nearly all nouns end in -е in the prepositional singular. Exception: nouns in -ий/-ие/-ия → -ии (в санатории, в армии). Plural: -ах/-ях.',
    examples: [
      { ru: 'Книга лежит на столе.', translit: 'Kníga lezhít na stolé.', en: 'The book is lying on the table. (на + prepositional)' },
      { ru: 'Мы живём в России.', translit: 'My zhivyóm v Rossíi.', en: 'We live in Russia.' },
      { ru: 'Расскажи мне о себе.', translit: 'Rasskázhî mne o sebé.', en: 'Tell me about yourself.' },
    ],
  },
  {
    id: 'pronouns',
    title: 'Personal Pronouns & Their Case Forms',
    level: 'beginner',
    body: 'Russian personal pronouns decline through all six cases. Here are the forms:\n\n        NOM   GEN    DAT    ACC    INSTR   PREP\nя        я     меня   мне    меня   мной    мне\nты       ты    тебя   тебе   тебя   тобой   тебе\nон/оно   он    его    ему    его    им      нём\nона      она   её     ей     её     ей      ней\nмы       мы    нас    нам    нас    нами    нас\nвы       вы    вас    вам    вас    вами    вас\nони      они   их     им     их     ими     них\n\nWhen a third-person pronoun follows a preposition, an "н" is added: у него (at his place), к ней (towards her), с ними (with them).',
    examples: [
      { ru: 'Он говорит со мной.', translit: 'On govorít so mnóy.', en: 'He is talking with me. (мной = instr.)' },
      { ru: 'Я думаю о тебе.', translit: 'Ya dúmayu o tebé.', en: 'I am thinking about you. (тебе = prep.)' },
      { ru: 'У неё есть машина.', translit: 'U neyó yest\' mashína.', en: 'She has a car. (неё with preposition)' },
    ],
  },
  {
    id: 'present_tense',
    title: 'Present-Tense Verb Conjugation (1st & 2nd Conjugation)',
    level: 'beginner',
    body: 'Russian verbs in the present tense follow two main conjugation patterns. The infinitive ending (-ать/-ять vs -ить/-еть/-ять) gives a rough guide, but exceptions exist and must be learned.\n\n1st conjugation (e.g., читать — to read):\n  я читаю, ты читаешь, он/она читает\n  мы читаем, вы читаете, они читают\n\n2nd conjugation (e.g., говорить — to speak):\n  я говорю, ты говоришь, он/она говорит\n  мы говорим, вы говорите, они говорят\n\nNote: Only imperfective verbs have a true present tense. Perfective verbs use the same endings but express a future meaning.\nCommon irregulars: хотеть (to want), мочь (to be able to), идти (to go on foot), ехать (to go by transport).',
    examples: [
      { ru: 'Я читаю каждый день.', translit: 'Ya chitáyu kázhdy den\'.', en: 'I read every day.' },
      { ru: 'Ты хочешь кофе?', translit: 'Ty khóchesh\' kófe?', en: 'Do you want coffee? (хотеть is irregular)' },
      { ru: 'Они говорят по-русски.', translit: 'Oní govoryát po-rússki.', en: 'They speak Russian.' },
    ],
  },
  {
    id: 'past_tense',
    title: 'Past Tense',
    level: 'beginner',
    body: 'The Russian past tense is formed from the infinitive stem by replacing the infinitive suffix with a gender/number suffix. Unlike present tense, past-tense forms agree with the SUBJECT\'S GENDER, not person.\n\nFormation: remove -ть (or -ти) → add:\n  masculine: -л (читал, говорил)\n  feminine:  -ла (читала, говорила)\n  neuter:    -ло (читало, говорило)\n  plural:    -ли (читали, говорили)\n\nThe verb быть (to be) in the past: был (m), была (f), было (n), были (pl).\nReflexive verbs: add -сь after -л/-ла/-ло/-ли (училась, учился).\nVerbs with consonant stems (мочь, идти): past forms are irregular — мог/могла/могло/могли; шёл/шла/шло/шли.',
    examples: [
      { ru: 'Она читала книгу.', translit: 'Oná chitála knígu.', en: 'She was reading a book.' },
      { ru: 'Вчера мы были дома.', translit: 'Vchéra my bylí dóma.', en: 'Yesterday we were at home.' },
      { ru: 'Он не пришёл.', translit: 'On ne prishól.', en: 'He did not come (irregular consonant stem).' },
    ],
  },
  {
    id: 'future_tense',
    title: 'Future Tense',
    level: 'intermediate',
    body: 'Russian has two ways to express the future:\n\n1. Compound future (imperfective): быть + imperfective infinitive.\n   я буду читать, ты будешь читать, он будет читать,\n   мы будем читать, вы будете читать, они будут читать.\n\n2. Simple future (perfective): perfective verb conjugated in the present-tense paradigm.\n   я прочитаю, ты прочитаешь, он прочитает, etc.\n\nThe simple future implies a completed result; the compound future describes an ongoing or repeated future action.\n\nThe verb буду/будет/etc. (future of быть) is also used when the verb "to be" is needed in the future: "Я буду дома" (I will be at home).',
    examples: [
      { ru: 'Завтра я буду работать.', translit: 'Závtra ya búdu rabótat\'.', en: 'Tomorrow I will be working. (compound, imperfective)' },
      { ru: 'Я прочитаю эту книгу.', translit: 'Ya prochitáyu étu knígu.', en: 'I will read (finish reading) this book. (simple, perfective)' },
      { ru: 'Она будет дома в семь.', translit: 'Oná búdet dóma v sem\'.', en: 'She will be home at seven.' },
    ],
  },
  {
    id: 'aspect',
    title: 'Verb Aspect: Imperfective vs Perfective',
    level: 'intermediate',
    body: 'Aspect is one of the most important features of Russian verbs. Almost every verb comes in an imperfective/perfective pair.\n\nIMPERFECTIVE: describes ongoing, habitual, or repeated actions; focus is on the process.\n  читать (to read / to be reading), писать (to write), делать (to do)\n\nPERFECTIVE: describes a single completed action; focus is on the result.\n  прочитать (to finish reading), написать (to write/finish writing), сделать (to do/finish doing)\n\nFormation of pairs:\n• Prefix added: писать → написать, делать → сделать\n• Suffix change: -ывать/-ивать vs shorter root: показывать ↔ показать\n• Completely different root (suppletive): говорить ↔ сказать, брать ↔ взять\n\nIn the past tense, both aspects work; choice depends on whether the completion matters.\nIn the future, imperfective uses "буду + inf"; perfective uses simple present endings.',
    examples: [
      { ru: 'Я читал газету. (impf)', translit: 'Ya chitál gazétu.', en: 'I was reading the newspaper.' },
      { ru: 'Я прочитал газету. (pfv)', translit: 'Ya prochitál gazétu.', en: 'I (have) read / finished the newspaper.' },
      { ru: 'Он говорил долго. (impf)', translit: 'On govorál dolgo.', en: 'He spoke for a long time.' },
    ],
  },
  {
    id: 'adjective_agreement',
    title: 'Adjective Agreement',
    level: 'beginner',
    body: 'Russian adjectives agree with the nouns they modify in gender, number, and case. You must change the adjective ending to match the noun.\n\nNominative singular endings:\n  Masculine: -ый/-ий/-ой (новый, синий, молодой)\n  Feminine: -ая/-яя (новая, синяя)\n  Neuter: -ое/-ее (новое, синее)\n  Plural (all genders): -ые/-ие (новые, синие)\n\nIn other cases, the adjective ending changes along with the noun. A useful trick: the adjective ending often mirrors the ending of the question word "какой/какого/какому…" (which/what kind of).\n\nAdjectives in the predicate (after a dash or быть) sometimes use short forms: красив, красива, красиво, красивы.',
    examples: [
      { ru: 'Красивый город (m, nom)', translit: 'Krasívyy górod', en: 'A beautiful city' },
      { ru: 'В красивом городе (m, prep)', translit: 'V krasívom górode', en: 'In a beautiful city' },
      { ru: 'Красивая девушка (f, nom)', translit: 'Krasívaya dévushka', en: 'A beautiful girl' },
    ],
  },
  {
    id: 'numbers_counting',
    title: 'Numbers & Counting (Number + Noun Case)',
    level: 'intermediate',
    body: 'When using numbers with nouns, the case of the noun depends on the last digit of the number.\n\n1 (один): noun in nominative singular — одна книга, один стол.\n2–4 (два, три, четыре): noun in GENITIVE SINGULAR — две книги, три стола, четыре окна.\n5–20, and 11–19: noun in GENITIVE PLURAL — пять книг, десять столов.\n21, 31, …: ends in 1 → nominative singular (двадцать одна книга).\n22–24, 32–34: ends in 2–4 → genitive singular.\n\nOrdinal numerals (first, second, …) are adjectives and agree in gender/number/case: первый, вторая, третье.\n\nNote: "один" has full adjectival declension; "два/две" has distinct masculine and feminine forms (два стола, две книги).',
    examples: [
      { ru: 'Одна кошка, две кошки, пять кошек', translit: 'Odná kóshka, dve kóshki, pyat\' kóshek', en: 'One cat, two cats, five cats (case changes with number)' },
      { ru: 'Мне двадцать один год.', translit: 'Mne dvadtsat\' odín god.', en: 'I am twenty-one years old.' },
      { ru: 'В городе три миллиона человек.', translit: 'V górode tri millióna chelovék.', en: 'The city has three million people.' },
    ],
  },
  {
    id: 'prepositions_cases',
    title: 'Common Prepositions & the Cases They Take',
    level: 'intermediate',
    body: 'Each Russian preposition governs a specific case (or sometimes two, with different meanings).\n\nGENITIVE: из (from, out of), от (from/away from), до (until/to), без (without), для (for), у (at/near/belonging to), около (near/about), после (after), кроме (except), против (against), вместо (instead of).\n\nDATIVE: к (towards), по (along/according to).\n\nACCUSATIVE (direction): в (into), на (onto), за (behind, motion), под (under, motion), через (through/across/in X time).\n\nINSTRUMENTAL: с (with), за (behind, static), под (under, static), над (above), перед (in front of), между (between).\n\nPREPOSITIONAL (location): в (in), на (on/at), о/об (about), при (at/in the presence of).\n\nTip: в/на + accusative = direction; в/на + prepositional = location.',
    examples: [
      { ru: 'Книга на столе. (prep)', translit: 'Kníga na stolé.', en: 'The book is on the table. (location, prepositional)' },
      { ru: 'Положи книгу на стол. (acc)', translit: 'Polozhi knígu na stol.', en: 'Put the book on the table. (direction, accusative)' },
      { ru: 'Мы идём к другу. (dat)', translit: 'My idyóm k drúgu.', en: 'We\'re going to a friend\'s place. (к + dative)' },
    ],
  },
  {
    id: 'questions_negation',
    title: 'Asking Questions & Negation',
    level: 'beginner',
    body: 'Yes/no questions in Russian do not require auxiliary verbs or word-order inversion. Simply raise the intonation on the key word: "Ты читаешь?" (Are you reading?) vs "Ты читаешь." (You are reading.)\n\nQuestion words: что (what), кто (who), где (where, location), куда (where to), откуда (from where), когда (when), почему (why), зачем (what for), как (how), сколько (how much/many), какой (which/what kind), чей (whose).\n\nNegation: place не directly before the verb or the word being negated.\n  "Я не знаю." (I don\'t know.) — sentence negation.\n  "Не я" (Not me.) — word negation.\n\nDouble/triple negation is required: "Я никогда ничего не говорю." (I never say anything.) — never, nothing, not — all together.',
    examples: [
      { ru: 'Ты говоришь по-русски?', translit: 'Ty govórishh po-rússki?', en: 'Do you speak Russian? (intonation question)' },
      { ru: 'Где ты живёшь?', translit: 'Gde ty zhivyósh\'?', en: 'Where do you live? (question-word question)' },
      { ru: 'Я никогда не пью кофе.', translit: 'Ya nikogdá ne p\'yu kófe.', en: 'I never drink coffee. (double negation required)' },
    ],
  },
];

// ─────────────────────────────────────────────
//  HELPERS
// ─────────────────────────────────────────────

/** Return unique themes present in VOCAB with entry counts. */
function vocabThemes() {
  const counts = {};
  VOCAB.forEach((e) => {
    counts[e.theme] = (counts[e.theme] || 0) + 1;
  });
  return Object.entries(counts)
    .map(([theme, count]) => ({ theme, count }))
    .sort((a, b) => a.theme.localeCompare(b.theme));
}

/** Filter vocab by theme (optional) and limit (optional). */
function filterVocab({ theme, limit } = {}) {
  let list = VOCAB;
  if (theme) list = list.filter((e) => e.theme === String(theme).trim().toLowerCase());
  return limit ? list.slice(0, Number(limit)) : list;
}

/** Filter grammar by level (optional). */
function filterGrammar({ level } = {}) {
  if (!level) return GRAMMAR;
  return GRAMMAR.filter((g) => g.level === String(level).trim().toLowerCase());
}

/** Find a single grammar lesson by id. */
function findLesson({ id }) {
  const lesson = GRAMMAR.find((g) => g.id === String(id).trim().toLowerCase());
  if (!lesson) throw new Error(`No grammar lesson with id "${id}". Available: ${GRAMMAR.map((g) => g.id).join(', ')}`);
  return lesson;
}

module.exports = {
  VOCAB,
  GRAMMAR,
  THEMES,
  LEVELS,
  vocabThemes,
  filterVocab,
  filterGrammar,
  findLesson,
};
