"""Achievement catalog."""

ACHIEVEMENTS = [
    {"slug": "first-words", "title": "First Words", "title_native": "Пе́рвые слова́",
     "description": "Learn your first 10 words.", "icon": "🐣",
     "metric": "words_learned", "threshold": 10, "xp_reward": 25},
    {"slug": "wordsmith", "title": "Wordsmith", "title_native": "Знато́к слов",
     "description": "Learn 100 words.", "icon": "📚",
     "metric": "words_learned", "threshold": 100, "xp_reward": 100},
    {"slug": "lexicon-500", "title": "Walking Dictionary", "title_native": "Ходя́чий слова́рь",
     "description": "Learn 500 words.", "icon": "🧠",
     "metric": "words_learned", "threshold": 500, "xp_reward": 300},
    {"slug": "reviewer-100", "title": "Memory Athlete", "title_native": "Атле́т па́мяти",
     "description": "Complete 100 reviews.", "icon": "🏋️",
     "metric": "reviews_done", "threshold": 100, "xp_reward": 100},
    {"slug": "first-lesson", "title": "Первый шаг", "title_native": "Пе́рвый шаг",
     "description": "Pass your first lesson.", "icon": "👣",
     "metric": "lessons_completed", "threshold": 1, "xp_reward": 25},
    {"slug": "course-crusher", "title": "Course Crusher", "title_native": "Гроза́ ку́рсов",
     "description": "Pass 10 lessons.", "icon": "🎓",
     "metric": "lessons_completed", "threshold": 10, "xp_reward": 200},
    {"slug": "streak-7", "title": "One Week Strong", "title_native": "Неде́ля подря́д",
     "description": "Keep a 7-day streak.", "icon": "🔥",
     "metric": "streak_days", "threshold": 7, "xp_reward": 75},
    {"slug": "streak-30", "title": "Habit Formed", "title_native": "Привы́чка",
     "description": "Keep a 30-day streak.", "icon": "🌋",
     "metric": "streak_days", "threshold": 30, "xp_reward": 300},
    {"slug": "chatterbox", "title": "Chatterbox", "title_native": "Болту́н",
     "description": "Send 50 conversation turns.", "icon": "💬",
     "metric": "conversation_turns", "threshold": 50, "xp_reward": 150},
    {"slug": "xp-1000", "title": "Dedicated Learner", "title_native": "Усе́рдный учени́к",
     "description": "Earn 1000 XP.", "icon": "⭐",
     "metric": "xp", "threshold": 1000, "xp_reward": 100},
]
