"""The complete Cyrillic alphabet with learner-oriented data.

Stored on Language.metadata_json and served by /api/v1/languages/ru.
"""

ALPHABET = [
    {"letter": "А а", "name": "а", "ipa": "[a]", "type": "vowel", "translit": "a",
     "note": "Like 'a' in 'father'. Reduces to a schwa-like sound when unstressed.",
     "example": {"word": "ма́ма", "translation": "mom"}},
    {"letter": "Б б", "name": "бэ", "ipa": "[b]", "type": "consonant", "translit": "b",
     "note": "Like 'b' in 'bad'. Devoices to [p] at word end (хлеб → 'khlep').",
     "example": {"word": "брат", "translation": "brother"}},
    {"letter": "В в", "name": "вэ", "ipa": "[v]", "type": "consonant", "translit": "v",
     "note": "Like 'v' in 'vet'. Devoices to [f] at word end.",
     "example": {"word": "вода́", "translation": "water"}},
    {"letter": "Г г", "name": "гэ", "ipa": "[ɡ]", "type": "consonant", "translit": "g",
     "note": "Like 'g' in 'go'. In genitive endings -ого/-его it is pronounced [v].",
     "example": {"word": "го́род", "translation": "city"}},
    {"letter": "Д д", "name": "дэ", "ipa": "[d]", "type": "consonant", "translit": "d",
     "note": "Like 'd' in 'do', but with the tongue on the teeth. Devoices to [t] at word end.",
     "example": {"word": "дом", "translation": "house"}},
    {"letter": "Е е", "name": "е", "ipa": "[je]", "type": "vowel", "translit": "e/ye",
     "note": "Like 'ye' in 'yes' at word start; after a consonant it softens that consonant.",
     "example": {"word": "е́сли", "translation": "if"}},
    {"letter": "Ё ё", "name": "ё", "ipa": "[jo]", "type": "vowel", "translit": "yo",
     "note": "Like 'yo' in 'yolk'. ALWAYS stressed. Often printed as е in real texts.",
     "example": {"word": "ёж", "translation": "hedgehog"}},
    {"letter": "Ж ж", "name": "жэ", "ipa": "[ʐ]", "type": "consonant", "translit": "zh",
     "note": "Like 's' in 'pleasure' but harder, tongue curled back. Always hard.",
     "example": {"word": "жена́", "translation": "wife"}},
    {"letter": "З з", "name": "зэ", "ipa": "[z]", "type": "consonant", "translit": "z",
     "note": "Like 'z' in 'zoo'. Devoices to [s] at word end.",
     "example": {"word": "зима́", "translation": "winter"}},
    {"letter": "И и", "name": "и", "ipa": "[i]", "type": "vowel", "translit": "i",
     "note": "Like 'ee' in 'see'. Softens the preceding consonant.",
     "example": {"word": "и́мя", "translation": "name"}},
    {"letter": "Й й", "name": "и кра́ткое", "ipa": "[j]", "type": "consonant", "translit": "y",
     "note": "'Short i' — like 'y' in 'boy'. Forms diphthongs: мой, чай.",
     "example": {"word": "чай", "translation": "tea"}},
    {"letter": "К к", "name": "ка", "ipa": "[k]", "type": "consonant", "translit": "k",
     "note": "Like 'k' in 'sky' — no puff of air (unaspirated).",
     "example": {"word": "кот", "translation": "cat"}},
    {"letter": "Л л", "name": "эль", "ipa": "[ɫ]", "type": "consonant", "translit": "l",
     "note": "Darker than English 'l', like the l in 'full'. Soft ль is close to 'million'.",
     "example": {"word": "луна́", "translation": "moon"}},
    {"letter": "М м", "name": "эм", "ipa": "[m]", "type": "consonant", "translit": "m",
     "note": "Like 'm' in 'map'.",
     "example": {"word": "мир", "translation": "world / peace"}},
    {"letter": "Н н", "name": "эн", "ipa": "[n]", "type": "consonant", "translit": "n",
     "note": "Like 'n' in 'net', tongue on the teeth.",
     "example": {"word": "нос", "translation": "nose"}},
    {"letter": "О о", "name": "о", "ipa": "[o]", "type": "vowel", "translit": "o",
     "note": "Like 'o' in 'or' when stressed. Unstressed it reduces to [ɐ]/[ə]: молоко́ = 'malako'.",
     "example": {"word": "окно́", "translation": "window"}},
    {"letter": "П п", "name": "пэ", "ipa": "[p]", "type": "consonant", "translit": "p",
     "note": "Like 'p' in 'spin' — unaspirated.",
     "example": {"word": "папа", "translation": "dad"}},
    {"letter": "Р р", "name": "эр", "ipa": "[r]", "type": "consonant", "translit": "r",
     "note": "Rolled/trilled 'r', like Spanish 'perro'.",
     "example": {"word": "рука́", "translation": "hand / arm"}},
    {"letter": "С с", "name": "эс", "ipa": "[s]", "type": "consonant", "translit": "s",
     "note": "Like 's' in 'sun'.",
     "example": {"word": "сын", "translation": "son"}},
    {"letter": "Т т", "name": "тэ", "ipa": "[t]", "type": "consonant", "translit": "t",
     "note": "Like 't' in 'stop' — unaspirated, tongue on the teeth.",
     "example": {"word": "там", "translation": "there"}},
    {"letter": "У у", "name": "у", "ipa": "[u]", "type": "vowel", "translit": "u",
     "note": "Like 'oo' in 'boot', with rounded lips.",
     "example": {"word": "у́тро", "translation": "morning"}},
    {"letter": "Ф ф", "name": "эф", "ipa": "[f]", "type": "consonant", "translit": "f",
     "note": "Like 'f' in 'fun'. Mostly appears in loanwords.",
     "example": {"word": "фильм", "translation": "film"}},
    {"letter": "Х х", "name": "ха", "ipa": "[x]", "type": "consonant", "translit": "kh",
     "note": "Like 'ch' in Scottish 'loch' or German 'Bach'. NOT English 'h'.",
     "example": {"word": "хлеб", "translation": "bread"}},
    {"letter": "Ц ц", "name": "цэ", "ipa": "[ts]", "type": "consonant", "translit": "ts",
     "note": "Like 'ts' in 'cats', as a single sound. Always hard.",
     "example": {"word": "цена́", "translation": "price"}},
    {"letter": "Ч ч", "name": "че", "ipa": "[tɕ]", "type": "consonant", "translit": "ch",
     "note": "Like 'ch' in 'cheap'. Always soft.",
     "example": {"word": "час", "translation": "hour"}},
    {"letter": "Ш ш", "name": "ша", "ipa": "[ʂ]", "type": "consonant", "translit": "sh",
     "note": "Like 'sh' in 'shut' but harder, tongue curled back. Always hard.",
     "example": {"word": "шко́ла", "translation": "school"}},
    {"letter": "Щ щ", "name": "ща", "ipa": "[ɕː]", "type": "consonant", "translit": "shch",
     "note": "A long, soft 'sh' — like 'sheep' stretched. Contrast with hard ш.",
     "example": {"word": "щи", "translation": "cabbage soup"}},
    {"letter": "Ъ ъ", "name": "твёрдый знак", "ipa": "—", "type": "sign", "translit": "\"",
     "note": "Hard sign: a separator that keeps the consonant hard before я/е/ё/ю (подъе́зд).",
     "example": {"word": "подъе́зд", "translation": "building entrance"}},
    {"letter": "Ы ы", "name": "ы", "ipa": "[ɨ]", "type": "vowel", "translit": "y",
     "note": "No English equivalent: say 'ee' while pulling the tongue back. Try 'roses' ('rozɨz').",
     "example": {"word": "сыр", "translation": "cheese"}},
    {"letter": "Ь ь", "name": "мя́гкий знак", "ipa": "—", "type": "sign", "translit": "'",
     "note": "Soft sign: softens (palatalizes) the preceding consonant — мать vs мат.",
     "example": {"word": "мать", "translation": "mother"}},
    {"letter": "Э э", "name": "э", "ipa": "[ɛ]", "type": "vowel", "translit": "e",
     "note": "Like 'e' in 'met'. Does not soften consonants; common in loanwords (э́то, экза́мен).",
     "example": {"word": "э́то", "translation": "this / it"}},
    {"letter": "Ю ю", "name": "ю", "ipa": "[ju]", "type": "vowel", "translit": "yu",
     "note": "Like 'you'. After a consonant it softens it: лю́ди.",
     "example": {"word": "юг", "translation": "south"}},
    {"letter": "Я я", "name": "я", "ipa": "[ja]", "type": "vowel", "translit": "ya",
     "note": "Like 'ya' in 'yard' at word start; after a consonant it softens it: мя́со.",
     "example": {"word": "я́блоко", "translation": "apple"}},
]

PRONUNCIATION_RULES = [
    {"rule": "Vowel reduction", "detail": "Unstressed о sounds like а; unstressed е/я sound like и. молоко́ → [məlɐˈko]."},
    {"rule": "Final devoicing", "detail": "Voiced consonants б в г д ж з devoice at word end: хлеб → [xlʲep], друг → [druk]."},
    {"rule": "Voicing assimilation", "detail": "Consonant clusters match the voicing of the LAST consonant: вокза́л → [vɐɡˈzaɫ], в саду́ → [f sɐˈdu]."},
    {"rule": "Soft consonants", "detail": "и е ё ю я and ь palatalize the preceding consonant — raise the middle of the tongue toward the palate."},
    {"rule": "Stress is unpredictable", "detail": "Stress must be memorized per word and can move within a paradigm: рука́ → ру́ки. Wrong stress can change meaning: за́мок (castle) vs замо́к (lock)."},
]
