"""Conversation scenarios with scripted dialogue trees.

Each script node: partner line (+translation, hints for the learner) and
`expects` branches keyword-matched against the learner's reply. `next: -1`
ends the dialogue. The same scenarios drive the LLM engine via
persona_prompt when a generative provider is configured.
"""


def node(partner, translation, hints=None, expects=None):
    return {"partner": partner, "translation": translation,
            "hints": hints or [], "expects": expects or []}


def branch(keywords, next_, feedback="", model_answer=""):
    return {"keywords": keywords, "next": next_, "feedback": feedback,
            "model_answer": model_answer}


SCENARIOS = [
    {
        "slug": "cafe-order", "title": "Ordering at a Café", "persona": "waiter",
        "setting": "café", "cefr_level": "A1",
        "description": "Order a drink and something to eat, then ask for the bill.",
        "persona_prompt": "You are a friendly waiter in a Moscow café. Greet the "
                          "customer, take their order, offer additions, bring the "
                          "bill when asked. Menu: coffee, tea, water, borscht, blini.",
        "key_vocabulary": ["кофе", "чай", "вода", "хотеть", "пожалуйста", "спасибо"],
        "script": [
            node("Здра́вствуйте! Что вы хоти́те?", "Hello! What would you like?",
                 hints=["Я хочу́ ко́фе, пожа́луйста", "Да́йте чай, пожа́луйста"],
                 expects=[
                     branch(["кофе", "чай", "воду", "вода"], 1,
                            feedback="Order with «Я хочу́...» or «Да́йте..., пожа́луйста»",
                            model_answer="Я хочу́ ко́фе, пожа́луйста."),
                 ]),
            node("Отли́чно! С молоко́м и́ли без?", "Excellent! With milk or without?",
                 hints=["С молоко́м, пожа́луйста", "Без молока́"],
                 expects=[
                     branch(["с молоком", "без", "молоком", "молока"], 2,
                            model_answer="С молоко́м, пожа́луйста.",
                            feedback="Say «с молоко́м» (with milk) or «без молока́» (without)."),
                 ]),
            node("Хорошо́. Что-нибу́дь ещё?", "OK. Anything else?",
                 hints=["Нет, спаси́бо", "Да, хлеб, пожа́луйста"],
                 expects=[
                     branch(["нет", "спасибо"], 3,
                            model_answer="Нет, спаси́бо."),
                     branch(["да", "хлеб", "блины", "борщ"], 3,
                            model_answer="Да, хлеб, пожа́луйста."),
                 ]),
            node("Пожа́луйста! Прия́тного аппети́та!", "Here you are! Enjoy your meal!",
                 hints=["Спаси́бо! Счёт, пожа́луйста"],
                 expects=[
                     branch(["спасибо", "счет", "счёт"], -1,
                            model_answer="Спаси́бо! Счёт, пожа́луйста."),
                 ]),
        ],
    },
    {
        "slug": "meeting-someone", "title": "Meeting Someone New",
        "persona": "stranger", "setting": "party", "cefr_level": "A1",
        "description": "Introduce yourself, ask names, say where you're from.",
        "persona_prompt": "You are a friendly Russian person at a small gathering, "
                          "meeting the learner for the first time. Exchange names, "
                          "ask where they are from and what they do.",
        "key_vocabulary": ["меня зовут", "очень", "жить", "работать", "как дела"],
        "script": [
            node("Приве́т! Меня́ зову́т Ди́ма. А тебя́ как зову́т?",
                 "Hi! My name is Dima. And what's your name?",
                 hints=["Меня́ зову́т ..."],
                 expects=[branch(["меня зовут", "я"], 1,
                                 model_answer="Меня́ зову́т Марк.",
                                 feedback="Say «Меня́ зову́т» + your name.")]),
            node("О́чень прия́тно! Отку́да ты?", "Very nice to meet you! Where are you from?",
                 hints=["Я из Аме́рики", "Я из А́нглии"],
                 expects=[branch(["я из", "из"], 2,
                                 model_answer="Я из Аме́рики.",
                                 feedback="Say «Я из» + country (genitive).")]),
            node("Как интере́сно! А где ты живёшь сейча́с?",
                 "How interesting! And where do you live now?",
                 hints=["Я живу́ в Москве́"],
                 expects=[branch(["я живу", "живу"], 3,
                                 model_answer="Я живу́ в Москве́.",
                                 feedback="Use «Я живу́ в» + city in the prepositional case.")]),
            node("Здо́рово! Ну, о́чень прия́тно познако́миться. Пока́!",
                 "Great! Well, very nice to meet you. Bye!",
                 hints=["Пока́!", "До свида́ния!"],
                 expects=[branch(["пока", "до свидания", "приятно"], -1,
                                 model_answer="Пока́!")]),
        ],
    },
    {
        "slug": "taxi-ride", "title": "Taking a Taxi", "persona": "taxi driver",
        "setting": "taxi", "cefr_level": "A1",
        "description": "Tell the driver where to go, make small talk, pay.",
        "persona_prompt": "You are a chatty Moscow taxi driver. Ask where to go, "
                          "make small talk about the weather, state the price at the end.",
        "key_vocabulary": ["куда", "пожалуйста", "сколько", "деньги", "спасибо"],
        "script": [
            node("Здра́вствуйте! Куда́ е́дем?", "Hello! Where are we going?",
                 hints=["В центр, пожа́луйста", "На вокза́л, пожа́луйста"],
                 expects=[branch(["центр", "вокзал", "аэропорт", "гостиницу", "в", "на"], 1,
                                 model_answer="В центр, пожа́луйста.",
                                 feedback="Name a destination: «В центр, пожа́луйста».")]),
            node("Хорошо́. Сего́дня хоро́шая пого́да, да?",
                 "OK. Nice weather today, right?",
                 hints=["Да, о́чень хоро́шая!", "Нет, хо́лодно"],
                 expects=[branch(["да", "нет", "хорошая", "холодно"], 2,
                                 model_answer="Да, о́чень хоро́шая!")]),
            node("Прие́хали! С вас три́ста рубле́й.",
                 "We've arrived! That'll be 300 rubles.",
                 hints=["Пожа́луйста. Спаси́бо большо́е!"],
                 expects=[branch(["пожалуйста", "спасибо", "вот"], -1,
                                 model_answer="Пожа́луйста. Спаси́бо большо́е!")]),
        ],
    },
    {
        "slug": "hotel-checkin", "title": "Hotel Check-in", "persona": "receptionist",
        "setting": "hotel", "cefr_level": "A2",
        "description": "Check in, give your name, ask about breakfast and Wi-Fi.",
        "persona_prompt": "You are a professional hotel receptionist in "
                          "St. Petersburg. Check the learner in: ask for their name "
                          "and passport, explain breakfast hours and Wi-Fi.",
        "key_vocabulary": ["меня зовут", "у меня", "есть", "сколько", "утро"],
        "script": [
            node("До́брый ве́чер! Вы брони́ровали но́мер?",
                 "Good evening! Did you book a room?",
                 hints=["Да, брони́ровал. Меня́ зову́т ..."],
                 expects=[branch(["да", "бронировал", "меня зовут"], 1,
                                 model_answer="Да, меня́ зову́т Марк Сми́т.",
                                 feedback="Confirm and give your name.")]),
            node("Отли́чно, ваш па́спорт, пожа́луйста.", "Excellent, your passport please.",
                 hints=["Вот, пожа́луйста"],
                 expects=[branch(["вот", "пожалуйста", "паспорт"], 2,
                                 model_answer="Вот, пожа́луйста.")]),
            node("Спаси́бо. За́втрак с семи́ до десяти́. Ваш но́мер — три́ста пять.",
                 "Thank you. Breakfast is from 7 to 10. Your room is 305.",
                 hints=["А есть Wi-Fi?", "Спаси́бо большо́е!"],
                 expects=[branch(["wi-fi", "вай", "интернет"], 3,
                                 model_answer="А есть Wi-Fi?"),
                          branch(["спасибо"], -1, model_answer="Спаси́бо большо́е!")]),
            node("Да, коне́чно, Wi-Fi беспла́тный. Хоро́шего ве́чера!",
                 "Yes of course, the Wi-Fi is free. Have a good evening!",
                 hints=["Спаси́бо, до свида́ния!"],
                 expects=[branch(["спасибо", "до свидания"], -1,
                                 model_answer="Спаси́бо, до свида́ния!")]),
        ],
    },
    # ---------------------------------------------------- Phase 3 scenarios
    {
        "slug": "doctor-visit", "title": "At the Doctor", "persona": "doctor",
        "setting": "clinic", "cefr_level": "A2",
        "description": "Describe symptoms, answer the doctor's questions, "
                       "understand the prescription.",
        "goals": ["Describe what hurts", "Answer since-when questions",
                  "Understand instructions"],
        "grammar_focus": ["dative-case", "impersonal"],
        "persona_prompt": "You are a kind Russian clinic doctor. Ask about "
                          "symptoms, how long, examine, prescribe rest and "
                          "medicine. Simple A2 Russian.",
        "key_vocabulary": ["болеть", "голова", "температура", "лекарство", "здоровье"],
        "script": [
            node("Здра́вствуйте, проходи́те. Что вас беспоко́ит?",
                 "Hello, come in. What is bothering you?",
                 hints=["У меня́ боли́т голова́", "У меня́ температу́ра"],
                 expects=[branch(["болит", "температура", "горло", "живот"], 1,
                                 model_answer="У меня́ боли́т голова́.",
                                 feedback="Use «У меня́ боли́т…» + the body part.")]),
            node("Поня́тно. Давно́ э́то у вас?", "I see. How long have you had this?",
                 hints=["Два дня", "С утра́"],
                 expects=[branch(["дня", "дней", "утра", "вчера", "неделю"], 2,
                                 model_answer="Два дня.")]),
            node("Ничего́ стра́шного. Вот реце́пт — принима́йте лека́рство два ра́за в день.",
                 "Nothing serious. Here's a prescription — take the medicine twice a day.",
                 hints=["Спаси́бо, до́ктор!"],
                 expects=[branch(["спасибо"], -1, model_answer="Спаси́бо, до́ктор!")]),
        ],
    },
    {
        "slug": "shopping-clothes", "title": "Buying Clothes", "persona": "shop assistant",
        "setting": "clothing store", "cefr_level": "A2",
        "description": "Ask for a size, try things on, decide, and pay.",
        "goals": ["Ask for size and color", "Use accusative for wants",
                  "Ask the price"],
        "grammar_focus": ["accusative-case", "adjective-declension"],
        "persona_prompt": "You are a helpful clothing-store assistant in "
                          "Russia. Help find sizes and colors, offer the "
                          "fitting room, state prices.",
        "key_vocabulary": ["куртка", "рубашка", "носить", "сколько", "дорогой"],
        "script": [
            node("До́брый день! Вам помо́чь?", "Good afternoon! May I help you?",
                 hints=["Да, я ищу́ ку́ртку", "Я про́сто смотрю́"],
                 expects=[branch(["ищу", "куртку", "рубашку", "платье"], 1,
                                 model_answer="Да, я ищу́ ку́ртку.",
                                 feedback="Use «Я ищу́…» + accusative."),
                          branch(["смотрю"], -1, model_answer="Я про́сто смотрю́, спаси́бо.")]),
            node("У нас есть чёрные и си́ние. Како́й разме́р вы но́сите?",
                 "We have black and blue ones. What size do you wear?",
                 hints=["Я ношу́ разме́р M"],
                 expects=[branch(["ношу", "размер", "m", "l", "s"], 2,
                                 model_answer="Я ношу́ разме́р M.")]),
            node("Вот, приме́рьте. Ну как?", "Here, try it on. Well?",
                 hints=["Отли́чно! Ско́лько сто́ит?"],
                 expects=[branch(["сколько", "стоит", "отлично", "беру"], 3,
                                 model_answer="Отли́чно! Ско́лько сто́ит?")]),
            node("Четы́ре ты́сячи рубле́й. Ка́ртой и́ли нали́чными?",
                 "Four thousand rubles. Card or cash?",
                 hints=["Ка́ртой, пожа́луйста"],
                 expects=[branch(["картой", "наличными"], -1,
                                 model_answer="Ка́ртой, пожа́луйста.")]),
        ],
    },
    {
        "slug": "job-interview", "title": "Job Interview", "persona": "interviewer",
        "setting": "office", "cefr_level": "B1",
        "description": "Present your experience, strengths, and salary "
                       "expectations in professional register.",
        "goals": ["Describe experience with instrumental case",
                  "Keep formal register (вы)", "Ask a question back"],
        "grammar_focus": ["instrumental-case", "style-registers"],
        "persona_prompt": "You are a professional but friendly HR manager "
                          "interviewing the learner for an office job. Formal "
                          "register, B1 Russian.",
        "key_vocabulary": ["работать", "опыт", "компания", "зарплата", "профессия"],
        "script": [
            node("Здра́вствуйте! Расскажи́те немно́го о себе́.",
                 "Hello! Tell me a little about yourself.",
                 hints=["Я рабо́тал(а) инжене́ром три го́да"],
                 expects=[branch(["работал", "работала", "опыт", "инженером",
                                  "учителем", "программистом"], 1,
                                 model_answer="Я рабо́тал инжене́ром три го́да.",
                                 feedback="Profession takes the instrumental: рабо́тать инжене́ром.")]),
            node("Хорошо́. Почему́ вы хоти́те рабо́тать у нас?",
                 "Good. Why do you want to work with us?",
                 hints=["Мне интере́сен ваш прое́кт"],
                 expects=[branch(["интересен", "интересно", "компания", "проект",
                                  "хочу"], 2,
                                 model_answer="Мне о́чень интере́сен ваш прое́кт.")]),
            node("Каки́е у вас вопро́сы к нам?", "What questions do you have for us?",
                 hints=["Кака́я у вас зарпла́та?", "Когда́ мо́жно нача́ть?"],
                 expects=[branch(["зарплата", "начать", "график", "команда"], -1,
                                 model_answer="Кака́я зарпла́та и когда́ мо́жно нача́ть?")]),
        ],
    },
    {
        "slug": "business-meeting", "title": "Business Meeting", "persona": "client",
        "setting": "meeting room", "cefr_level": "B2",
        "description": "Negotiate a deadline and budget with a client.",
        "goals": ["Propose and counter-propose", "Agree politely",
                  "Summarize the agreement"],
        "grammar_focus": ["conditional", "complex-syntax"],
        "persona_prompt": "You are a demanding but fair Russian client "
                          "negotiating a project deadline and budget. B2 "
                          "business register.",
        "key_vocabulary": ["договор", "сделка", "предлагать", "соглашаться", "цель"],
        "script": [
            node("Добро́ пожа́ловать. Ита́к, когда́ вы смо́жете зако́нчить прое́кт?",
                 "Welcome. So, when will you be able to finish the project?",
                 hints=["Мы предлага́ем два ме́сяца"],
                 expects=[branch(["предлагаем", "месяца", "месяцев", "недель"], 1,
                                 model_answer="Мы предлага́ем два ме́сяца.")]),
            node("Два ме́сяца — э́то до́лго. А е́сли бы мы увели́чили бюдже́т?",
                 "Two months is long. And if we increased the budget?",
                 hints=["Тогда́ мы могли́ бы зако́нчить за шесть неде́ль"],
                 expects=[branch(["могли бы", "тогда", "недель", "быстрее"], 2,
                                 model_answer="Тогда́ мы могли́ бы зако́нчить за шесть неде́ль.",
                                 feedback="Hypotheticals take бы + past: могли́ бы.")]),
            node("Договори́лись. Пришли́те, пожа́луйста, догово́р за́втра.",
                 "Agreed. Please send the contract tomorrow.",
                 hints=["Коне́чно, пришлём за́втра у́тром"],
                 expects=[branch(["пришлём", "пришлем", "конечно", "договорились"], -1,
                                 model_answer="Коне́чно, пришлём за́втра у́тром.")]),
        ],
    },
    {
        "slug": "airport-checkin", "title": "At the Airport", "persona": "airline agent",
        "setting": "airport", "cefr_level": "A2",
        "description": "Check in, drop your bag, find the gate.",
        "goals": ["Hand over documents", "Answer baggage questions",
                  "Understand gate directions"],
        "grammar_focus": ["prepositional-case", "numerals-declension"],
        "persona_prompt": "You are an airline check-in agent at a Russian "
                          "airport. Check documents, ask about baggage, give "
                          "the gate number.",
        "key_vocabulary": ["паспорт", "билет", "чемодан", "аэропорт", "лететь"],
        "script": [
            node("Здра́вствуйте! Ваш па́спорт и биле́т, пожа́луйста.",
                 "Hello! Your passport and ticket, please.",
                 hints=["Вот, пожа́луйста"],
                 expects=[branch(["вот", "пожалуйста"], 1,
                                 model_answer="Вот, пожа́луйста.")]),
            node("Спаси́бо. У вас есть бага́ж?", "Thank you. Do you have luggage?",
                 hints=["Да, оди́н чемода́н", "То́лько ручна́я кладь"],
                 expects=[branch(["чемодан", "кладь", "да", "нет"], 2,
                                 model_answer="Да, оди́н чемода́н.")]),
            node("Гото́во. Ва́ша поса́дка у вы́хода два́дцать три, в де́сять три́дцать.",
                 "Done. Your boarding is at gate 23 at 10:30.",
                 hints=["Спаси́бо! А где вы́ход два́дцать три?"],
                 expects=[branch(["где", "спасибо", "выход"], -1,
                                 model_answer="Спаси́бо! А где вы́ход два́дцать три?")]),
        ],
    },
    {
        "slug": "first-date", "title": "First Date", "persona": "date",
        "setting": "café", "cefr_level": "B1",
        "description": "Small talk about hobbies, likes, and plans — the ты "
                       "register done right.",
        "goals": ["Talk about hobbies with заниматься + instrumental",
                  "Ask follow-up questions", "Suggest meeting again"],
        "grammar_focus": ["instrumental-case", "reflexive-verbs"],
        "persona_prompt": "You are a friendly, curious person on a relaxed "
                          "first date in a café. Informal ты register, B1 "
                          "Russian, warm humor.",
        "key_vocabulary": ["заниматься", "любить", "хобби", "встречаться", "весёлый"],
        "script": [
            node("Приве́т! Ра́да наконе́ц познако́миться. Чем ты занима́ешься в свобо́дное вре́мя?",
                 "Hi! Glad to finally meet. What do you do in your free time?",
                 hints=["Я занима́юсь спо́ртом", "Я люблю́ чита́ть"],
                 expects=[branch(["занимаюсь", "люблю", "играю", "читаю"], 1,
                                 model_answer="Я занима́юсь спо́ртом и люблю́ чита́ть.",
                                 feedback="занима́ться takes the instrumental: спо́ртом.")]),
            node("Здо́рово! А кака́я твоя́ люби́мая кни́га и́ли фильм?",
                 "Cool! And what's your favorite book or film?",
                 hints=["Мой люби́мый фильм — ..."],
                 expects=[branch(["любимый", "любимая", "фильм", "книга"], 2,
                                 model_answer="Мой люби́мый фильм — «Ирония судьбы».")]),
            node("Отли́чный вкус! Мо́жет, встре́тимся ещё раз на сле́дующей неде́ле?",
                 "Great taste! Maybe we could meet again next week?",
                 hints=["С удово́льствием!", "Дава́й!"],
                 expects=[branch(["удовольствием", "давай", "конечно", "да"], -1,
                                 model_answer="С удово́льствием!")]),
        ],
    },
    {
        "slug": "government-office", "title": "At the Government Office",
        "persona": "clerk", "setting": "МФЦ (public services center)",
        "cefr_level": "B1",
        "description": "Register your address: forms, documents, bureaucracy — "
                       "official register survival.",
        "goals": ["Understand official vocabulary", "Ask what documents are needed",
                  "Confirm next steps"],
        "grammar_focus": ["style-registers", "genitive-case"],
        "persona_prompt": "You are a strict but ultimately helpful clerk at a "
                          "Russian public services center (МФЦ). Use official "
                          "register vocabulary, explain document requirements.",
        "key_vocabulary": ["документ", "паспорт", "гражданин", "закон", "подписывать"],
        "script": [
            node("Сле́дующий! Слу́шаю вас.", "Next! I'm listening.",
                 hints=["Мне ну́жно зарегистри́ровать а́дрес"],
                 expects=[branch(["нужно", "зарегистрировать", "регистрация", "адрес"], 1,
                                 model_answer="Мне ну́жно зарегистри́ровать а́дрес.")]),
            node("Каки́е докуме́нты у вас с собо́й?", "What documents do you have with you?",
                 hints=["У меня́ есть па́спорт и догово́р"],
                 expects=[branch(["паспорт", "договор", "документы"], 2,
                                 model_answer="У меня́ есть па́спорт и догово́р.")]),
            node("Хорошо́. Запо́лните заявле́ние и подпиши́те здесь и здесь.",
                 "Good. Fill in the application and sign here and here.",
                 hints=["Гото́во. Когда́ бу́дет резу́льтат?"],
                 expects=[branch(["готово", "когда", "результат", "подписал"], -1,
                                 model_answer="Гото́во. Когда́ бу́дет резу́льтат?")]),
        ],
    },
    {
        "slug": "small-talk-weather", "title": "Small Talk", "persona": "neighbor",
        "setting": "courtyard", "cefr_level": "A1",
        "description": "The universal opener: weather, weekend, family — "
                       "keep a light chat going.",
        "goals": ["React naturally to weather talk", "Ask a question back",
                  "Close the chat politely"],
        "grammar_focus": ["no-verb-to-be", "stress-and-reduction"],
        "persona_prompt": "You are a chatty elderly neighbor in the courtyard. "
                          "Simple A1 Russian about weather and weekend plans.",
        "key_vocabulary": ["погода", "сегодня", "хорошо", "гулять", "завтра"],
        "script": [
            node("До́брый день, сосе́д! Кака́я сего́дня пого́да хоро́шая, да?",
                 "Good afternoon, neighbor! What nice weather today, right?",
                 hints=["Да, о́чень тепло́!", "Да, наконе́ц со́лнце!"],
                 expects=[branch(["да", "тепло", "солнце", "хорошая"], 1,
                                 model_answer="Да, о́чень тепло́!")]),
            node("Что де́лаете в выходны́е? Мы с му́жем е́дем на да́чу.",
                 "What are you doing on the weekend? My husband and I are going to the dacha.",
                 hints=["Я бу́ду гуля́ть в па́рке"],
                 expects=[branch(["гулять", "буду", "дома", "работать", "парке"], 2,
                                 model_answer="Я бу́ду гуля́ть в па́рке.")]),
            node("Прекра́сно! Ну, хоро́шего дня!", "Wonderful! Well, have a good day!",
                 hints=["И вам! До свида́ния!"],
                 expects=[branch(["и вам", "до свидания", "спасибо", "хорошего"], -1,
                                 model_answer="И вам! До свида́ния!")]),
        ],
    },
]
