"""Curated core Russian vocabulary (A1 foundation set).

Every entry carries the full learner payload: stress, IPA, transliteration,
part of speech, frequency rank (per the Sharoff/OpenCorpora frequency
band), morphology, register, mnemonics, examples with stress marks, and
common-mistake notes. This is the hand-curated foundation the bulk import
pipeline (Phase 2, docs/ROADMAP.md) extends toward the top-10k list.
"""


def entry(lemma, stressed, ipa, translit, pos, translation, **kw):
    e = {
        "lemma": lemma, "stressed": stressed, "ipa": ipa,
        "transliteration": translit, "part_of_speech": pos,
        "translation": translation, "cefr_level": kw.pop("cefr", "A1"),
        "frequency_rank": kw.pop("rank", None),
        "register": kw.pop("register", "neutral"),
        "domain": kw.pop("domain", "general"),
        "examples": kw.pop("examples", []),
        "relations": kw.pop("relations", []),
    }
    e.update(kw)
    return e


VOCABULARY = [
    # ------------------------------------------------ greetings & phrases
    entry("здравствуйте", "здра́вствуйте", "[ˈzdrastvʊjtʲe]", "zdravstvuyte",
          "phrase", "hello (formal)", rank=310,
          literal_translation="be healthy",
          mnemonic="From здоро́вье (health) — you wish the person health.",
          usage_notes="Formal or plural greeting. The first в is silent.",
          common_mistakes=["Pronouncing the first 'в' — say 'zdrastvuyte'"],
          examples=[("Здра́вствуйте, меня́ зову́т А́нна.", "Hello, my name is Anna.")]),
    entry("привет", "приве́т", "[prʲɪˈvʲet]", "privet", "phrase",
          "hi (informal)", rank=701, register="informal",
          usage_notes="Only with friends, family, peers. Use здравствуйте with strangers.",
          relations=[("synonym", "здравствуйте", "formal equivalent")],
          examples=[("Приве́т! Как дела́?", "Hi! How are things?")]),
    entry("до свидания", "до свида́ния", "[də svʲɪˈdanʲɪjə]", "do svidaniya",
          "phrase", "goodbye", rank=1500, literal_translation="until the meeting",
          examples=[("До свида́ния, уви́димся за́втра!", "Goodbye, see you tomorrow!")]),
    entry("пока", "пока́", "[pɐˈka]", "poka", "phrase", "bye (informal)",
          rank=180, register="informal",
          usage_notes="Also means 'while / for now' as a conjunction.",
          examples=[("Ну всё, пока́!", "OK then, bye!")]),
    entry("спасибо", "спаси́бо", "[spɐˈsʲibə]", "spasibo", "phrase",
          "thank you", rank=580, literal_translation="God save (спаси Бог)",
          examples=[("Большо́е спаси́бо за по́мощь!", "Thank you very much for the help!")]),
    entry("пожалуйста", "пожа́луйста", "[pɐˈʐaɫʊstə]", "pozhaluysta", "phrase",
          "please / you're welcome", rank=900,
          usage_notes="Means both 'please' and 'you're welcome' — context decides.",
          common_mistakes=["Pronouncing every letter — say 'pazhalusta'"],
          examples=[("Да́йте, пожа́луйста, ко́фе.", "Please give me a coffee.")]),
    entry("извините", "извини́те", "[ɪzvʲɪˈnʲitʲe]", "izvinite", "phrase",
          "excuse me / sorry (formal)", rank=1200,
          relations=[("synonym", "простите", "equally polite")],
          examples=[("Извини́те, где метро́?", "Excuse me, where is the metro?")]),
    entry("да", "да", "[da]", "da", "particle", "yes", rank=11,
          examples=[("Да, коне́чно!", "Yes, of course!")]),
    entry("нет", "нет", "[nʲet]", "net", "particle", "no", rank=31,
          usage_notes="Also 'there is no X': Здесь нет воды́ (+ genitive).",
          examples=[("Нет, спаси́бо.", "No, thank you.")]),
    entry("как дела", "как дела́", "[kak dʲɪˈɫa]", "kak dela", "phrase",
          "how are you", rank=1100, literal_translation="how (are) affairs",
          usage_notes="Common replies: хорошо́ (good), норма́льно (OK), непло́хо (not bad).",
          examples=[("— Как дела́? — Хорошо́, а у тебя́?", "— How are you? — Good, and you?")]),
    entry("меня зовут", "меня́ зову́т", "[mʲɪˈnʲa zɐˈvut]", "menya zovut",
          "phrase", "my name is", literal_translation="(they) call me",
          usage_notes="Literally '(they) call me' — accusative of я + 3rd-person plural.",
          examples=[("Меня́ зову́т Ива́н. А вас?", "My name is Ivan. And yours?")]),
    entry("доброе утро", "до́брое у́тро", "[ˈdobrəje ˈutrə]", "dobroye utro",
          "phrase", "good morning",
          examples=[("До́брое у́тро! Ко́фе бу́дешь?", "Good morning! Want coffee?")]),

    # ---------------------------------------------------------- pronouns
    entry("я", "я", "[ja]", "ya", "pronoun", "I", rank=1,
          inflections={"case_forms": {"nom": "я", "gen": "меня́", "dat": "мне",
                                      "acc": "меня́", "ins": "мной", "pre": "обо мне"}},
          examples=[("Я говорю́ по-ру́сски.", "I speak Russian.")]),
    entry("ты", "ты", "[tɨ]", "ty", "pronoun", "you (informal singular)", rank=17,
          usage_notes="Informal 'you'. Switching from вы to ты is a social step — wait to be invited.",
          inflections={"case_forms": {"nom": "ты", "gen": "тебя́", "dat": "тебе́",
                                      "acc": "тебя́", "ins": "тобо́й", "pre": "о тебе́"}},
          examples=[("Ты где живёшь?", "Where do you live?")]),
    entry("вы", "вы", "[vɨ]", "vy", "pronoun", "you (formal / plural)", rank=24,
          usage_notes="Both polite singular and plural. Capitalized Вы in formal letters.",
          examples=[("Вы говори́те по-англи́йски?", "Do you speak English?")]),
    entry("он", "он", "[on]", "on", "pronoun", "he / it (m)", rank=6,
          examples=[("Он рабо́тает в ба́нке.", "He works at a bank.")]),
    entry("она", "она́", "[ɐˈna]", "ona", "pronoun", "she / it (f)", rank=15,
          examples=[("Она́ живёт в Москве́.", "She lives in Moscow.")]),
    entry("мы", "мы", "[mɨ]", "my", "pronoun", "we", rank=22,
          examples=[("Мы у́чим ру́сский язы́к.", "We are learning Russian.")]),
    entry("они", "они́", "[ɐˈnʲi]", "oni", "pronoun", "they", rank=20,
          examples=[("Они́ до́ма.", "They are at home.")]),
    entry("это", "э́то", "[ˈɛtə]", "eto", "pronoun", "this / it is", rank=8,
          usage_notes="The universal introducer: Это дом = 'This is a house' — no verb 'to be' needed.",
          examples=[("Что э́то? — Э́то кни́га.", "What is this? — This is a book.")]),

    # ----------------------------------------------------- question words
    entry("что", "что", "[ʂto]", "chto", "pronoun", "what", rank=9,
          common_mistakes=["Pronouncing as 'chto' — standard is 'shto'"],
          examples=[("Что ты де́лаешь?", "What are you doing?")]),
    entry("кто", "кто", "[kto]", "kto", "pronoun", "who", rank=60,
          examples=[("Кто э́то?", "Who is this?")]),
    entry("где", "где", "[ɡdʲe]", "gde", "adverb", "where", rank=112,
          usage_notes="Location only. 'Where to' (direction) is куда́.",
          relations=[("family", "куда", "where to (direction)")],
          examples=[("Где туале́т?", "Where is the bathroom?")]),
    entry("когда", "когда́", "[kɐɡˈda]", "kogda", "adverb", "when", rank=90,
          examples=[("Когда́ ты придёшь?", "When will you come?")]),
    entry("почему", "почему́", "[pətɕɪˈmu]", "pochemu", "adverb", "why", rank=250,
          examples=[("Почему́ ты у́чишь ру́сский?", "Why are you learning Russian?")]),
    entry("как", "как", "[kak]", "kak", "adverb", "how / as", rank=13,
          examples=[("Как э́то по-ру́сски?", "How do you say this in Russian?")]),
    entry("сколько", "ско́лько", "[ˈskolʲkə]", "skol'ko", "adverb",
          "how much / how many", rank=300,
          usage_notes="Takes genitive: ско́лько де́нег? (how much money?).",
          examples=[("Ско́лько э́то сто́ит?", "How much does this cost?")]),

    # ------------------------------------------------------------- verbs
    entry("быть", "быть", "[bɨtʲ]", "byt'", "verb", "to be", rank=4,
          aspect="imperfective", root="бы",
          usage_notes="Omitted in the present (Я студе́нт = I [am] a student); used in past (был/была́/бы́ло/бы́ли) and future (бу́ду, бу́дешь...).",
          inflections={"past": {"m": "был", "f": "была́", "n": "бы́ло", "pl": "бы́ли"},
                       "future": {"я": "бу́ду", "ты": "бу́дешь", "он": "бу́дет",
                                  "мы": "бу́дем", "вы": "бу́дете", "они": "бу́дут"}},
          examples=[("Я был до́ма.", "I was at home."),
                    ("За́втра я бу́ду там.", "Tomorrow I will be there.")]),
    entry("говорить", "говори́ть", "[ɡəvɐˈrʲitʲ]", "govorit'", "verb",
          "to speak, to say", rank=45, aspect="imperfective",
          aspect_partner="сказа́ть", root="говор",
          government=[{"case": "prepositional", "preposition": "о", "meaning": "talk about"}],
          inflections={"present": {"я": "говорю́", "ты": "говори́шь", "он": "говори́т",
                                   "мы": "говори́м", "вы": "говори́те", "они": "говоря́т"}},
          mnemonic="A GOVernor GOVoriting (governing) by speaking.",
          examples=[("Вы говори́те по-ру́сски?", "Do you speak Russian?"),
                    ("Он говори́т о рабо́те.", "He is talking about work.")]),
    entry("сказать", "сказа́ть", "[skɐˈzatʲ]", "skazat'", "verb",
          "to say (perfective)", rank=48, aspect="perfective",
          aspect_partner="говори́ть", root="каз",
          usage_notes="Perfective of говорить for a single completed utterance: Он сказа́л, что придёт.",
          inflections={"future": {"я": "скажу́", "ты": "ска́жешь", "они": "ска́жут"}},
          examples=[("Скажи́те, пожа́луйста, где вокза́л?", "Tell me please, where is the station?")]),
    entry("жить", "жить", "[ʐɨtʲ]", "zhit'", "verb", "to live", rank=71,
          aspect="imperfective", root="жи",
          government=[{"case": "prepositional", "preposition": "в/на", "meaning": "live in a place"}],
          inflections={"present": {"я": "живу́", "ты": "живёшь", "он": "живёт",
                                   "мы": "живём", "вы": "живёте", "они": "живу́т"}},
          examples=[("Я живу́ в Москве́.", "I live in Moscow.")]),
    entry("работать", "рабо́тать", "[rɐˈbotətʲ]", "rabotat'", "verb",
          "to work", rank=105, aspect="imperfective", root="работ",
          inflections={"present": {"я": "рабо́таю", "ты": "рабо́таешь", "они": "рабо́тают"}},
          mnemonic="Robots рабо́тают — the English word 'robot' comes from Slavic 'work'.",
          examples=[("Где вы рабо́таете?", "Where do you work?")]),
    entry("хотеть", "хоте́ть", "[xɐˈtʲetʲ]", "khotet'", "verb", "to want",
          rank=57, aspect="imperfective", root="хот",
          usage_notes="Irregular: singular endings are 1st-conjugation, plural are 2nd (хочу́, хо́чешь... хоти́м, хотя́т).",
          inflections={"present": {"я": "хочу́", "ты": "хо́чешь", "он": "хо́чет",
                                   "мы": "хоти́м", "вы": "хоти́те", "они": "хотя́т"}},
          common_mistakes=["Saying 'хочу́т' — correct is хотя́т"],
          examples=[("Я хочу́ чай.", "I want tea.")]),
    entry("знать", "знать", "[znatʲ]", "znat'", "verb", "to know", rank=40,
          aspect="imperfective", root="зна",
          inflections={"present": {"я": "зна́ю", "ты": "зна́ешь", "они": "зна́ют"}},
          examples=[("Я не зна́ю.", "I don't know.")]),
    entry("понимать", "понима́ть", "[pənʲɪˈmatʲ]", "ponimat'", "verb",
          "to understand", rank=150, aspect="imperfective",
          aspect_partner="поня́ть", root="ним", prefixes=["по"],
          inflections={"present": {"я": "понима́ю", "ты": "понима́ешь", "они": "понима́ют"}},
          examples=[("Я не понима́ю. Повтори́те, пожа́луйста.", "I don't understand. Please repeat.")]),
    entry("идти", "идти́", "[ɪˈtʲːi]", "idti", "verb",
          "to go (on foot, one direction)", rank=65, aspect="imperfective",
          root="ид",
          usage_notes="Unidirectional motion verb; its multidirectional pair is ходи́ть.",
          relations=[("family", "ходить", "multidirectional pair")],
          inflections={"present": {"я": "иду́", "ты": "идёшь", "они": "иду́т"},
                       "past": {"m": "шёл", "f": "шла", "pl": "шли"}},
          examples=[("Я иду́ домо́й.", "I am walking home.")]),
    entry("ходить", "ходи́ть", "[xɐˈdʲitʲ]", "khodit'", "verb",
          "to go (on foot, repeatedly)", rank=180, aspect="imperfective",
          root="ход",
          usage_notes="Multidirectional: habitual trips or round trips. Я хожу́ в шко́лу = I go to school (regularly).",
          inflections={"present": {"я": "хожу́", "ты": "хо́дишь", "они": "хо́дят"}},
          examples=[("Мы ча́сто хо́дим в кино́.", "We often go to the movies.")]),
    entry("любить", "люби́ть", "[lʲʊˈbʲitʲ]", "lyubit'", "verb",
          "to love, to like", rank=140, aspect="imperfective", root="люб",
          inflections={"present": {"я": "люблю́", "ты": "лю́бишь", "они": "лю́бят"}},
          common_mistakes=["Forgetting the -л- in я люблю́"],
          examples=[("Я люблю́ ко́фе.", "I love coffee.")]),
    entry("читать", "чита́ть", "[tɕɪˈtatʲ]", "chitat'", "verb", "to read",
          rank=230, aspect="imperfective", aspect_partner="прочита́ть", root="чит",
          inflections={"present": {"я": "чита́ю", "ты": "чита́ешь", "они": "чита́ют"}},
          examples=[("Она́ чита́ет кни́гу.", "She is reading a book.")]),
    entry("писать", "писа́ть", "[pʲɪˈsatʲ]", "pisat'", "verb", "to write",
          rank=260, aspect="imperfective", aspect_partner="написа́ть", root="пис",
          common_mistakes=["Stress: пи́сать (with initial stress) is a vulgar word meaning 'to pee' — always say писа́ть"],
          inflections={"present": {"я": "пишу́", "ты": "пи́шешь", "они": "пи́шут"}},
          examples=[("Я пишу́ письмо́.", "I am writing a letter.")]),
    entry("видеть", "ви́деть", "[ˈvʲidʲɪtʲ]", "videt'", "verb", "to see",
          rank=100, aspect="imperfective", aspect_partner="уви́деть", root="вид",
          inflections={"present": {"я": "ви́жу", "ты": "ви́дишь", "они": "ви́дят"}},
          mnemonic="Related to 'video' — both from the same Indo-European root.",
          examples=[("Я ви́жу мо́ре.", "I see the sea.")]),
    entry("думать", "ду́мать", "[ˈdumətʲ]", "dumat'", "verb", "to think",
          rank=95, aspect="imperfective", root="дум",
          government=[{"case": "prepositional", "preposition": "о", "meaning": "think about"}],
          inflections={"present": {"я": "ду́маю", "ты": "ду́маешь", "они": "ду́мают"}},
          examples=[("Я ду́маю о тебе́.", "I am thinking about you.")]),
    entry("делать", "де́лать", "[ˈdʲeɫətʲ]", "delat'", "verb",
          "to do, to make", rank=120, aspect="imperfective",
          aspect_partner="сде́лать", root="дел",
          inflections={"present": {"я": "де́лаю", "ты": "де́лаешь", "они": "де́лают"}},
          examples=[("Что ты де́лаешь ве́чером?", "What are you doing tonight?")]),
    entry("есть", "есть", "[jesʲtʲ]", "yest'", "verb", "to eat", rank=350,
          aspect="imperfective", aspect_partner="съесть",
          usage_notes="Irregular. Same spelling as 'there is' (У меня́ есть...) — different words.",
          inflections={"present": {"я": "ем", "ты": "ешь", "он": "ест",
                                   "мы": "еди́м", "вы": "еди́те", "они": "едя́т"}},
          examples=[("Я ем суп.", "I am eating soup.")]),
    entry("пить", "пить", "[pʲitʲ]", "pit'", "verb", "to drink", rank=400,
          aspect="imperfective", aspect_partner="вы́пить",
          inflections={"present": {"я": "пью", "ты": "пьёшь", "они": "пьют"}},
          examples=[("Что вы пьёте — чай и́ли ко́фе?", "What do you drink — tea or coffee?")]),
    entry("учить", "учи́ть", "[ʊˈtɕitʲ]", "uchit'", "verb",
          "to learn / to teach", rank=420, aspect="imperfective", root="уч",
          usage_notes="учи́ть + accusative = memorize/study something; учи́ться = to study (at an institution).",
          relations=[("derived", "учиться", "reflexive: to study"),
                     ("family", "учитель", "teacher")],
          inflections={"present": {"я": "учу́", "ты": "у́чишь", "они": "у́чат"}},
          examples=[("Я учу́ ру́сские слова́.", "I am learning Russian words.")]),

    # -------------------------------------------------------------- nouns
    entry("дом", "дом", "[dom]", "dom", "noun", "house, home", rank=94,
          gender="m", animacy="inanimate", root="дом",
          inflections={"declension": {"nom_sg": "дом", "gen_sg": "до́ма",
                                      "pre_sg": "до́ме", "nom_pl": "дома́"}},
          usage_notes="'At home' = до́ма (adverb); 'homeward' = домо́й.",
          relations=[("derived", "дома", "at home"), ("derived", "домой", "homeward")],
          examples=[("Э́то мой дом.", "This is my house.")]),
    entry("город", "го́род", "[ˈɡorət]", "gorod", "noun", "city", rank=170,
          gender="m", animacy="inanimate", root="город",
          inflections={"declension": {"nom_sg": "го́род", "gen_sg": "го́рода",
                                      "nom_pl": "города́"}},
          cultural_notes="Old Russian город meant 'fortress'; -grad in Volgograd is the same root.",
          examples=[("Москва́ — большо́й го́род.", "Moscow is a big city.")]),
    entry("вода", "вода́", "[vɐˈda]", "voda", "noun", "water", rank=280,
          gender="f", animacy="inanimate", root="вод",
          inflections={"declension": {"nom_sg": "вода́", "acc_sg": "во́ду",
                                      "gen_sg": "воды́"}},
          common_mistakes=["Stress moves: вода́ but во́ду (accusative)"],
          examples=[("Да́йте во́ду, пожа́луйста.", "Give me water, please.")]),
    entry("хлеб", "хлеб", "[xlʲep]", "khleb", "noun", "bread", rank=1100,
          gender="m", animacy="inanimate",
          cultural_notes="Bread is central in Russian culture: хлеб-соль (bread and salt) is the traditional welcome.",
          examples=[("Купи́ хлеб, пожа́луйста.", "Buy bread, please.")]),
    entry("человек", "челове́к", "[tɕɪɫɐˈvʲek]", "chelovek", "noun",
          "person, human", rank=36, gender="m", animacy="animate",
          usage_notes="Suppletive plural: лю́ди (people). But with numbers: пять челове́к.",
          relations=[("family", "люди", "people (plural)")],
          examples=[("Он хоро́ший челове́к.", "He is a good person.")]),
    entry("друг", "друг", "[druk]", "drug", "noun", "friend (male)", rank=175,
          gender="m", animacy="animate",
          inflections={"declension": {"nom_sg": "друг", "nom_pl": "друзья́"}},
          usage_notes="Irregular plural друзья́. Female friend = подру́га. друг дру́га = each other.",
          relations=[("family", "подруга", "female friend")],
          examples=[("Он мой лу́чший друг.", "He is my best friend.")]),
    entry("время", "вре́мя", "[ˈvrʲemʲə]", "vremya", "noun", "time", rank=44,
          gender="n", animacy="inanimate",
          usage_notes="One of ten neuter nouns in -мя with irregular declension: gen. вре́мени.",
          inflections={"declension": {"nom_sg": "вре́мя", "gen_sg": "вре́мени",
                                      "nom_pl": "времена́"}},
          examples=[("Ско́лько вре́мени?", "What time is it?")]),
    entry("день", "день", "[dʲenʲ]", "den'", "noun", "day", rank=62,
          gender="m", animacy="inanimate",
          inflections={"declension": {"nom_sg": "день", "gen_sg": "дня",
                                      "nom_pl": "дни"}},
          usage_notes="Fleeting vowel: the е disappears in oblique cases (дня, дню).",
          relations=[("family", "сегодня", "today"), ("antonym", "ночь", "night")],
          examples=[("До́брый день!", "Good afternoon!")]),
    entry("ночь", "ночь", "[notɕ]", "noch'", "noun", "night", rank=210,
          gender="f", animacy="inanimate",
          usage_notes="Feminine (3rd declension) despite ending in a consonant + ь.",
          relations=[("antonym", "день", "day")],
          examples=[("Споко́йной но́чи!", "Good night!")]),
    entry("утро", "у́тро", "[ˈutrə]", "utro", "noun", "morning", rank=450,
          gender="n", animacy="inanimate",
          relations=[("family", "завтра", "tomorrow — lit. 'after morning'")],
          examples=[("У́тром я пью ко́фе.", "In the morning I drink coffee.")]),
    entry("вечер", "ве́чер", "[ˈvʲetɕɪr]", "vecher", "noun", "evening",
          rank=380, gender="m", animacy="inanimate",
          examples=[("До́брый ве́чер!", "Good evening!")]),
    entry("год", "год", "[ɡot]", "god", "noun", "year", rank=50, gender="m",
          animacy="inanimate",
          usage_notes="With 2-4: го́да; with 5+: лет (suppletive): пять лет.",
          common_mistakes=["Saying 'пять го́дов' — correct is пять лет"],
          examples=[("Мне два́дцать лет.", "I am twenty years old.")]),
    entry("работа", "рабо́та", "[rɐˈbotə]", "rabota", "noun", "work, job",
          rank=130, gender="f", animacy="inanimate", root="работ",
          usage_notes="'At work' = на рабо́те (на, not в).",
          examples=[("Я е́ду на рабо́ту.", "I am going to work.")]),
    entry("язык", "язы́к", "[jɪˈzɨk]", "yazyk", "noun", "language; tongue",
          rank=270, gender="m", animacy="inanimate",
          meanings=["language", "tongue (anatomy)"],
          examples=[("Ру́сский язы́к тру́дный, но краси́вый.", "Russian is difficult but beautiful.")]),
    entry("книга", "кни́га", "[ˈknʲiɡə]", "kniga", "noun", "book", rank=340,
          gender="f", animacy="inanimate",
          inflections={"declension": {"nom_sg": "кни́га", "acc_sg": "кни́гу",
                                      "nom_pl": "кни́ги"}},
          examples=[("Я чита́ю интере́сную кни́гу.", "I am reading an interesting book.")]),
    entry("школа", "шко́ла", "[ˈʂkoɫə]", "shkola", "noun", "school",
          rank=390, gender="f", animacy="inanimate",
          examples=[("Де́ти иду́т в шко́лу.", "The children are going to school.")]),
    entry("стол", "стол", "[stoɫ]", "stol", "noun", "table", rank=800,
          gender="m", animacy="inanimate",
          inflections={"declension": {"nom_sg": "стол", "gen_sg": "стола́",
                                      "pre_sg": "столе́"}},
          usage_notes="End-stressed in oblique cases: на столе́.",
          examples=[("Кни́га на столе́.", "The book is on the table.")]),
    entry("окно", "окно́", "[ɐkˈno]", "okno", "noun", "window", rank=980,
          gender="n", animacy="inanimate",
          inflections={"declension": {"nom_sg": "окно́", "nom_pl": "о́кна"}},
          examples=[("Откро́й окно́, пожа́луйста.", "Open the window, please.")]),
    entry("мама", "ма́ма", "[ˈmamə]", "mama", "noun", "mom", rank=320,
          gender="f", animacy="animate", register="informal",
          relations=[("synonym", "мать", "mother (formal)")],
          examples=[("Ма́ма до́ма.", "Mom is at home.")]),
    entry("папа", "па́па", "[ˈpapə]", "papa", "noun", "dad", rank=500,
          gender="m", animacy="animate", register="informal",
          usage_notes="Masculine despite the -а ending (declines like a feminine noun).",
          relations=[("synonym", "отец", "father (formal)")],
          examples=[("Па́па на рабо́те.", "Dad is at work.")]),
    entry("брат", "брат", "[brat]", "brat", "noun", "brother", rank=560,
          gender="m", animacy="animate",
          inflections={"declension": {"nom_sg": "брат", "nom_pl": "бра́тья"}},
          mnemonic="A bratty little brother.",
          examples=[("У меня́ есть брат.", "I have a brother.")]),
    entry("сестра", "сестра́", "[sʲɪˈstra]", "sestra", "noun", "sister",
          rank=650, gender="f", animacy="animate",
          inflections={"declension": {"nom_sg": "сестра́", "nom_pl": "сёстры"}},
          examples=[("Моя́ сестра́ живёт в Пари́же.", "My sister lives in Paris.")]),
    entry("кот", "кот", "[kot]", "kot", "noun", "cat (male)", rank=1900,
          gender="m", animacy="animate",
          relations=[("family", "кошка", "female cat / cat generally")],
          examples=[("Мой кот спит весь день.", "My cat sleeps all day.")]),
    entry("собака", "соба́ка", "[sɐˈbakə]", "sobaka", "noun", "dog",
          rank=1000, gender="f", animacy="animate",
          cultural_notes="The @ sign is called соба́ка ('dog') in Russian.",
          examples=[("Соба́ка хо́чет гуля́ть.", "The dog wants to go for a walk.")]),
    entry("улица", "у́лица", "[ˈulʲɪtsə]", "ulitsa", "noun", "street",
          rank=520, gender="f", animacy="inanimate",
          usage_notes="'Outside' = на у́лице (lit. 'on the street'), even in the countryside.",
          examples=[("На у́лице хо́лодно.", "It's cold outside.")]),
    entry("магазин", "магази́н", "[məɡɐˈzʲin]", "magazin", "noun", "shop, store",
          rank=750, gender="m", animacy="inanimate",
          common_mistakes=["False friend: магази́н is a shop, NOT a magazine (журна́л)"],
          relations=[("false_friend", "magazine", "магазин = shop; magazine = журна́л")],
          examples=[("Я иду́ в магази́н.", "I am going to the store.")]),
    entry("деньги", "де́ньги", "[ˈdʲenʲɡʲɪ]", "den'gi", "noun", "money",
          rank=290, animacy="inanimate",
          usage_notes="Plural-only noun: де́ньги, gen. де́нег. 'I have no money' = У меня́ нет де́нег.",
          examples=[("У меня́ нет де́нег.", "I have no money.")]),
    entry("чай", "чай", "[tɕæj]", "chay", "noun", "tea", rank=1300,
          gender="m", animacy="inanimate",
          cultural_notes="Tea culture is huge in Russia — offering tea is the default hospitality.",
          examples=[("Хоти́те ча́ю?", "Would you like some tea?")]),
    entry("кофе", "ко́фе", "[ˈkofʲe]", "kofe", "noun", "coffee", rank=1600,
          gender="m", animacy="inanimate",
          usage_notes="Indeclinable loanword; masculine in standard usage: вку́сный ко́фе.",
          common_mistakes=["Saying вку́сное ко́фе (neuter) — standard register uses masculine"],
          examples=[("Оди́н ко́фе, пожа́луйста.", "One coffee, please.")]),
    entry("молоко", "молоко́", "[məɫɐˈko]", "moloko", "noun", "milk",
          rank=1700, gender="n", animacy="inanimate",
          usage_notes="Textbook example of vowel reduction: [məɫɐˈko] — only the last о is a real 'o'.",
          examples=[("Ко́фе с молоко́м, пожа́луйста.", "Coffee with milk, please.")]),

    # --------------------------------------------------------- adjectives
    entry("хороший", "хоро́ший", "[xɐˈroʂɨj]", "khoroshiy", "adjective",
          "good", rank=110, root="хорош",
          inflections={"forms": {"m": "хоро́ший", "f": "хоро́шая", "n": "хоро́шее",
                                 "pl": "хоро́шие"}},
          relations=[("antonym", "плохой", "bad"), ("derived", "хорошо", "well (adverb)")],
          examples=[("Э́то хоро́шая иде́я.", "That's a good idea.")]),
    entry("плохой", "плохо́й", "[pɫɐˈxoj]", "plokhoy", "adjective", "bad",
          rank=470,
          relations=[("antonym", "хороший", "good")],
          examples=[("Сего́дня плоха́я пого́да.", "The weather is bad today.")]),
    entry("большой", "большо́й", "[bɐlʲˈʂoj]", "bol'shoy", "adjective",
          "big", rank=85,
          cultural_notes="The Bolshoi Theatre is literally 'The Big Theatre'.",
          relations=[("antonym", "маленький", "small")],
          examples=[("Москва́ — о́чень большо́й го́род.", "Moscow is a very big city.")]),
    entry("маленький", "ма́ленький", "[ˈmalʲɪnʲkʲɪj]", "malen'kiy",
          "adjective", "small", rank=200,
          relations=[("antonym", "большой", "big")],
          examples=[("У нас ма́ленькая кварти́ра.", "We have a small apartment.")]),
    entry("новый", "но́вый", "[ˈnovɨj]", "novyy", "adjective", "new",
          rank=115,
          mnemonic="Related to 'novel' and 'nova' — all mean new.",
          relations=[("antonym", "старый", "old")],
          examples=[("С Но́вым го́дом!", "Happy New Year!")]),
    entry("старый", "ста́рый", "[ˈstarɨj]", "staryy", "adjective", "old",
          rank=225,
          relations=[("antonym", "новый", "new")],
          examples=[("Э́то ста́рый дом.", "This is an old house.")]),
    entry("красивый", "краси́вый", "[krɐˈsʲivɨj]", "krasivyy", "adjective",
          "beautiful", rank=330, root="крас",
          cultural_notes="Кра́сная пло́щадь (Red Square) originally meant 'beautiful square' — красный and красивый share a root.",
          examples=[("Кака́я краси́вая у́лица!", "What a beautiful street!")]),
    entry("русский", "ру́сский", "[ˈruskʲɪj]", "russkiy", "adjective",
          "Russian", rank=75,
          usage_notes="Also a noun: ру́сский = a Russian person. 'In Russian' = по-ру́сски.",
          examples=[("Я учу́ ру́сский язы́к.", "I am learning the Russian language.")]),

    # ------------------------------------------------------------ adverbs
    entry("хорошо", "хорошо́", "[xərɐˈʂo]", "khorosho", "adverb",
          "well / OK", rank=120,
          usage_notes="Also the universal 'OK, agreed'.",
          examples=[("Хорошо́, договори́лись!", "OK, agreed!")]),
    entry("очень", "о́чень", "[ˈotɕɪnʲ]", "ochen'", "adverb", "very",
          rank=80,
          examples=[("О́чень прия́тно!", "Very nice (to meet you)!")]),
    entry("сейчас", "сейча́с", "[sʲɪjˈtɕas]", "seychas", "adverb", "now",
          rank=130, literal_translation="this hour",
          usage_notes="Colloquially pronounced 'щас'. Also 'in a moment': Сейча́с приду́.",
          examples=[("Я сейча́с до́ма.", "I am at home now.")]),
    entry("здесь", "здесь", "[zʲdʲesʲ]", "zdes'", "adverb", "here", rank=160,
          relations=[("synonym", "тут", "here (more colloquial)"),
                     ("antonym", "там", "there")],
          examples=[("Я здесь!", "I am here!")]),
    entry("там", "там", "[tam]", "tam", "adverb", "there", rank=93,
          examples=[("Кто там?", "Who is there?")]),
    entry("дома", "до́ма", "[ˈdomə]", "doma", "adverb", "at home", rank=440,
          usage_notes="Location only. Direction ('homeward') is домо́й: Я иду́ домо́й.",
          examples=[("Ве́чером я до́ма.", "In the evening I am at home.")]),
    entry("сегодня", "сего́дня", "[sʲɪˈvodʲnʲə]", "segodnya", "adverb",
          "today", rank=190, literal_translation="of this day",
          common_mistakes=["The г is pronounced [v]: 'sevodnya', not 'segodnya'"],
          examples=[("Сего́дня хоро́шая пого́да.", "The weather is nice today.")]),
    entry("завтра", "за́втра", "[ˈzaftrə]", "zavtra", "adverb", "tomorrow",
          rank=600,
          relations=[("family", "завтрак", "breakfast")],
          examples=[("Уви́димся за́втра!", "See you tomorrow!")]),
    entry("вчера", "вчера́", "[ftɕɪˈra]", "vchera", "adverb", "yesterday",
          rank=640,
          examples=[("Вчера́ я был в кино́.", "Yesterday I was at the movies.")]),

    # ---------------------------------------------------------- numerals
    entry("один", "оди́н", "[ɐˈdʲin]", "odin", "numeral", "one", rank=70,
          usage_notes="Agrees like an adjective: оди́н дом, одна́ кни́га, одно́ окно́.",
          inflections={"forms": {"m": "оди́н", "f": "одна́", "n": "одно́"}},
          examples=[("Оди́н биле́т, пожа́луйста.", "One ticket, please.")]),
    entry("два", "два", "[dva]", "dva", "numeral", "two", rank=140,
          usage_notes="два (m/n) / две (f) + genitive singular: два дня, две неде́ли.",
          inflections={"forms": {"m/n": "два", "f": "две"}},
          examples=[("Два ко́фе, пожа́луйста.", "Two coffees, please.")]),
    entry("три", "три", "[trʲi]", "tri", "numeral", "three", rank=210,
          examples=[("У меня́ три бра́та.", "I have three brothers.")]),
    entry("четыре", "четы́ре", "[tɕɪˈtɨrʲe]", "chetyre", "numeral", "four",
          rank=400,
          examples=[("Четы́ре челове́ка.", "Four people.")]),
    entry("пять", "пять", "[pʲætʲ]", "pyat'", "numeral", "five", rank=350,
          usage_notes="From 5 upward the counted noun goes to genitive PLURAL: пять домо́в.",
          examples=[("Пять мину́т, пожа́луйста.", "Five minutes, please.")]),
    entry("шесть", "шесть", "[ʂesʲtʲ]", "shest'", "numeral", "six", rank=550,
          examples=[("Шесть часо́в ве́чера.", "Six o'clock in the evening.")]),
    entry("семь", "семь", "[sʲemʲ]", "sem'", "numeral", "seven", rank=590,
          examples=[("Семь дней в неде́ле.", "Seven days in a week.")]),
    entry("восемь", "во́семь", "[ˈvosʲɪmʲ]", "vosem'", "numeral", "eight",
          rank=680,
          examples=[("Во́семь часо́в утра́.", "Eight in the morning.")]),
    entry("девять", "де́вять", "[ˈdʲevʲɪtʲ]", "devyat'", "numeral", "nine",
          rank=700,
          examples=[("Де́вять рубле́й.", "Nine rubles.")]),
    entry("десять", "де́сять", "[ˈdʲesʲɪtʲ]", "desyat'", "numeral", "ten",
          rank=430,
          examples=[("Де́сять мину́т пешко́м.", "Ten minutes on foot.")]),

    # ---------------------------------------- conjunctions & prepositions
    entry("и", "и", "[i]", "i", "conjunction", "and", rank=2,
          examples=[("Чай и ко́фе.", "Tea and coffee.")]),
    entry("а", "а", "[a]", "a", "conjunction", "and / but (contrast)",
          rank=10,
          usage_notes="Contrasting 'and': Я рабо́таю, а он отдыха́ет. Also starts follow-up questions: А ты?",
          examples=[("Я из А́нглии. А вы отку́да?", "I'm from England. And where are you from?")]),
    entry("но", "но", "[no]", "no", "conjunction", "but", rank=35,
          examples=[("Тру́дно, но интере́сно.", "Hard, but interesting.")]),
    entry("или", "и́ли", "[ˈilʲɪ]", "ili", "conjunction", "or", rank=100,
          examples=[("Чай и́ли ко́фе?", "Tea or coffee?")]),
    entry("не", "не", "[nʲe]", "ne", "particle", "not", rank=3,
          usage_notes="Goes directly before the negated word: Я не зна́ю. Unstressed, pronounced together with the verb.",
          examples=[("Я не понима́ю.", "I don't understand.")]),
    entry("в", "в", "[v]", "v", "preposition", "in, into, to", rank=5,
          government=[{"case": "prepositional", "meaning": "location: в го́роде"},
                      {"case": "accusative", "meaning": "direction: в го́род"}],
          usage_notes="Location takes prepositional; direction takes accusative — the core case contrast of Russian.",
          examples=[("Я живу́ в Москве́.", "I live in Moscow."),
                    ("Я е́ду в Москву́.", "I am going to Moscow.")]),
    entry("на", "на", "[na]", "na", "preposition", "on, onto, at", rank=7,
          government=[{"case": "prepositional", "meaning": "location: на столе́"},
                      {"case": "accusative", "meaning": "direction: на стол"}],
          usage_notes="Some places idiomatically take на, not в: на рабо́те, на по́чте, на конце́рте.",
          examples=[("Кни́га на столе́.", "The book is on the table.")]),
    entry("с", "с", "[s]", "s", "preposition", "with; from (off)", rank=14,
          government=[{"case": "instrumental", "meaning": "with: с дру́гом"},
                      {"case": "genitive", "meaning": "off/from: с рабо́ты"}],
          examples=[("Ко́фе с молоко́м.", "Coffee with milk.")]),
    entry("у", "у", "[u]", "u", "preposition", "at, by; possession", rank=25,
          government=[{"case": "genitive", "meaning": "у + genitive"}],
          usage_notes="Possession: У меня́ есть кот = 'By me there is a cat' = I have a cat.",
          examples=[("У меня́ есть вопро́с.", "I have a question.")]),
]
