"""Curated compact wordlist, expanded by services/vocab_factory.py.

Format: (stressed_lemma, pos, translation, topic, cefr, extras?)
See vocab_factory docstring for extras. Words with mobile stress or
consonant mutations carry explicit overrides; the factory generates
everything else (translit, IPA, declension/conjugation, difficulty).
"""

W = [
    # ── food & drink ────────────────────────────────────────────────────
    ("суп", "n", "soup", "food", "A1"),
    ("сала́т", "n", "salad", "food", "A1"),
    ("мя́со", "n", "meat", "food", "A1"),
    ("ры́ба", "n", "fish", "food", "A1"),
    ("ку́рица", "n", "chicken", "food", "A1"),
    ("сыр", "n", "cheese", "food", "A1", {"decl_overrides": {"gen_sg": "сы́ра"}}),
    ("ма́сло", "n", "butter; oil", "food", "A1"),
    ("я́блоко", "n", "apple", "food", "A1", {"decl_overrides": {"nom_pl": "я́блоки", "gen_pl": "я́блок"}}),
    ("бана́н", "n", "banana", "food", "A1"),
    ("апельси́н", "n", "orange", "food", "A2"),
    ("о́вощи", "n", "vegetables", "food", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "о́вощи", "gen_pl": "овоще́й"}}}),
    ("фру́кты", "n", "fruit", "food", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "фру́кты", "gen_pl": "фру́ктов"}}}),
    ("карто́шка", "n", "potato (colloq.)", "food", "A2", {"register": "informal", "decl_overrides": {"gen_pl": "карто́шек"}}),
    ("помидо́р", "n", "tomato", "food", "A2"),
    ("огуре́ц", "n", "cucumber", "food", "A2", {"decl_overrides": {"gen_sg": "огурца́", "nom_pl": "огурцы́", "gen_pl": "огурцо́в", "dat_sg": "огурцу́", "ins_sg": "огурцо́м", "pre_sg": "огурце́"}}),
    ("лук", "n", "onion", "food", "A2"),
    ("са́хар", "n", "sugar", "food", "A1"),
    ("соль", "n", "salt", "food", "A1", {"gender": "f"}),
    ("пе́рец", "n", "pepper", "food", "A2", {"decl_overrides": {"gen_sg": "пе́рца", "dat_sg": "пе́рцу", "ins_sg": "пе́рцем", "pre_sg": "пе́рце", "nom_pl": "пе́рцы", "gen_pl": "пе́рцев"}}),
    ("торт", "n", "cake", "food", "A1"),
    ("моро́женое", "n", "ice cream", "food", "A1", {"gender": "n", "inflections": {"declension": {"nom_sg": "моро́женое", "gen_sg": "моро́женого"}}, "usage_notes": "An adjective used as a noun; declines like an adjective."}),
    ("шокола́д", "n", "chocolate", "food", "A2"),
    ("сок", "n", "juice", "food", "A1"),
    ("пи́во", "n", "beer", "food", "A2"),
    ("вино́", "n", "wine", "food", "A2", {"decl_overrides": {"nom_pl": "ви́на"}}),
    ("за́втрак", "n", "breakfast", "food", "A1", {"relations": [("family", "завтракать", "to have breakfast")]}),
    ("обе́д", "n", "lunch", "food", "A1", {"cultural_notes": "Обед is the main meal, traditionally with soup, eaten 13:00–15:00."}),
    ("у́жин", "n", "dinner, supper", "food", "A1"),
    ("ка́ша", "n", "porridge, kasha", "food", "A2", {"cultural_notes": "A staple Russian breakfast — buckwheat (гре́чка) is the classic."}),
    ("блины́", "n", "blini, pancakes", "food", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "блины́", "gen_pl": "блино́в"}}, "cultural_notes": "Eaten in heaps during Ма́сленица (butter week)."}),
    ("борщ", "n", "borscht", "food", "A2", {"decl_overrides": {"gen_sg": "борща́"}}),
    ("вку́сный", "adj", "tasty", "food", "A1"),
    ("голо́дный", "adj", "hungry", "food", "A2"),
    ("гото́вить", "v", "to cook, prepare", "food", "A2", {"aspect_partner": "пригото́вить", "conj_overrides": {"present": {"я": "гото́влю"}}}),
    ("зака́зывать", "v", "to order", "food", "A2", {"aspect_partner": "заказа́ть"}),

    # ── family & people ─────────────────────────────────────────────────
    ("семья́", "n", "family", "family", "A1", {"decl_overrides": {"acc_sg": "семью́", "nom_pl": "се́мьи", "gen_pl": "семе́й"}}),
    ("роди́тели", "n", "parents", "family", "A1", {"gender": "m", "animacy": "animate", "inflections": {"declension": {"nom_pl": "роди́тели", "gen_pl": "роди́телей"}}}),
    ("оте́ц", "n", "father", "family", "A1", {"animacy": "animate", "decl_overrides": {"gen_sg": "отца́", "dat_sg": "отцу́", "acc_sg": "отца́", "ins_sg": "отцо́м", "pre_sg": "отце́", "nom_pl": "отцы́", "gen_pl": "отцо́в"}, "usage_notes": "Fleeting е: оте́ц → отца́."}),
    ("мать", "n", "mother", "family", "A1", {"gender": "f", "animacy": "animate", "inflections": {"declension": {"nom_sg": "мать", "gen_sg": "ма́тери", "acc_sg": "мать", "ins_sg": "ма́терью", "nom_pl": "ма́тери", "gen_pl": "матере́й"}}, "usage_notes": "Expands to ма́тер- in oblique cases; same pattern as дочь."}),
    ("муж", "n", "husband", "family", "A1", {"animacy": "animate", "decl_overrides": {"nom_pl": "мужья́", "gen_pl": "муже́й"}}),
    ("жена́", "n", "wife", "family", "A1", {"animacy": "animate", "decl_overrides": {"acc_sg": "жену́", "nom_pl": "жёны", "gen_pl": "жён"}}),
    ("сын", "n", "son", "family", "A1", {"animacy": "animate", "decl_overrides": {"nom_pl": "сыновья́", "gen_pl": "сынове́й"}}),
    ("дочь", "n", "daughter", "family", "A1", {"gender": "f", "animacy": "animate", "inflections": {"declension": {"nom_sg": "дочь", "gen_sg": "до́чери", "ins_sg": "до́черью", "nom_pl": "до́чери", "gen_pl": "дочере́й"}}}),
    ("ба́бушка", "n", "grandmother", "family", "A1", {"animacy": "animate", "decl_overrides": {"gen_pl": "ба́бушек"}, "cultural_notes": "The бабушка is a cultural institution — expect to be fed."}),
    ("де́душка", "n", "grandfather", "family", "A1", {"gender": "m", "animacy": "animate", "decl_overrides": {"gen_pl": "де́душек"}}),
    ("ребёнок", "n", "child", "family", "A1", {"animacy": "animate", "decl_overrides": {"gen_sg": "ребёнка", "acc_sg": "ребёнка", "nom_pl": "де́ти", "gen_pl": "дете́й"}, "usage_notes": "Suppletive plural: де́ти (children)."}),
    ("де́ти", "n", "children", "family", "A1", {"gender": "m", "animacy": "animate", "inflections": {"declension": {"nom_pl": "де́ти", "gen_pl": "дете́й", "dat_pl": "де́тям", "ins_pl": "детьми́"}}}),
    ("дя́дя", "n", "uncle", "family", "A2", {"gender": "m", "animacy": "animate"}),
    ("тётя", "n", "aunt", "family", "A2", {"animacy": "animate", "gender": "f"}),
    ("сосе́д", "n", "neighbor", "family", "A2", {"animacy": "animate", "decl_overrides": {"nom_pl": "сосе́ди", "gen_pl": "сосе́дей"}}),
    ("гость", "n", "guest", "family", "A2", {"gender": "m", "animacy": "animate", "cultural_notes": "Гостеприи́мство (hospitality) is sacred; guests are fed first, asked questions later."}),
    ("па́рень", "n", "guy; boyfriend", "family", "A2", {"gender": "m", "animacy": "animate", "register": "informal", "decl_overrides": {"gen_sg": "па́рня", "nom_pl": "па́рни", "gen_pl": "парне́й"}}),
    ("де́вушка", "n", "girl; girlfriend", "family", "A1", {"animacy": "animate", "decl_overrides": {"gen_pl": "де́вушек"}, "usage_notes": "Also the standard polite way to address a young woman (waitress, clerk)."}),
    ("мужчи́на", "n", "man", "family", "A1", {"gender": "m", "animacy": "animate"}),
    ("же́нщина", "n", "woman", "family", "A1", {"animacy": "animate"}),
    ("ма́льчик", "n", "boy", "family", "A1", {"animacy": "animate"}),
    ("подру́га", "n", "female friend", "family", "A1", {"animacy": "animate"}),
    ("знако́мый", "n", "acquaintance", "family", "A2", {"gender": "m", "animacy": "animate", "inflections": {"declension": {"nom_sg": "знако́мый", "gen_sg": "знако́мого"}}, "usage_notes": "Adjective-as-noun; declines like an adjective."}),
    ("люби́мый", "adj", "beloved, favorite", "family", "A2"),
    ("жени́ться", "v", "to marry (of a man)", "family", "B1", {"usage_notes": "Мужчи́на же́нится на + prep.; же́нщина выхо́дит за́муж за + acc.", "conj_overrides": {"present": {"я": "женю́сь", "ты": "же́нишься", "он": "же́нится", "мы": "же́нимся", "вы": "же́нитесь", "они": "же́нятся"}}}),

    # ── home & apartment ────────────────────────────────────────────────
    ("кварти́ра", "n", "apartment", "home", "A1"),
    ("ко́мната", "n", "room", "home", "A1"),
    ("ку́хня", "n", "kitchen", "home", "A1", {"decl_overrides": {"gen_pl": "ку́хонь"}}),
    ("ва́нная", "n", "bathroom", "home", "A2", {"gender": "f", "inflections": {"declension": {"nom_sg": "ва́нная", "gen_sg": "ва́нной"}}, "usage_notes": "Adjective-as-noun. The toilet is usually a separate room: туале́т."}),
    ("туале́т", "n", "toilet, restroom", "home", "A1"),
    ("спа́льня", "n", "bedroom", "home", "A2", {"decl_overrides": {"gen_pl": "спа́лен"}}),
    ("дверь", "n", "door", "home", "A1", {"gender": "f"}),
    ("стена́", "n", "wall", "home", "A2", {"decl_overrides": {"acc_sg": "сте́ну", "nom_pl": "сте́ны"}}),
    ("пол", "n", "floor", "home", "A2", {"decl_overrides": {"pre_sg": "полу́"}, "usage_notes": "Locative in -у: на полу́ (on the floor)."}),
    ("потоло́к", "n", "ceiling", "home", "B1", {"decl_overrides": {"gen_sg": "потолка́", "pre_sg": "потолке́"}}),
    ("крова́ть", "n", "bed", "home", "A1", {"gender": "f"}),
    ("дива́н", "n", "sofa", "home", "A1"),
    ("кре́сло", "n", "armchair", "home", "A2", {"decl_overrides": {"gen_pl": "кре́сел"}}),
    ("шкаф", "n", "wardrobe, cupboard", "home", "A2", {"decl_overrides": {"pre_sg": "шкафу́", "gen_sg": "шка́фа"}, "usage_notes": "Locative in -у: в шкафу́."}),
    ("по́лка", "n", "shelf", "home", "A2", {"decl_overrides": {"gen_pl": "по́лок"}}),
    ("ла́мпа", "n", "lamp", "home", "A1"),
    ("зе́ркало", "n", "mirror", "home", "A2", {"decl_overrides": {"nom_pl": "зеркала́", "gen_pl": "зерка́л"}}),
    ("холоди́льник", "n", "refrigerator", "home", "A2"),
    ("плита́", "n", "stove", "home", "A2", {"decl_overrides": {"nom_pl": "пли́ты"}}),
    ("посу́да", "n", "dishes, tableware", "home", "A2", {"usage_notes": "Singular-only collective: мыть посу́ду = do the dishes."}),
    ("ключ", "n", "key", "home", "A1", {"decl_overrides": {"gen_sg": "ключа́", "nom_pl": "ключи́", "gen_pl": "ключе́й"}}),
    ("эта́ж", "n", "floor, storey", "home", "A1", {"decl_overrides": {"gen_sg": "этажа́", "nom_pl": "этажи́", "gen_pl": "этаже́й", "pre_sg": "этаже́"}}),
    ("лифт", "n", "elevator", "home", "A2"),
    ("да́ча", "n", "dacha, country house", "home", "A2", {"cultural_notes": "The summer escape where half of Russia grows its own potatoes."}),
    ("двор", "n", "courtyard", "home", "A2", {"decl_overrides": {"gen_sg": "двора́", "pre_sg": "дворе́"}}),
    ("убира́ть", "v", "to clean, tidy up", "home", "A2", {"aspect_partner": "убра́ть"}),
    ("мыть", "v", "to wash", "home", "A2", {"aspect_partner": "помы́ть", "conj_overrides": {"present": {"я": "мо́ю", "ты": "мо́ешь", "он": "мо́ет", "мы": "мо́ем", "вы": "мо́ете", "они": "мо́ют"}}}),
    ("ую́тный", "adj", "cozy", "home", "B1", {"cultural_notes": "Ую́т — the Russian cousin of hygge."}),

    # ── city & transport ────────────────────────────────────────────────
    ("це́нтр", "n", "center, downtown", "city", "A1"),
    ("пло́щадь", "n", "square", "city", "A2", {"gender": "f", "decl_overrides": {"gen_pl": "площаде́й"}}),
    ("парк", "n", "park", "city", "A1"),
    ("мост", "n", "bridge", "city", "A2", {"decl_overrides": {"gen_sg": "моста́", "pre_sg": "мосту́"}}),
    ("река́", "n", "river", "city", "A2", {"decl_overrides": {"acc_sg": "ре́ку", "nom_pl": "ре́ки"}}),
    ("доро́га", "n", "road, way", "city", "A1"),
    ("остано́вка", "n", "(bus) stop", "city", "A1", {"decl_overrides": {"gen_pl": "остано́вок"}}),
    ("авто́бус", "n", "bus", "city", "A1"),
    ("трамва́й", "n", "tram", "city", "A2"),
    ("метро́", "n", "metro, subway", "city", "A1", {"gender": "n", "inflections": {"declension": {"nom_sg": "метро́"}}, "usage_notes": "Indeclinable. The Moscow metro doubles as an art museum.", "etymology": "From French métro."}),
    ("по́езд", "n", "train", "city", "A1", {"decl_overrides": {"nom_pl": "поезда́", "gen_pl": "поездо́в"}}),
    ("маши́на", "n", "car", "city", "A1"),
    ("такси́", "n", "taxi", "city", "A1", {"gender": "n", "inflections": {"declension": {"nom_sg": "такси́"}}, "usage_notes": "Indeclinable."}),
    ("велосипе́д", "n", "bicycle", "city", "A2"),
    ("вокза́л", "n", "railway station", "city", "A1", {"usage_notes": "на вокза́ле, not в.", "etymology": "From London's Vauxhall — via a 19th-century pleasure garden near St. Petersburg."}),
    ("аэропо́рт", "n", "airport", "city", "A1", {"decl_overrides": {"pre_sg": "аэропорту́"}}),
    ("больни́ца", "n", "hospital", "city", "A1"),
    ("апте́ка", "n", "pharmacy", "city", "A1", {"etymology": "From Greek apothēkē (storehouse)."}),
    ("банк", "n", "bank", "city", "A1"),
    ("по́чта", "n", "post office; mail", "city", "A1", {"usage_notes": "на по́чте, not в."}),
    ("рестора́н", "n", "restaurant", "city", "A1"),
    ("кафе́", "n", "café", "city", "A1", {"gender": "n", "inflections": {"declension": {"nom_sg": "кафе́"}}, "usage_notes": "Indeclinable; final е pronounced [э]."}),
    ("гости́ница", "n", "hotel", "city", "A1"),
    ("музе́й", "n", "museum", "city", "A1"),
    ("теа́тр", "n", "theater", "city", "A1"),
    ("кино́", "n", "cinema; movie", "city", "A1", {"gender": "n", "inflections": {"declension": {"nom_sg": "кино́"}}, "usage_notes": "Indeclinable: в кино́."}),
    ("це́рковь", "n", "church", "city", "A2", {"gender": "f", "inflections": {"declension": {"nom_sg": "це́рковь", "gen_sg": "це́ркви", "ins_sg": "це́рковью", "nom_pl": "це́ркви", "gen_pl": "церкве́й"}}}),
    ("ры́нок", "n", "market", "city", "A2", {"decl_overrides": {"gen_sg": "ры́нка", "pre_sg": "ры́нке", "nom_pl": "ры́нки"}, "usage_notes": "Fleeting о: ры́нок → ры́нка. на ры́нке, not в."}),
    ("биле́т", "n", "ticket", "city", "A1"),
    ("е́хать", "v", "to go (by vehicle, one direction)", "city", "A1", {"inflections": {"present": {"я": "е́ду", "ты": "е́дешь", "он": "е́дет", "мы": "е́дем", "вы": "е́дете", "они": "е́дут"}, "past": {"m": "е́хал", "f": "е́хала", "pl": "е́хали"}}, "relations": [("family", "ездить", "multidirectional pair")]}),
    ("е́здить", "v", "to go (by vehicle, repeatedly)", "city", "A2", {"conj_overrides": {"present": {"я": "е́зжу"}}}),
    ("лете́ть", "v", "to fly (one direction)", "city", "A2", {"conj_overrides": {"present": {"я": "лечу́"}}}),
    ("остана́вливаться", "v", "to stop; to stay (hotel)", "city", "B1", {"aspect_partner": "останови́ться"}),

    # ── travel ──────────────────────────────────────────────────────────
    ("путеше́ствие", "n", "journey, trip", "travel", "A2"),
    ("о́тпуск", "n", "vacation (from work)", "travel", "A2", {"decl_overrides": {"pre_sg": "отпуске́" }}),
    ("кани́кулы", "n", "school holidays", "travel", "A2", {"gender": "f", "inflections": {"declension": {"nom_pl": "кани́кулы", "gen_pl": "кани́кул"}}}),
    ("па́спорт", "n", "passport", "travel", "A1", {"decl_overrides": {"nom_pl": "паспорта́"}}),
    ("ви́за", "n", "visa", "travel", "A2"),
    ("грани́ца", "n", "border", "travel", "B1", {"usage_notes": "за грани́цей = abroad (location), за грани́цу = abroad (direction)."}),
    ("чемода́н", "n", "suitcase", "travel", "A2"),
    ("рюкза́к", "n", "backpack", "travel", "A2", {"decl_overrides": {"gen_sg": "рюкзака́"}}),
    ("ка́рта", "n", "map; card", "travel", "A1", {"meanings": ["map", "playing card", "bank card"]}),
    ("страна́", "n", "country", "travel", "A1", {"decl_overrides": {"nom_pl": "стра́ны"}}),
    ("мир", "n", "world; peace", "travel", "A1", {"meanings": ["world", "peace"], "cultural_notes": "One word for both 'world' and 'peace' — Tolstoy's «Война и мир» plays on it."}),
    ("мо́ре", "n", "sea", "travel", "A1", {"decl_overrides": {"nom_pl": "моря́", "gen_pl": "море́й"}}),
    ("пляж", "n", "beach", "travel", "A2", {"decl_overrides": {"gen_sg": "пля́жа"}}),
    ("гора́", "n", "mountain", "travel", "A2", {"decl_overrides": {"acc_sg": "го́ру", "nom_pl": "го́ры"}}),
    ("лес", "n", "forest", "travel", "A1", {"decl_overrides": {"pre_sg": "лесу́", "nom_pl": "леса́"}, "usage_notes": "Locative -у: в лесу́."}),
    ("о́зеро", "n", "lake", "travel", "A2", {"decl_overrides": {"nom_pl": "озёра"}}),
    ("о́стров", "n", "island", "travel", "B1", {"decl_overrides": {"nom_pl": "острова́"}}),
    ("столи́ца", "n", "capital city", "travel", "A2"),
    ("дере́вня", "n", "village, countryside", "travel", "A2", {"decl_overrides": {"gen_pl": "дереве́нь"}}),
    ("иностра́нец", "n", "foreigner", "travel", "B1", {"animacy": "animate", "decl_overrides": {"gen_sg": "иностра́нца", "acc_sg": "иностра́нца"}}),
    ("прие́хать", "v", "to arrive (by vehicle)", "travel", "A2", {"aspect": "perfective", "aspect_partner": "приезжа́ть", "inflections": {"future": {"я": "прие́ду", "ты": "прие́дешь", "они": "прие́дут"}, "past": {"m": "прие́хал", "f": "прие́хала", "pl": "прие́хали"}}}),
    ("верну́ться", "v", "to return", "travel", "A2", {"aspect": "perfective", "inflections": {"future": {"я": "верну́сь", "ты": "вернёшься", "они": "верну́тся"}, "past": {"m": "верну́лся", "f": "верну́лась", "pl": "верну́лись"}}}),

    # ── work & study ────────────────────────────────────────────────────
    ("о́фис", "n", "office", "work", "A1"),
    ("компа́ния", "n", "company", "work", "A2"),
    ("нача́льник", "n", "boss", "work", "A2", {"animacy": "animate"}),
    ("колле́га", "n", "colleague", "work", "A2", {"gender": "m", "animacy": "animate", "usage_notes": "Common gender: мой колле́га / моя колле́га."}),
    ("зарпла́та", "n", "salary", "work", "A2", {"etymology": "за + плата — 'payment for'."}),
    ("профе́ссия", "n", "profession", "work", "A2"),
    ("врач", "n", "doctor", "work", "A1", {"animacy": "animate", "decl_overrides": {"gen_sg": "врача́", "acc_sg": "врача́", "nom_pl": "врачи́", "gen_pl": "враче́й"}}),
    ("учи́тель", "n", "teacher", "work", "A1", {"gender": "m", "animacy": "animate", "decl_overrides": {"nom_pl": "учителя́", "gen_pl": "учителе́й"}}),
    ("инжене́р", "n", "engineer", "work", "A2", {"animacy": "animate"}),
    ("продаве́ц", "n", "salesperson", "work", "A2", {"animacy": "animate", "decl_overrides": {"gen_sg": "продавца́", "acc_sg": "продавца́", "nom_pl": "продавцы́", "gen_pl": "продавцо́в"}}),
    ("студе́нт", "n", "student (university)", "work", "A1", {"animacy": "animate"}),
    ("университе́т", "n", "university", "work", "A1"),
    ("уро́к", "n", "lesson", "work", "A1"),
    ("экза́мен", "n", "exam", "work", "A2"),
    ("вопро́с", "n", "question", "work", "A1"),
    ("отве́т", "n", "answer", "work", "A1"),
    ("оши́бка", "n", "mistake", "work", "A2", {"decl_overrides": {"gen_pl": "оши́бок"}}),
    ("пра́ктика", "n", "practice", "work", "A2"),
    ("собра́ние", "n", "meeting", "work", "B1"),
    ("прое́кт", "n", "project", "work", "A2"),
    ("докуме́нт", "n", "document", "work", "A2"),
    ("подпи́сывать", "v", "to sign", "work", "B1", {"aspect_partner": "подписа́ть"}),
    ("учи́ться", "v", "to study (at an institution)", "work", "A1", {"conj_overrides": {"present": {"я": "учу́сь", "ты": "у́чишься", "он": "у́чится", "мы": "у́чимся", "вы": "у́читесь", "они": "у́чатся"}}}),
    ("изуча́ть", "v", "to study (a subject)", "work", "A2", {"government": [{"case": "accusative", "meaning": "study something in depth"}]}),
    ("зараба́тывать", "v", "to earn", "work", "B1", {"aspect_partner": "зарабо́тать"}),
    ("отдыха́ть", "v", "to rest, relax", "work", "A1", {"aspect_partner": "отдохну́ть"}),
    ("помога́ть", "v", "to help", "work", "A2", {"aspect_partner": "помо́чь", "government": [{"case": "dative", "meaning": "help someone: помога́ть дру́гу"}]}),
    ("объясня́ть", "v", "to explain", "work", "A2", {"aspect_partner": "объясни́ть"}),
    ("спра́шивать", "v", "to ask (a question)", "work", "A2", {"aspect_partner": "спроси́ть", "relations": [("false_friend", "проси́ть", "to request — not to ask a question")]}),
    ("отвеча́ть", "v", "to answer", "work", "A2", {"aspect_partner": "отве́тить", "government": [{"case": "dative", "meaning": "answer someone"}]}),

    # ── body & health ───────────────────────────────────────────────────
    ("голова́", "n", "head", "body", "A1", {"decl_overrides": {"acc_sg": "го́лову", "nom_pl": "го́ловы"}}),
    ("лицо́", "n", "face", "body", "A2", {"decl_overrides": {"nom_pl": "ли́ца"}}),
    ("глаз", "n", "eye", "body", "A1", {"decl_overrides": {"nom_pl": "глаза́", "gen_pl": "глаз", "pre_sg": "глазу́"}}),
    ("у́хо", "n", "ear", "body", "A2", {"decl_overrides": {"nom_pl": "у́ши", "gen_pl": "уше́й"}}),
    ("нос", "n", "nose", "body", "A1", {"decl_overrides": {"pre_sg": "носу́"}}),
    ("рот", "n", "mouth", "body", "A2", {"decl_overrides": {"gen_sg": "рта", "pre_sg": "рту"}, "usage_notes": "Fleeting о: рот → рта."}),
    ("зуб", "n", "tooth", "body", "A2", {"decl_overrides": {"nom_pl": "зу́бы", "gen_pl": "зубо́в"}}),
    ("рука́", "n", "hand, arm", "body", "A1", {"decl_overrides": {"acc_sg": "ру́ку", "nom_pl": "ру́ки", "gen_sg": "руки́"}}),
    ("нога́", "n", "leg, foot", "body", "A1", {"decl_overrides": {"acc_sg": "но́гу", "nom_pl": "но́ги", "gen_sg": "ноги́"}}),
    ("па́лец", "n", "finger, toe", "body", "A2", {"decl_overrides": {"gen_sg": "па́льца", "nom_pl": "па́льцы", "gen_pl": "па́льцев"}}),
    ("се́рдце", "n", "heart", "body", "A2", {"decl_overrides": {"gen_pl": "серде́ц"}, "usage_notes": "The д is silent: [се́рце]."}),
    ("спина́", "n", "back", "body", "A2", {"decl_overrides": {"acc_sg": "спи́ну"}}),
    ("живо́т", "n", "stomach, belly", "body", "A2", {"decl_overrides": {"gen_sg": "живота́"}}),
    ("во́лосы", "n", "hair", "body", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "во́лосы", "gen_pl": "воло́с"}}}),
    ("здоро́вье", "n", "health", "body", "A2", {"relations": [("family", "здравствуйте", "the greeting literally wishes health")]}),
    ("боле́знь", "n", "illness", "body", "B1", {"gender": "f"}),
    ("температу́ра", "n", "temperature, fever", "body", "A2"),
    ("лека́рство", "n", "medicine", "body", "A2"),
    ("боле́ть", "v", "to be ill; to hurt", "body", "A2", {"usage_notes": "Two verbs: я боле́ю (I am ill) vs у меня́ боли́т голова́ (my head hurts).", "conj_overrides": {"present": {"я": "боле́ю", "ты": "боле́ешь", "он": "боле́ет", "мы": "боле́ем", "вы": "боле́ете", "они": "боле́ют"}}}),
    ("уста́ть", "v", "to get tired", "body", "A2", {"aspect": "perfective", "inflections": {"future": {"я": "уста́ну", "ты": "уста́нешь", "они": "уста́нут"}, "past": {"m": "уста́л", "f": "уста́ла", "pl": "уста́ли"}}, "usage_notes": "Я уста́л(а) = I'm tired — past form, present meaning."}),
    ("спать", "v", "to sleep", "body", "A1", {"conj_overrides": {"present": {"я": "сплю", "ты": "спишь", "он": "спит", "мы": "спим", "вы": "спи́те", "они": "спят"}, "past": {"f": "спала́"}}}),
    ("здоро́вый", "adj", "healthy", "body", "A2"),
    ("больно́й", "adj", "sick; painful", "body", "A2"),

    # ── nature & weather ────────────────────────────────────────────────
    ("пого́да", "n", "weather", "nature", "A1"),
    ("со́лнце", "n", "sun", "nature", "A1", {"usage_notes": "The л is silent: [со́нце]."}),
    ("не́бо", "n", "sky", "nature", "A2", {"decl_overrides": {"nom_pl": "небеса́"}}),
    ("звезда́", "n", "star", "nature", "A2", {"decl_overrides": {"nom_pl": "звёзды"}}),
    ("луна́", "n", "moon", "nature", "A2"),
    ("дождь", "n", "rain", "nature", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "дождя́"}, "usage_notes": "Идёт дождь = it's raining (lit. 'rain is walking')."}),
    ("снег", "n", "snow", "nature", "A1", {"decl_overrides": {"pre_sg": "снегу́", "nom_pl": "снега́"}}),
    ("ве́тер", "n", "wind", "nature", "A2", {"decl_overrides": {"gen_sg": "ве́тра", "pre_sg": "ветру́"}}),
    ("тума́н", "n", "fog", "nature", "B1"),
    ("гроза́", "n", "thunderstorm", "nature", "B1", {"decl_overrides": {"nom_pl": "гро́зы"}}),
    ("во́здух", "n", "air", "nature", "A2"),
    ("земля́", "n", "earth, ground, land", "nature", "A2", {"decl_overrides": {"acc_sg": "зе́млю", "nom_pl": "зе́мли", "gen_pl": "земе́ль"}}),
    ("де́рево", "n", "tree; wood", "nature", "A1", {"decl_overrides": {"nom_pl": "дере́вья", "gen_pl": "дере́вьев"}}),
    ("цвето́к", "n", "flower", "nature", "A1", {"decl_overrides": {"gen_sg": "цветка́", "nom_pl": "цветы́", "gen_pl": "цвето́в"}}),
    ("трава́", "n", "grass", "nature", "A2", {"decl_overrides": {"nom_pl": "тра́вы"}}),
    ("пти́ца", "n", "bird", "nature", "A2", {"animacy": "animate"}),
    ("ло́шадь", "n", "horse", "nature", "A2", {"gender": "f", "animacy": "animate", "decl_overrides": {"gen_pl": "лошаде́й"}}),
    ("коро́ва", "n", "cow", "nature", "A2", {"animacy": "animate"}),
    ("медве́дь", "n", "bear", "nature", "A2", {"gender": "m", "animacy": "animate", "etymology": "мёд + ведать — 'the honey-knower'; the true name was taboo."}),
    ("волк", "n", "wolf", "nature", "A2", {"animacy": "animate", "decl_overrides": {"nom_pl": "во́лки", "gen_pl": "волко́в"}}),
    ("зима́", "n", "winter", "nature", "A1", {"decl_overrides": {"acc_sg": "зи́му", "nom_pl": "зи́мы"}, "usage_notes": "зимо́й = in winter (instrumental as adverb)."}),
    ("весна́", "n", "spring", "nature", "A1", {"decl_overrides": {"nom_pl": "вёсны"}}),
    ("ле́то", "n", "summer", "nature", "A1"),
    ("о́сень", "n", "autumn", "nature", "A1", {"gender": "f"}),
    ("тёплый", "adj", "warm", "nature", "A1"),
    ("холо́дный", "adj", "cold", "nature", "A1"),
    ("жа́ркий", "adj", "hot (weather)", "nature", "A2"),

    # ── clothing ────────────────────────────────────────────────────────
    ("оде́жда", "n", "clothes", "clothing", "A1", {"usage_notes": "Singular-only collective."}),
    ("руба́шка", "n", "shirt", "clothing", "A2", {"decl_overrides": {"gen_pl": "руба́шек"}}),
    ("футбо́лка", "n", "T-shirt", "clothing", "A2", {"decl_overrides": {"gen_pl": "футбо́лок"}}),
    ("брю́ки", "n", "trousers", "clothing", "A2", {"gender": "f", "inflections": {"declension": {"nom_pl": "брю́ки", "gen_pl": "брюк"}}, "usage_notes": "Plural-only."}),
    ("джи́нсы", "n", "jeans", "clothing", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "джи́нсы", "gen_pl": "джи́нсов"}}}),
    ("пла́тье", "n", "dress", "clothing", "A2", {"decl_overrides": {"gen_pl": "пла́тьев"}}),
    ("ю́бка", "n", "skirt", "clothing", "A2", {"decl_overrides": {"gen_pl": "ю́бок"}}),
    ("ку́ртка", "n", "jacket", "clothing", "A2", {"decl_overrides": {"gen_pl": "ку́рток"}}),
    ("пальто́", "n", "coat", "clothing", "A2", {"gender": "n", "inflections": {"declension": {"nom_sg": "пальто́"}}, "usage_notes": "Indeclinable."}),
    ("ша́пка", "n", "hat (warm)", "clothing", "A2", {"decl_overrides": {"gen_pl": "ша́пок"}}),
    ("шарф", "n", "scarf", "clothing", "A2"),
    ("перча́тки", "n", "gloves", "clothing", "B1", {"gender": "f", "inflections": {"declension": {"nom_pl": "перча́тки", "gen_pl": "перча́ток"}}}),
    ("о́бувь", "n", "footwear", "clothing", "A2", {"gender": "f"}),
    ("боти́нки", "n", "boots, shoes", "clothing", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "боти́нки", "gen_pl": "боти́нок"}}}),
    ("носи́ть", "v", "to wear; to carry (multidir.)", "clothing", "A2", {"conj_overrides": {"present": {"я": "ношу́"}}}),
    ("надева́ть", "v", "to put on", "clothing", "A2", {"aspect_partner": "наде́ть", "common_mistakes": ["Don't confuse with одева́ть (to dress someone)"]}),

    # ── time & calendar ─────────────────────────────────────────────────
    ("неде́ля", "n", "week", "time", "A1", {"decl_overrides": {"gen_pl": "неде́ль"}}),
    ("ме́сяц", "n", "month; moon", "time", "A1", {"decl_overrides": {"gen_pl": "ме́сяцев", "ins_sg": "ме́сяцем", "nom_pl": "ме́сяцы"}}),
    ("час", "n", "hour", "time", "A1", {"decl_overrides": {"gen_sg": "ча́са", "nom_pl": "часы́", "gen_pl": "часо́в"}, "usage_notes": "With 2-4: часа́ (два часа́); clock/watch is the plural часы́."}),
    ("мину́та", "n", "minute", "time", "A1"),
    ("секу́нда", "n", "second", "time", "A2"),
    ("понеде́льник", "n", "Monday", "time", "A1", {"etymology": "по + неде́ля: the day 'after the do-nothing day' (неделя originally meant Sunday)."}),
    ("вто́рник", "n", "Tuesday", "time", "A1", {"etymology": "From второ́й (second)."}),
    ("среда́", "n", "Wednesday", "time", "A1", {"decl_overrides": {"acc_sg": "сре́ду"}, "etymology": "From среди́на (middle) — midweek."}),
    ("четве́рг", "n", "Thursday", "time", "A1", {"decl_overrides": {"gen_sg": "четверга́"}}),
    ("пя́тница", "n", "Friday", "time", "A1"),
    ("суббо́та", "n", "Saturday", "time", "A1", {"etymology": "From Hebrew shabbat."}),
    ("воскресе́нье", "n", "Sunday", "time", "A1", {"decl_overrides": {"gen_pl": "воскресе́ний"}, "etymology": "From воскресе́ние — resurrection."}),
    ("янва́рь", "n", "January", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "января́"}}),
    ("февра́ль", "n", "February", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "февраля́"}}),
    ("ма́рт", "n", "March", "time", "A1"),
    ("апре́ль", "n", "April", "time", "A1", {"gender": "m"}),
    ("май", "n", "May", "time", "A1", {"decl_overrides": {"gen_sg": "ма́я"}}),
    ("ию́нь", "n", "June", "time", "A1", {"gender": "m"}),
    ("ию́ль", "n", "July", "time", "A1", {"gender": "m"}),
    ("а́вгуст", "n", "August", "time", "A1"),
    ("сентя́брь", "n", "September", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "сентября́"}}),
    ("октя́брь", "n", "October", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "октября́"}}),
    ("ноя́брь", "n", "November", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "ноября́"}}),
    ("дека́брь", "n", "December", "time", "A1", {"gender": "m", "decl_overrides": {"gen_sg": "декабря́"}}),
    ("пра́здник", "n", "holiday, celebration", "time", "A2", {"usage_notes": "The д is silent: [пра́зник]."}),
    ("день рожде́ния", "phrase", "birthday", "time", "A1", {"usage_notes": "Literally 'day of birth'; С днём рожде́ния! = Happy birthday!"}),
    ("ра́но", "adv", "early", "time", "A1"),
    ("по́здно", "adv", "late", "time", "A1", {"usage_notes": "The д is silent: [по́зно]."}),
    ("ча́сто", "adv", "often", "time", "A1"),
    ("ре́дко", "adv", "rarely", "time", "A2"),
    ("всегда́", "adv", "always", "time", "A1"),
    ("никогда́", "adv", "never", "time", "A1", {"usage_notes": "Requires double negation: Я никогда́ не был в Москве́."}),
    ("иногда́", "adv", "sometimes", "time", "A1"),
    ("сно́ва", "adv", "again", "time", "A2"),
    ("уже́", "adv", "already", "time", "A1"),
    ("ещё", "adv", "still; yet; more", "time", "A1"),
    ("пото́м", "adv", "later, then", "time", "A1"),

    # ── emotions & character ────────────────────────────────────────────
    ("сча́стье", "n", "happiness", "emotions", "A2"),
    ("ра́дость", "n", "joy", "emotions", "B1", {"gender": "f"}),
    ("страх", "n", "fear", "emotions", "B1"),
    ("грусть", "n", "sadness", "emotions", "B1", {"gender": "f"}),
    ("любо́вь", "n", "love", "emotions", "A2", {"gender": "f", "inflections": {"declension": {"nom_sg": "любо́вь", "gen_sg": "любви́", "ins_sg": "любо́вью"}}, "usage_notes": "Fleeting о: любо́вь → любви́."}),
    ("наде́жда", "n", "hope", "emotions", "B1"),
    ("мечта́", "n", "dream (aspiration)", "emotions", "A2", {"relations": [("family", "сон", "dream while sleeping — a different word")]}),
    ("сон", "n", "sleep; dream", "emotions", "A2", {"decl_overrides": {"gen_sg": "сна", "pre_sg": "сне"}, "usage_notes": "Fleeting о: сон → сна."}),
    ("настрое́ние", "n", "mood", "emotions", "A2"),
    ("хара́ктер", "n", "character, personality", "emotions", "B1"),
    ("сча́стливый", "adj", "happy", "emotions", "A2", {"usage_notes": "First т is silent: [щасли́вый]."}),
    ("гру́стный", "adj", "sad", "emotions", "A2", {"usage_notes": "The т is silent: [гру́сный]."}),
    ("весёлый", "adj", "cheerful", "emotions", "A2"),
    ("серьёзный", "adj", "serious", "emotions", "A2"),
    ("до́брый", "adj", "kind", "emotions", "A1"),
    ("злой", "adj", "angry, evil", "emotions", "A2", {"inflections": {"forms": {"m": "злой", "f": "зла́я", "n": "зло́е", "pl": "злы́е"}}}),
    ("у́мный", "adj", "smart", "emotions", "A2"),
    ("глу́пый", "adj", "stupid, silly", "emotions", "A2"),
    ("сме́лый", "adj", "brave", "emotions", "B1"),
    ("лени́вый", "adj", "lazy", "emotions", "B1"),
    ("ве́жливый", "adj", "polite", "emotions", "B1"),
    ("боя́ться", "v", "to be afraid", "emotions", "A2", {"government": [{"case": "genitive", "meaning": "afraid OF: боя́ться темноты́"}], "conj_overrides": {"present": {"я": "бою́сь", "ты": "бои́шься", "он": "бои́тся", "мы": "бои́мся", "вы": "бои́тесь", "они": "боя́тся"}}}),
    ("наде́яться", "v", "to hope", "emotions", "B1", {"conj_overrides": {"present": {"я": "наде́юсь", "ты": "наде́ешься", "он": "наде́ется", "мы": "наде́емся", "вы": "наде́етесь", "они": "наде́ются"}}}),
    ("смея́ться", "v", "to laugh", "emotions", "A2", {"government": [{"case": "instrumental", "preposition": "над", "meaning": "laugh AT: смея́ться над шу́ткой"}], "conj_overrides": {"present": {"я": "смею́сь", "ты": "смеёшься", "он": "смеётся", "мы": "смеёмся", "вы": "смеётесь", "они": "смею́тся"}}}),
    ("пла́кать", "v", "to cry", "emotions", "A2", {"conj_overrides": {"present": {"я": "пла́чу", "ты": "пла́чешь", "он": "пла́чет", "мы": "пла́чем", "вы": "пла́чете", "они": "пла́чут"}}}),
    ("улыба́ться", "v", "to smile", "emotions", "A2", {"government": [{"case": "dative", "meaning": "smile at someone"}]}),

    # ── daily verbs ─────────────────────────────────────────────────────
    ("встава́ть", "v", "to get up", "daily", "A1", {"aspect_partner": "встать", "conj_overrides": {"present": {"я": "встаю́", "ты": "встаёшь", "он": "встаёт", "мы": "встаём", "вы": "встаёте", "они": "встаю́т"}}}),
    ("умыва́ться", "v", "to wash one's face", "daily", "A2"),
    ("одева́ться", "v", "to get dressed", "daily", "A2", {"aspect_partner": "оде́ться"}),
    ("за́втракать", "v", "to have breakfast", "daily", "A1", {"aspect_partner": "поза́втракать"}),
    ("обе́дать", "v", "to have lunch", "daily", "A1", {"aspect_partner": "пообе́дать"}),
    ("у́жинать", "v", "to have dinner", "daily", "A1", {"aspect_partner": "поу́жинать"}),
    ("гуля́ть", "v", "to stroll, walk", "daily", "A1", {"aspect_partner": "погуля́ть", "usage_notes": "Walking for pleasure — a national pastime."}),
    ("покупа́ть", "v", "to buy", "daily", "A1", {"aspect_partner": "купи́ть"}),
    ("купи́ть", "v", "to buy (pf.)", "daily", "A1", {"aspect": "perfective", "aspect_partner": "покупа́ть", "inflections": {"future": {"я": "куплю́", "ты": "ку́пишь", "он": "ку́пит", "мы": "ку́пим", "вы": "ку́пите", "они": "ку́пят"}, "past": {"m": "купи́л", "f": "купи́ла", "pl": "купи́ли"}}}),
    ("продава́ть", "v", "to sell", "daily", "A2", {"aspect_partner": "прода́ть", "conj_overrides": {"present": {"я": "продаю́", "ты": "продаёшь", "он": "продаёт", "мы": "продаём", "вы": "продаёте", "они": "продаю́т"}}}),
    ("плати́ть", "v", "to pay", "daily", "A2", {"aspect_partner": "заплати́ть", "conj_overrides": {"present": {"я": "плачу́"}}, "government": [{"case": "accusative", "preposition": "за", "meaning": "pay FOR: плати́ть за обе́д"}]}),
    ("сто́ить", "v", "to cost", "daily", "A1", {"conj_overrides": {"present": {"я": "сто́ю", "ты": "сто́ишь", "он": "сто́ит", "мы": "сто́им", "вы": "сто́ите", "они": "сто́ят"}}}),
    ("открыва́ть", "v", "to open", "daily", "A2", {"aspect_partner": "откры́ть"}),
    ("закрыва́ть", "v", "to close", "daily", "A2", {"aspect_partner": "закры́ть"}),
    ("начина́ть", "v", "to begin", "daily", "A2", {"aspect_partner": "нача́ть"}),
    ("конча́ть", "v", "to finish", "daily", "A2", {"aspect_partner": "ко́нчить", "relations": [("synonym", "зака́нчивать", "more common in modern speech")]}),
    ("ждать", "v", "to wait", "daily", "A1", {"conj_overrides": {"present": {"я": "жду", "ты": "ждёшь", "он": "ждёт", "мы": "ждём", "вы": "ждёте", "они": "ждут"}, "past": {"f": "ждала́"}}, "government": [{"case": "genitive", "meaning": "wait for: ждать авто́буса"}]}),
    ("иска́ть", "v", "to look for", "daily", "A2", {"conj_overrides": {"present": {"я": "ищу́", "ты": "и́щешь", "он": "и́щет", "мы": "и́щем", "вы": "и́щете", "они": "и́щут"}}}),
    ("находи́ть", "v", "to find", "daily", "A2", {"aspect_partner": "найти́", "conj_overrides": {"present": {"я": "нахожу́"}}}),
    ("брать", "v", "to take", "daily", "A2", {"aspect_partner": "взять", "conj_overrides": {"present": {"я": "беру́", "ты": "берёшь", "он": "берёт", "мы": "берём", "вы": "берёте", "они": "беру́т"}, "past": {"f": "брала́"}}}),
    ("дава́ть", "v", "to give", "daily", "A1", {"aspect_partner": "дать", "conj_overrides": {"present": {"я": "даю́", "ты": "даёшь", "он": "даёт", "мы": "даём", "вы": "даёте", "они": "даю́т"}}, "government": [{"case": "dative", "meaning": "give TO someone"}]}),
    ("посыла́ть", "v", "to send", "daily", "A2", {"aspect_partner": "посла́ть"}),
    ("получа́ть", "v", "to receive", "daily", "A2", {"aspect_partner": "получи́ть"}),
    ("звони́ть", "v", "to call (phone)", "daily", "A1", {"aspect_partner": "позвони́ть", "government": [{"case": "dative", "meaning": "call someone: звони́ть ма́ме"}], "common_mistakes": ["Stress is always on the ending: звони́т, NOT зво́нит — a famous shibboleth"]}),
    ("слу́шать", "v", "to listen", "daily", "A1", {"aspect_partner": "послу́шать"}),
    ("слы́шать", "v", "to hear", "daily", "A2", {"conj_overrides": {"present": {"я": "слы́шу", "ты": "слы́шишь", "он": "слы́шит", "мы": "слы́шим", "вы": "слы́шите", "они": "слы́шат"}}, "relations": [("family", "слушать", "listen (deliberate) vs hear (perceive)")]}),
    ("смотре́ть", "v", "to watch, look", "daily", "A1", {"aspect_partner": "посмотре́ть", "conj_overrides": {"present": {"я": "смотрю́", "ты": "смо́тришь", "он": "смо́трит", "мы": "смо́трим", "вы": "смо́трите", "они": "смо́трят"}}}),
    ("пока́зывать", "v", "to show", "daily", "A2", {"aspect_partner": "показа́ть"}),
    ("расска́зывать", "v", "to tell, narrate", "daily", "A2", {"aspect_partner": "рассказа́ть"}),
    ("по́мнить", "v", "to remember", "daily", "A2"),
    ("забыва́ть", "v", "to forget", "daily", "A2", {"aspect_partner": "забы́ть"}),
    ("ве́рить", "v", "to believe", "daily", "A2", {"government": [{"case": "dative", "meaning": "believe someone: ве́рить дру́гу"}]}),
    ("игра́ть", "v", "to play", "daily", "A1", {"government": [{"case": "accusative", "preposition": "в", "meaning": "play a game: игра́ть в футбо́л"}, {"case": "prepositional", "preposition": "на", "meaning": "play an instrument: игра́ть на гита́ре"}]}),
    ("петь", "v", "to sing", "daily", "A2", {"conj_overrides": {"present": {"я": "пою́", "ты": "поёшь", "он": "поёт", "мы": "поём", "вы": "поёте", "они": "пою́т"}}}),
    ("танцева́ть", "v", "to dance", "daily", "A2"),
    ("рисова́ть", "v", "to draw", "daily", "A2"),
    ("занима́ться", "v", "to do, be occupied with", "daily", "A2", {"government": [{"case": "instrumental", "meaning": "занима́ться спо́ртом = do sports"}]}),
    ("встреча́ться", "v", "to meet; to date", "daily", "A2", {"government": [{"case": "instrumental", "preposition": "с", "meaning": "meet with someone"}]}),
    ("разгова́ривать", "v", "to converse", "daily", "A2"),
    ("узнава́ть", "v", "to find out; recognize", "daily", "B1", {"aspect_partner": "узна́ть", "conj_overrides": {"present": {"я": "узнаю́", "ты": "узнаёшь", "он": "узнаёт", "мы": "узнаём", "вы": "узнаёте", "они": "узнаю́т"}}}),
    ("реша́ть", "v", "to decide; solve", "daily", "A2", {"aspect_partner": "реши́ть"}),
    ("про́бовать", "v", "to try, taste", "daily", "A2", {"aspect_partner": "попро́бовать"}),
    ("успева́ть", "v", "to have time to, manage", "daily", "B1", {"aspect_partner": "успе́ть"}),
    ("опа́здывать", "v", "to be late", "daily", "A2", {"aspect_partner": "опозда́ть", "government": [{"case": "accusative", "preposition": "на", "meaning": "late FOR: опа́здывать на рабо́ту"}]}),

    # ── adjectives ──────────────────────────────────────────────────────
    ("молодо́й", "adj", "young", "adjectives", "A1"),
    ("бы́стрый", "adj", "fast", "adjectives", "A1", {"relations": [("derived", "быстро", "quickly")]}),
    ("ме́дленный", "adj", "slow", "adjectives", "A2"),
    ("лёгкий", "adj", "light; easy", "adjectives", "A2", {"usage_notes": "гк pronounced [хк]: [лёхкий]."}),
    ("тру́дный", "adj", "difficult", "adjectives", "A1"),
    ("тяжёлый", "adj", "heavy; hard", "adjectives", "A2"),
    ("дорого́й", "adj", "expensive; dear", "adjectives", "A1", {"meanings": ["expensive", "dear (in letters: Дорого́й Ива́н!)"]}),
    ("дешёвый", "adj", "cheap", "adjectives", "A2"),
    ("бога́тый", "adj", "rich", "adjectives", "A2"),
    ("бе́дный", "adj", "poor", "adjectives", "A2"),
    ("высо́кий", "adj", "tall, high", "adjectives", "A1"),
    ("ни́зкий", "adj", "low, short", "adjectives", "A2"),
    ("дли́нный", "adj", "long", "adjectives", "A2"),
    ("коро́ткий", "adj", "short", "adjectives", "A2"),
    ("широ́кий", "adj", "wide", "adjectives", "A2"),
    ("у́зкий", "adj", "narrow", "adjectives", "B1"),
    ("си́льный", "adj", "strong", "adjectives", "A2"),
    ("сла́бый", "adj", "weak", "adjectives", "A2"),
    ("чи́стый", "adj", "clean", "adjectives", "A2"),
    ("гря́зный", "adj", "dirty", "adjectives", "A2"),
    ("по́лный", "adj", "full; plump", "adjectives", "A2"),
    ("пусто́й", "adj", "empty", "adjectives", "A2"),
    ("гро́мкий", "adj", "loud", "adjectives", "A2"),
    ("ти́хий", "adj", "quiet", "adjectives", "A2"),
    ("све́тлый", "adj", "light, bright", "adjectives", "A2"),
    ("тёмный", "adj", "dark", "adjectives", "A2"),
    ("гла́вный", "adj", "main, chief", "adjectives", "A2"),
    ("ва́жный", "adj", "important", "adjectives", "A2"),
    ("интере́сный", "adj", "interesting", "adjectives", "A1"),
    ("ску́чный", "adj", "boring", "adjectives", "A2", {"usage_notes": "чн pronounced [шн]: [ску́шный]."}),
    ("изве́стный", "adj", "famous", "adjectives", "B1", {"usage_notes": "The т is silent: [изве́сный]."}),
    ("свобо́дный", "adj", "free (available)", "adjectives", "A2"),
    ("гото́вый", "adj", "ready", "adjectives", "A2"),
    ("после́дний", "adj", "last, latest", "adjectives", "A2"),
    ("сле́дующий", "adj", "next", "adjectives", "A2", {"inflections": {"forms": {"m": "сле́дующий", "f": "сле́дующая", "n": "сле́дующее", "pl": "сле́дующие"}}}),
    ("ка́ждый", "adj", "each, every", "adjectives", "A1"),
    ("друго́й", "adj", "other, different", "adjectives", "A1"),
    ("одина́ковый", "adj", "identical", "adjectives", "B1"),
    ("настоя́щий", "adj", "real, genuine; present", "adjectives", "B1", {"inflections": {"forms": {"m": "настоя́щий", "f": "настоя́щая", "n": "настоя́щее", "pl": "настоя́щие"}}}),

    # ── adverbs & connectors ────────────────────────────────────────────
    ("бы́стро", "adv", "quickly", "adverbs", "A1"),
    ("ме́дленно", "adv", "slowly", "adverbs", "A1"),
    ("гро́мко", "adv", "loudly", "adverbs", "A2"),
    ("ти́хо", "adv", "quietly", "adverbs", "A2"),
    ("легко́", "adv", "easily", "adverbs", "A2"),
    ("тру́дно", "adv", "with difficulty; it's hard", "adverbs", "A2"),
    ("мно́го", "adv", "much, many", "adverbs", "A1", {"government": [{"case": "genitive", "meaning": "мно́го рабо́ты"}]}),
    ("ма́ло", "adv", "little, few", "adverbs", "A1", {"government": [{"case": "genitive", "meaning": "ма́ло вре́мени"}]}),
    ("немно́го", "adv", "a little", "adverbs", "A1"),
    ("сли́шком", "adv", "too (excessively)", "adverbs", "A2"),
    ("почти́", "adv", "almost", "adverbs", "A2"),
    ("то́чно", "adv", "exactly; for sure", "adverbs", "A2"),
    ("коне́чно", "adv", "of course", "adverbs", "A1", {"usage_notes": "чн pronounced [шн]: [коне́шно]."}),
    ("наве́рное", "adv", "probably", "adverbs", "A2"),
    ("мо́жет быть", "phrase", "maybe", "adverbs", "A1"),
    ("вме́сте", "adv", "together", "adverbs", "A1"),
    ("отде́льно", "adv", "separately", "adverbs", "B1"),
    ("да́же", "particle", "even", "adverbs", "A2"),
    ("то́лько", "particle", "only", "adverbs", "A1"),
    ("та́кже", "conj", "also", "adverbs", "A2", {"relations": [("synonym", "тоже", "тоже after theme; также adds new info")]}),
    ("то́же", "particle", "also, too", "adverbs", "A1"),
    ("потому́ что", "conj", "because", "adverbs", "A1"),
    ("поэ́тому", "conj", "therefore", "adverbs", "A2"),
    ("е́сли", "conj", "if", "adverbs", "A1"),
    ("хотя́", "conj", "although", "adverbs", "B1"),
    ("что́бы", "conj", "in order to; so that", "adverbs", "A2", {"usage_notes": "After что́бы use past tense or infinitive: Я хочу́, что́бы ты знал."}),

    # ── tech & media ────────────────────────────────────────────────────
    ("компью́тер", "n", "computer", "tech", "A1", {"domain": "tech"}),
    ("телефо́н", "n", "telephone", "tech", "A1", {"domain": "tech"}),
    ("интерне́т", "n", "internet", "tech", "A1", {"domain": "tech"}),
    ("сайт", "n", "website", "tech", "A2", {"domain": "tech"}),
    ("па́пка", "n", "folder", "tech", "B1", {"domain": "tech", "decl_overrides": {"gen_pl": "па́пок"}}),
    ("файл", "n", "file", "tech", "B1", {"domain": "tech"}),
    ("экра́н", "n", "screen", "tech", "A2", {"domain": "tech"}),
    ("кла́виша", "n", "key (keyboard)", "tech", "B1", {"domain": "tech"}),
    ("сообще́ние", "n", "message", "tech", "A2", {"domain": "tech"}),
    ("письмо́", "n", "letter; email", "tech", "A1", {"decl_overrides": {"nom_pl": "пи́сьма", "gen_pl": "пи́сем"}}),
    ("но́вости", "n", "news", "tech", "A2", {"gender": "f", "inflections": {"declension": {"nom_pl": "но́вости", "gen_pl": "новосте́й"}}}),
    ("газе́та", "n", "newspaper", "tech", "A1", {"etymology": "From Italian gazzetta, a Venetian coin — the price of a paper."}),
    ("журна́л", "n", "magazine", "tech", "A1", {"relations": [("false_friend", "magazine", "журнал = magazine; магазин = shop")]}),
    ("програ́мма", "n", "program", "tech", "A2"),
    ("игра́", "n", "game", "tech", "A1", {"decl_overrides": {"nom_pl": "и́гры"}}),
    ("му́зыка", "n", "music", "tech", "A1"),
    ("пе́сня", "n", "song", "tech", "A1", {"decl_overrides": {"gen_pl": "пе́сен"}}),
    ("фильм", "n", "film", "tech", "A1"),
    ("фотогра́фия", "n", "photograph", "tech", "A1"),
    ("скача́ть", "v", "to download", "tech", "B1", {"aspect": "perfective", "domain": "tech", "register": "informal", "inflections": {"future": {"я": "скача́ю", "ты": "скача́ешь", "они": "скача́ют"}, "past": {"m": "скача́л", "f": "скача́ла", "pl": "скача́ли"}}}),
    ("включа́ть", "v", "to turn on", "tech", "A2", {"aspect_partner": "включи́ть"}),
    ("выключа́ть", "v", "to turn off", "tech", "A2", {"aspect_partner": "вы́ключить"}),

    # ── leisure & sport ─────────────────────────────────────────────────
    ("спорт", "n", "sport", "leisure", "A1"),
    ("футбо́л", "n", "soccer", "leisure", "A1"),
    ("хокке́й", "n", "hockey", "leisure", "A2", {"cultural_notes": "The national winter religion."}),
    ("ша́хматы", "n", "chess", "leisure", "A2", {"gender": "m", "inflections": {"declension": {"nom_pl": "ша́хматы", "gen_pl": "ша́хмат"}}, "etymology": "From Persian shāh māt — 'the king is dead'."}),
    ("бассе́йн", "n", "swimming pool", "leisure", "A2"),
    ("трениро́вка", "n", "training, workout", "leisure", "B1", {"decl_overrides": {"gen_pl": "трениро́вок"}}),
    ("бег", "n", "running", "leisure", "B1"),
    ("пла́вание", "n", "swimming", "leisure", "B1"),
    ("пла́вать", "v", "to swim (multidir.)", "leisure", "A2"),
    ("бе́гать", "v", "to run (multidir.)", "leisure", "A2"),
    ("выи́грывать", "v", "to win", "leisure", "B1", {"aspect_partner": "вы́играть"}),
    ("прои́грывать", "v", "to lose (a game)", "leisure", "B1", {"aspect_partner": "проигра́ть"}),
    ("боле́ть за", "phrase", "to root for (a team)", "leisure", "B1", {"usage_notes": "Я боле́ю за «Спарта́к» — same verb as 'to be ill', different construction."}),
    ("хо́бби", "n", "hobby", "leisure", "A2", {"gender": "n", "inflections": {"declension": {"nom_sg": "хо́бби"}}, "usage_notes": "Indeclinable."}),
    ("пода́рок", "n", "gift", "leisure", "A1", {"decl_overrides": {"gen_sg": "пода́рка", "nom_pl": "пода́рки", "gen_pl": "пода́рков"}}),
    ("та́нец", "n", "dance", "leisure", "A2", {"decl_overrides": {"gen_sg": "та́нца", "nom_pl": "та́нцы", "gen_pl": "та́нцев"}}),

    # ── communication & abstract ───────────────────────────────────────
    ("сло́во", "n", "word", "communication", "A1", {"decl_overrides": {"nom_pl": "слова́", "gen_pl": "слов"}}),
    ("предложе́ние", "n", "sentence; proposal", "communication", "A2", {"meanings": ["sentence", "offer/proposal", "marriage proposal"]}),
    ("разгово́р", "n", "conversation", "communication", "A2"),
    ("го́лос", "n", "voice; vote", "communication", "A2", {"decl_overrides": {"nom_pl": "голоса́"}}),
    ("шу́тка", "n", "joke", "communication", "A2", {"decl_overrides": {"gen_pl": "шу́ток"}}),
    ("пра́вда", "n", "truth", "communication", "A1", {"usage_notes": "Also 'really?': Пра́вда? and 'isn't it': ..., пра́вда?"}),
    ("ложь", "n", "lie", "communication", "B1", {"gender": "f", "inflections": {"declension": {"nom_sg": "ложь", "gen_sg": "лжи", "ins_sg": "ло́жью"}}}),
    ("смысл", "n", "meaning, sense", "communication", "B1"),
    ("иде́я", "n", "idea", "communication", "A2"),
    ("мысль", "n", "thought", "communication", "B1", {"gender": "f"}),
    ("мне́ние", "n", "opinion", "communication", "B1", {"usage_notes": "по-мо́ему = in my opinion."}),
    ("исто́рия", "n", "history; story", "communication", "A2", {"meanings": ["history", "story"]}),
    ("причи́на", "n", "reason, cause", "communication", "B1"),
    ("пробле́ма", "n", "problem", "communication", "A2"),
    ("возмо́жность", "n", "possibility, opportunity", "communication", "B1", {"gender": "f"}),
    ("посло́вица", "n", "proverb", "communication", "B2"),
    ("жизнь", "n", "life", "communication", "A1", {"gender": "f"}),
    ("смерть", "n", "death", "communication", "B1", {"gender": "f", "decl_overrides": {"gen_pl": "смерте́й"}}),
    ("война́", "n", "war", "communication", "A2", {"decl_overrides": {"nom_pl": "во́йны", "gen_pl": "войн"}}),
    ("исти́на", "n", "truth (philosophical)", "communication", "C1", {"register": "formal", "relations": [("synonym", "правда", "everyday truth vs deep truth")]}),
    ("душа́", "n", "soul", "communication", "B1", {"decl_overrides": {"acc_sg": "ду́шу", "nom_pl": "ду́ши"}, "cultural_notes": "The famous ру́сская душа́ — the Russian soul. Говори́ть по душа́м = a heart-to-heart talk."}),
    ("судьба́", "n", "fate, destiny", "communication", "B2", {"decl_overrides": {"nom_pl": "су́дьбы", "gen_pl": "су́деб"}}),
    ("наро́д", "n", "people, nation", "communication", "B1"),
    ("о́бщество", "n", "society", "communication", "B2"),
    ("госуда́рство", "n", "state (government)", "communication", "B2", {"domain": "legal"}),
    ("зако́н", "n", "law", "communication", "B1", {"domain": "legal"}),
    ("пра́во", "n", "right; law (field)", "communication", "B2", {"domain": "legal", "decl_overrides": {"nom_pl": "права́"}}),
    ("нало́г", "n", "tax", "communication", "B2", {"domain": "finance"}),
    ("бизнесме́н", "n", "businessman", "communication", "B1", {"animacy": "animate", "domain": "business"}),
    ("догово́р", "n", "contract", "communication", "B2", {"domain": "business", "decl_overrides": {"nom_pl": "догово́ры"}}),
    ("сде́лка", "n", "deal", "communication", "B2", {"domain": "business", "decl_overrides": {"gen_pl": "сде́лок"}}),
    ("счёт", "n", "bill; account", "communication", "A2", {"meanings": ["bill (restaurant)", "bank account", "score (sport)"], "decl_overrides": {"nom_pl": "счета́"}}),
]
