"""Investment Memo Generator.

Builds a structured investment memo for a single security entirely from its
stored fundamentals. Bull/bear/risk/catalyst bullets are generated by applying
real thresholds to the metrics, and a 0-100 confidence score blends the
scanner subscores. Advisory only — not a recommendation to buy or sell.
"""
from __future__ import annotations

from .scanner import OpportunityScanner


class MemoGenerator:
    def __init__(self, universe, scanner: OpportunityScanner | None = None):
        self.universe = universe
        self.scanner = scanner or OpportunityScanner(universe)

    def generate(self, symbol: str) -> dict:
        s = self.universe.get(symbol)
        if not s:
            raise ValueError(f"security not found: {symbol}")

        tier = self.universe.cap_tier(s.get("market_cap", 0))
        val, val_sig, _ = self.scanner._value(s)
        qual, qual_sig, _ = self.scanner._quality(s)
        grow, grow_sig, _ = self.scanner._growth(s)
        compounder, comp_sig, _ = self.scanner._compounder(s)

        rg1, rg2 = self.scanner._series_deltas(s.get("revenue_3y", []))
        eg1, eg2 = self.scanner._series_deltas(s.get("eps_3y", []))

        # ── narrative ────────────────────────────────────────────────────────
        business_overview = (
            f"{s['name']} ({s['symbol']}) is a {tier}-cap {s['sector']} company "
            f"in the {s['industry']} industry, listed on {s['exchange']}. "
            f"Trailing revenue is ${s['revenue'] / 1000:.1f}B with operating "
            f"margins of {s['operating_margin'] * 100:.0f}% and ROIC of "
            f"{s['roic'] * 100:.0f}%. It is followed by {s['analyst_coverage']} "
            f"sell-side analysts."
        )

        # ── bull case ────────────────────────────────────────────────────────
        bull = []
        if s["roic"] >= 0.15:
            bull.append(f"High returns on capital (ROIC {s['roic'] * 100:.0f}%) signal a durable economic moat.")
        if s["gross_margin"] >= 0.55:
            bull.append(f"Premium gross margin of {s['gross_margin'] * 100:.0f}% indicates strong pricing power.")
        if rg2 > 0.08:
            bull.append(f"Revenue is compounding at {rg2 * 100:.0f}% with a multi-year growth runway.")
        if s["fcf_yield"] >= 0.05:
            bull.append(f"Generates a {s['fcf_yield'] * 100:.1f}% free-cash-flow yield, funding buybacks/dividends.")
        if s["pe"] > 0 and s["pe"] <= 12:
            bull.append(f"Inexpensive at {s['pe']:.1f}x earnings versus market and history.")
        if s["dividend_yield"] >= 0.03:
            bull.append(f"Pays a {s['dividend_yield'] * 100:.1f}% dividend yield for income investors.")
        if s["insider_ownership"] >= 0.05:
            bull.append(f"Meaningful insider ownership ({s['insider_ownership'] * 100:.0f}%) aligns management with shareholders.")
        if eg2 > eg1 and eg2 > 0:
            bull.append(f"Earnings momentum is accelerating (EPS growth {eg2 * 100:.0f}% vs {eg1 * 100:.0f}% prior).")
        if not bull:
            bull.append("Stable, cash-generative business with no single dominant strength.")

        # ── bear case ────────────────────────────────────────────────────────
        bear = []
        equity = s.get("equity", 0) or 0.0
        d2e = (s.get("total_debt", 0) / equity) if equity > 0 else None
        if d2e is not None and d2e > 1.5:
            bear.append(f"Leveraged balance sheet (debt/equity {d2e:.1f}x) raises financial risk.")
        elif equity <= 0:
            bear.append("Negative book equity (often buyback-driven) limits balance-sheet flexibility.")
        if s["pe"] > 30:
            bear.append(f"Rich valuation at {s['pe']:.1f}x earnings leaves little margin of safety.")
        if s["ev_ebitda"] > 20:
            bear.append(f"Elevated {s['ev_ebitda']:.1f}x EV/EBITDA prices in a lot of optimism.")
        if rg2 < 0:
            bear.append(f"Revenue is contracting ({rg2 * 100:.0f}%), pointing to demand or cyclical pressure.")
        if s["net_income"] < 0:
            bear.append("Currently unprofitable on a net-income basis.")
        if s["operating_margin"] < 0.08 and s["operating_margin"] >= 0:
            bear.append(f"Thin operating margin ({s['operating_margin'] * 100:.0f}%) offers little error budget.")
        if s["roic"] < 0.08:
            bear.append(f"Low returns on capital (ROIC {s['roic'] * 100:.0f}%) suggest weak competitive economics.")
        if not bear:
            bear.append("No glaring weaknesses, but multiple expansion may be limited from here.")

        # ── risks ────────────────────────────────────────────────────────────
        risks = [
            f"Sector risk: {s['sector']} is sensitive to macro and policy shifts.",
            "Execution risk on growth and margin assumptions embedded in the thesis.",
        ]
        if tier in ("micro", "small"):
            risks.append("Liquidity and volatility risk inherent to smaller-cap equities.")
        if s["analyst_coverage"] <= 5:
            risks.append("Thin analyst coverage means information is sparse and prices can be inefficient.")
        if d2e is not None and d2e > 1.0:
            risks.append("Refinancing/interest-rate risk given the debt load.")

        # ── catalysts ────────────────────────────────────────────────────────
        catalysts = []
        if eg2 > eg1:
            catalysts.append("Continued earnings acceleration could drive estimate revisions higher.")
        if s["fcf_yield"] >= 0.05:
            catalysts.append("Capital returns (buybacks/dividend hikes) from robust free cash flow.")
        if val >= 60:
            catalysts.append("Valuation re-rating toward peers as the discount narrows.")
        if tier in ("micro", "small") and s["analyst_coverage"] <= 5:
            catalysts.append("New sell-side initiations could broaden the shareholder base.")
        if not catalysts:
            catalysts.append("Operational milestones and steady compounding of intrinsic value.")

        # ── valuation read ───────────────────────────────────────────────────
        cheap_signals = sum([
            0 < s["pe"] <= 12,
            0 < s["ev_ebitda"] <= 8,
            s["fcf_yield"] >= 0.06,
            0 < s["price_to_fcf"] <= 12,
        ])
        expensive_signals = sum([
            s["pe"] > 30 or s["pe"] <= 0,
            s["ev_ebitda"] > 20,
            s["price_to_fcf"] > 35 or s["price_to_fcf"] <= 0,
        ])
        if cheap_signals >= 2:
            read = "cheap"
        elif expensive_signals >= 2:
            read = "expensive"
        else:
            read = "fair"
        valuation = {
            "pe": s["pe"], "ev_ebitda": s["ev_ebitda"],
            "price_to_fcf": s["price_to_fcf"], "fcf_yield": s["fcf_yield"],
            "dividend_yield": s["dividend_yield"], "read": read,
            "value_score": round(val, 1),
        }

        quality_analysis = {
            "roic": s["roic"], "roe": s["roe"],
            "gross_margin": s["gross_margin"], "operating_margin": s["operating_margin"],
            "debt_to_equity": round(d2e, 2) if d2e is not None else None,
            "quality_score": round(qual, 1),
            "compounder_score": round(compounder, 1),
            "signals": qual_sig,
        }

        # ── competitive position ─────────────────────────────────────────────
        if s["roic"] >= 0.20 and s["gross_margin"] >= 0.50:
            competitive_position = (
                "Wide-moat: high returns on capital and premium margins point to "
                "durable competitive advantages.")
        elif s["roic"] >= 0.12:
            competitive_position = (
                "Narrow-moat: above-average returns on capital suggest a defensible "
                "but contestable position.")
        else:
            competitive_position = (
                "No-moat / cyclical: returns hover near the cost of capital; results "
                "are likely commodity- or cycle-driven.")

        # ── confidence score (0-100) ─────────────────────────────────────────
        confidence = (0.35 * qual + 0.25 * val + 0.20 * grow + 0.20 * compounder)
        # penalize unprofitable / very thinly covered names
        if s["net_income"] < 0:
            confidence -= 12
        if s["analyst_coverage"] <= 2:
            confidence -= 5
        confidence = float(max(0.0, min(100.0, confidence)))

        return {
            "symbol": s["symbol"], "name": s["name"], "sector": s["sector"],
            "industry": s["industry"], "cap_tier": tier,
            "business_overview": business_overview,
            "bull_case": bull, "bear_case": bear, "risks": risks,
            "catalysts": catalysts, "valuation": valuation,
            "quality_analysis": quality_analysis,
            "competitive_position": competitive_position,
            "confidence_score": round(confidence, 1),
        }


_instance = None
